package com.esn.smp.gameplay;
import org.bukkit.*;import org.bukkit.command.*;import org.bukkit.entity.Player;import org.bukkit.event.*;import org.bukkit.event.inventory.InventoryClickEvent;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.*;import org.bukkit.plugin.java.JavaPlugin;import java.util.*;
public final class AdminControlCenter implements Listener,CommandExecutor{
 private final JavaPlugin plugin;private final SMPGameplay gameplay;private final V18Core staff;private final Map<UUID,UUID> selected=new HashMap<>();
 public AdminControlCenter(JavaPlugin plugin,SMPGameplay gameplay,V18Core staff){this.plugin=plugin;this.gameplay=gameplay;this.staff=staff;}
 public boolean onCommand(CommandSender s,Command c,String l,String[] a){if(!(s instanceof Player p)){s.sendMessage("Players only.");return true;}if(!p.hasPermission("esnsmp.admin")){p.sendMessage(ChatColor.RED+"No permission.");return true;}open(p);return true;}
 private ItemStack item(Material m,String name,String... lore){ItemStack i=new ItemStack(m);ItemMeta im=i.getItemMeta();im.setDisplayName(name);im.setLore(Arrays.asList(lore));i.setItemMeta(im);return i;}
 private void open(Player p){Inventory i=Bukkit.createInventory(null,54,ChatColor.DARK_RED+"ESN Admin Control Center");i.setItem(10,item(Material.EMERALD,ChatColor.GREEN+"Open Server Shop",ChatColor.GRAY+"Open the same /shop menu players use."));i.setItem(12,item(Material.ENDER_CHEST,ChatColor.LIGHT_PURPLE+"Open Loot Crates",ChatColor.GRAY+"Open the same /crates menu players use."));i.setItem(14,item(Material.COMPASS,ChatColor.AQUA+"Run Diagnostics",ChatColor.GRAY+"Runs /diagnostics."));i.setItem(16,item(Material.NETHER_STAR,ChatColor.GOLD+"World Boss Controls",ChatColor.GRAY+"Click to run /boss world."));int slot=27;for(Player q:Bukkit.getOnlinePlayers()){if(slot>=54)break;i.setItem(slot++,head(q));}i.setItem(49,item(Material.BARRIER,ChatColor.RED+"Close"));p.openInventory(i);}
 private ItemStack head(Player q){ItemStack i=new ItemStack(Material.PLAYER_HEAD);SkullMeta m=(SkullMeta)i.getItemMeta();m.setOwningPlayer(q);m.setDisplayName(ChatColor.YELLOW+q.getName());m.setLore(List.of(ChatColor.GREEN+"ONLINE",ChatColor.GRAY+"Health: "+Math.round(q.getHealth())+"/"+Math.round(q.getAttribute(org.bukkit.attribute.Attribute.MAX_HEALTH).getValue()),ChatColor.GRAY+"World: "+q.getWorld().getName(),ChatColor.GRAY+"Click to manage player"));i.setItemMeta(m);return i;}
 private void playerMenu(Player admin,Player target){selected.put(admin.getUniqueId(),target.getUniqueId());Inventory i=Bukkit.createInventory(null,27,ChatColor.DARK_RED+"Manage • "+target.getName());i.setItem(4,head(target));i.setItem(10,item(Material.ICE,ChatColor.AQUA+"Freeze / Unfreeze",ChatColor.GRAY+"Toggle the existing ESN freeze system."));i.setItem(12,item(Material.IRON_BOOTS,ChatColor.YELLOW+"Kick",ChatColor.GRAY+"Remove this player from the server."));i.setItem(14,item(Material.BARRIER,ChatColor.DARK_RED+"Ban",ChatColor.GRAY+"Ban this player from the server."));i.setItem(16,item(Material.CHEST,ChatColor.GOLD+"View Inventory",ChatColor.GRAY+"Open ESN /invsee."));i.setItem(22,item(Material.ARROW,ChatColor.YELLOW+"Back"));admin.openInventory(i);}
 @EventHandler public void click(InventoryClickEvent e){String title=e.getView().getTitle();if(!title.startsWith(ChatColor.DARK_RED+"ESN Admin Control Center")&&!title.startsWith(ChatColor.DARK_RED+"Manage • "))return;e.setCancelled(true);if(!(e.getWhoClicked() instanceof Player p)||!p.hasPermission("esnsmp.admin"))return;int s=e.getRawSlot();if(title.startsWith(ChatColor.DARK_RED+"ESN Admin Control Center")){if(s==10){gameplay.openShop(p);return;}if(s==12){gameplay.openCrates(p);return;}if(s==14){p.closeInventory();p.performCommand("diagnostics");return;}if(s==16){p.closeInventory();p.performCommand("boss world");return;}if(s==49){p.closeInventory();return;}ItemStack clicked=e.getCurrentItem();if(clicked!=null&&clicked.getType()==Material.PLAYER_HEAD&&clicked.getItemMeta() instanceof SkullMeta sm&&sm.getOwningPlayer()!=null){Player t=Bukkit.getPlayer(sm.getOwningPlayer().getUniqueId());if(t==null){p.sendMessage(ChatColor.RED+"That player went offline.");open(p);}else playerMenu(p,t);}return;}if(s==22){open(p);return;}UUID id=selected.get(p.getUniqueId());Player t=id==null?null:Bukkit.getPlayer(id);if(t==null){p.sendMessage(ChatColor.RED+"That player is no longer online.");open(p);return;}switch(s){case 10->{p.closeInventory();p.performCommand("freeze "+t.getName());}case 12->{t.kickPlayer("Kicked by ESN staff.");p.sendMessage(ChatColor.YELLOW+"Kicked "+t.getName()+".");open(p);}case 14->{Bukkit.getBanList(BanList.Type.NAME).addBan(t.getName(),"Banned by ESN staff.",null,p.getName());t.kickPlayer("Banned by ESN staff.");Bukkit.broadcastMessage(ChatColor.RED+t.getName()+" was banned by ESN staff.");open(p);}case 16->{p.closeInventory();p.performCommand("invsee "+t.getName());}}}
}
