package com.esn.smp.gameplay;
import org.bukkit.*;import org.bukkit.command.*;import org.bukkit.entity.*;import org.bukkit.event.*;import org.bukkit.event.entity.*;import org.bukkit.event.player.PlayerFishEvent;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.ItemMeta;import org.bukkit.persistence.*;import org.bukkit.plugin.java.JavaPlugin;import java.util.*;import java.util.concurrent.ThreadLocalRandom;
public final class AdventureSystems implements Listener,CommandExecutor{
 private final JavaPlugin p;private final Map<UUID,Integer> mastery=new HashMap<>(),pity=new HashMap<>(),bossKills=new HashMap<>(),fish=new HashMap<>();private final NamespacedKey artifact,pet,treasure;private long nextInvasion,nextBlood,nextMeteor;
 public AdventureSystems(JavaPlugin p){this.p=p;artifact=new NamespacedKey(p,"adventure_artifact");pet=new NamespacedKey(p,"boss_pet");treasure=new NamespacedKey(p,"treasure_map");long n=System.currentTimeMillis();nextInvasion=n+1800000;nextBlood=n+2700000;nextMeteor=n+3600000;Bukkit.getScheduler().runTaskTimer(p,this::events,1200L,1200L);Bukkit.getScheduler().runTaskLater(p,this::diagnostics,100L);}
 public boolean onCommand(CommandSender s,Command c,String l,String[] a){if(!(s instanceof Player x))return true;switch(c.getName()){case"mastery"->x.sendMessage(ChatColor.LIGHT_PURPLE+"Realm Mastery "+String.valueOf(mastery.getOrDefault(x.getUniqueId(),0))+" | Bosses "+bossKills.getOrDefault(x.getUniqueId(),0)+" | Fishing "+fish.getOrDefault(x.getUniqueId(),0));case"codex"->x.sendMessage(ChatColor.GOLD+"ESN Codex: "+bossKills.getOrDefault(x.getUniqueId(),0)+" regional/world bosses defeated. Explore every biome to discover relic families.");case"pets"->x.sendMessage(ChatColor.AQUA+"Boss pets are rare cosmetic trophies. Keep one in your inventory to show the boss you conquered.");case"treasure"->x.sendMessage(ChatColor.YELLOW+"Treasure maps can drop from bosses and point you toward a nearby cache location.");case"progression"->x.sendMessage(ChatColor.GREEN+"Progression: Biome Bosses → Relics → Forge/Gear → Dungeons/Raids → Realm Mastery → Realm 100 Ascension.");case"diagnostics"->{if(!x.hasPermission("esnsmp.admin"))return true;diagnostics();x.sendMessage(ChatColor.GREEN+"ESN diagnostics written to console.");}}return true;}
 @EventHandler public void boss(EntityDeathEvent e){Set<String> t=e.getEntity().getScoreboardTags();if(!t.contains("esnBiomeBoss")&&!t.contains("esnSwampBoss")&&!t.contains("esnWorldBoss"))return;Player x=e.getEntity().getKiller();if(x==null)return;UUID u=x.getUniqueId();bossKills.merge(u,1,Integer::sum);mastery.merge(u,t.contains("esnWorldBoss")?25:10,Integer::sum);int miss=pity.merge(u,1,Integer::sum);double rare=Math.min(.30,.03+miss*.005);if(ThreadLocalRandom.current().nextDouble()<rare){ItemStack a=new ItemStack(Material.NETHER_STAR);ItemMeta m=a.getItemMeta();m.setDisplayName(ChatColor.LIGHT_PURPLE+"Ascendant Boss Artifact");m.setLore(List.of(ChatColor.GRAY+"Rare ability-bearing progression artifact",ChatColor.GOLD+"Boss pity reset"));m.getPersistentDataContainer().set(artifact,PersistentDataType.BYTE,(byte)1);a.setItemMeta(m);e.getDrops().add(a);pity.put(u,0);Bukkit.broadcastMessage(ChatColor.LIGHT_PURPLE+x.getName()+" found an Ascendant Boss Artifact!");}if(ThreadLocalRandom.current().nextDouble()<.015){ItemStack a=new ItemStack(Material.ALLAY_SPAWN_EGG);ItemMeta m=a.getItemMeta();m.setDisplayName(ChatColor.AQUA+"Mini Boss Companion");m.getPersistentDataContainer().set(pet,PersistentDataType.BYTE,(byte)1);a.setItemMeta(m);e.getDrops().add(a);}if(ThreadLocalRandom.current().nextDouble()<.08)e.getDrops().add(treasure(x));}
 private ItemStack treasure(Player x){ItemStack a=new ItemStack(Material.FILLED_MAP);ItemMeta m=a.getItemMeta();m.setDisplayName(ChatColor.GOLD+"ESN Treasure Map");m.setLore(List.of(ChatColor.GRAY+"Treasure signal near:",ChatColor.YELLOW+String.valueOf(x.getLocation().getBlockX()+ThreadLocalRandom.current().nextInt(-300,301))+", "+(x.getLocation().getBlockZ()+ThreadLocalRandom.current().nextInt(-300,301))));m.getPersistentDataContainer().set(treasure,PersistentDataType.BYTE,(byte)1);a.setItemMeta(m);return a;}
 @EventHandler public void fish(PlayerFishEvent e){if(e.getState()!=PlayerFishEvent.State.CAUGHT_FISH)return;fish.merge(e.getPlayer().getUniqueId(),1,Integer::sum);if(ThreadLocalRandom.current().nextDouble()<.03){e.getPlayer().getWorld().dropItemNaturally(e.getPlayer().getLocation(),new ItemStack(Material.HEART_OF_THE_SEA));e.getPlayer().sendMessage(ChatColor.AQUA+"Rare fishing treasure!");}}
 @EventHandler public void scale(EntityDamageByEntityEvent e){if(!(e.getEntity() instanceof LivingEntity z))return;Set<String> t=z.getScoreboardTags();if(!t.contains("esnBiomeBoss")&&!t.contains("esnWorldBoss")&&!t.contains("esnSwampBoss"))return;int nearby=0;for(Player q:z.getWorld().getPlayers())if(q.getLocation().distanceSquared(z.getLocation())<2500)nearby++;if(nearby>1)e.setDamage(e.getDamage()*(1.0+Math.min(1.5,(nearby-1)*.12)));}
 private void events(){long n=System.currentTimeMillis();if(n>=nextInvasion){Bukkit.broadcastMessage(ChatColor.DARK_PURPLE+"VOID INVASION: regional bosses are empowered for the next cycle!");nextInvasion=n+3600000;}if(n>=nextBlood){Bukkit.broadcastMessage(ChatColor.RED+"BLOOD MOON: hunt hostile mobs and bosses for heightened progression!");nextBlood=n+5400000;}if(n>=nextMeteor){for(World w:Bukkit.getWorlds())if(w.getEnvironment()==World.Environment.NORMAL&&!w.getPlayers().isEmpty()){Player x=w.getPlayers().get(0);Location q=x.getLocation().clone().add(ThreadLocalRandom.current().nextInt(-150,151),0,ThreadLocalRandom.current().nextInt(-150,151));q.setY(w.getHighestBlockYAt(q.getBlockX(),q.getBlockZ())+1);w.dropItemNaturally(q,new ItemStack(Material.AMETHYST_SHARD,8));Bukkit.broadcastMessage(ChatColor.AQUA+"METEOR EVENT: a crystal meteor landed near "+String.valueOf(q.getBlockX())+", "+q.getBlockZ()+"!");break;}nextMeteor=n+7200000;}}
 private void diagnostics(){p.getLogger().info("[ESN Diagnostics] Adventure systems online; Realm crates="+MegaCrates.COUNT+", rewards="+(MegaCrates.COUNT*MegaCrates.ITEMS)+".");for(int t=0;t<MegaCrates.COUNT;t++)if(MegaCrates.key(t).getMaxStackSize()<64)p.getLogger().warning("[ESN Diagnostics] Realm key "+(t+1)+" is not 64-stackable.");}
}