package com.esn.smp.gameplay;
import org.bukkit.*;import org.bukkit.command.*;import org.bukkit.entity.*;import org.bukkit.event.*;import org.bukkit.event.entity.*;import org.bukkit.event.player.PlayerFishEvent;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.ItemMeta;import org.bukkit.persistence.*;import org.bukkit.plugin.java.JavaPlugin;import java.util.*;import java.util.concurrent.ThreadLocalRandom;
public final class AdventureSystems implements Listener,CommandExecutor{
 private final JavaPlugin p;private final Map<UUID,Integer> mastery=new HashMap<>(),fish=new HashMap<>();private final NamespacedKey artifact,pet,treasure;private long nextInvasion,nextBlood,nextMeteor,voidUntil,bloodUntil;
 public AdventureSystems(JavaPlugin p){this.p=p;artifact=new NamespacedKey(p,"adventure_artifact");pet=new NamespacedKey(p,"boss_pet");treasure=new NamespacedKey(p,"treasure_map");long n=System.currentTimeMillis();nextInvasion=n+1800000;nextBlood=n+2700000;nextMeteor=n+3600000;Bukkit.getScheduler().runTaskTimer(p,this::events,1200L,1200L);Bukkit.getScheduler().runTaskLater(p,this::diagnostics,100L);}
 public boolean onCommand(CommandSender s,Command c,String l,String[] a){if(!(s instanceof Player x))return true;switch(c.getName()){case"mastery"->x.sendMessage(ChatColor.LIGHT_PURPLE+"Realm Mastery "+String.valueOf(mastery.getOrDefault(x.getUniqueId(),0))+" | Fishing "+fish.getOrDefault(x.getUniqueId(),0));case"codex"->x.sendMessage(ChatColor.GOLD+"ESN Codex: boss records and rewards are tracked by the unified ESN boss progression systems.");case"pets"->x.sendMessage(ChatColor.AQUA+"Boss pets are rare cosmetic trophies. Keep one in your inventory to show the boss you conquered.");case"treasure"->x.sendMessage(ChatColor.YELLOW+"Treasure maps can drop from bosses and point you toward a nearby cache location.");case"progression"->x.sendMessage(ChatColor.GREEN+"Progression: Biome Bosses → Relics → Forge/Gear → Dungeons/Raids → Realm Mastery → Realm 100 Ascension.");case"diagnostics"->{if(!x.hasPermission("esnsmp.admin"))return true;diagnostics();int bosses=0,encounters=0;for(World w:Bukkit.getWorlds())for(LivingEntity z:w.getLivingEntities()){Set<String> tags=z.getScoreboardTags();if(tags.contains("esnWorldBoss")||tags.contains("esnSwampBoss")||tags.contains("esnBiomeBoss"))bosses++;if(tags.contains("esnRaid")||tags.contains("esnRaidBoss")||tags.contains("esnDungeonBoss"))encounters++;}World w=Bukkit.getWorlds().isEmpty()?null:Bukkit.getWorlds().get(0);x.sendMessage(ChatColor.GREEN+"ESN diagnostics: "+ChatColor.WHITE+"bosses="+bosses+" encounter mobs="+encounters+" realms="+MegaCrates.COUNT);if(w!=null){Location sp=w.getSpawnLocation();x.sendMessage(ChatColor.GRAY+"World spawn: "+w.getName()+" "+sp.getBlockX()+", "+sp.getBlockY()+", "+sp.getBlockZ());}x.sendMessage(ChatColor.GRAY+"Full diagnostics written to console.");}}return true;}
 private ItemStack treasure(Player x){ItemStack a=new ItemStack(Material.FILLED_MAP);ItemMeta m=a.getItemMeta();m.setDisplayName(ChatColor.GOLD+"ESN Treasure Map");m.setLore(List.of(ChatColor.GRAY+"Treasure signal near:",ChatColor.YELLOW+String.valueOf(x.getLocation().getBlockX()+ThreadLocalRandom.current().nextInt(-300,301))+", "+(x.getLocation().getBlockZ()+ThreadLocalRandom.current().nextInt(-300,301))));m.getPersistentDataContainer().set(treasure,PersistentDataType.BYTE,(byte)1);a.setItemMeta(m);return a;}
 @EventHandler public void fish(PlayerFishEvent e){if(e.getState()!=PlayerFishEvent.State.CAUGHT_FISH)return;fish.merge(e.getPlayer().getUniqueId(),1,Integer::sum);if(ThreadLocalRandom.current().nextDouble()<.03){e.getPlayer().getWorld().dropItemNaturally(e.getPlayer().getLocation(),new ItemStack(Material.HEART_OF_THE_SEA));e.getPlayer().sendMessage(ChatColor.AQUA+"Rare fishing treasure!");}}
 @EventHandler public void eventKill(EntityDeathEvent e){Player k=e.getEntity().getKiller();if(k!=null&&e.getEntity() instanceof Monster&&System.currentTimeMillis()<bloodUntil){k.giveExp(12);k.sendActionBar(ChatColor.RED+"Blood Moon: +12 XP");}}
 @EventHandler public void scale(EntityDamageByEntityEvent e){if(!(e.getEntity() instanceof LivingEntity z))return;Set<String> t=z.getScoreboardTags();if(!t.contains("esnBiomeBoss")&&!t.contains("esnWorldBoss")&&!t.contains("esnSwampBoss"))return;int nearby=0;for(Player q:z.getWorld().getPlayers())if(q.getLocation().distanceSquared(z.getLocation())<2500)nearby++;if(nearby>1)e.setDamage(e.getDamage()*(1.0+Math.min(1.5,(nearby-1)*.12)));}
 private void events(){long n=System.currentTimeMillis();if(n>=nextInvasion){voidUntil=n+15*60_000L;Bukkit.broadcastMessage(ChatColor.DARK_PURPLE+"VOID INVASION: regional bosses are empowered for 15 minutes!");for(World w:Bukkit.getWorlds())for(LivingEntity z:w.getLivingEntities())if(z.getScoreboardTags().contains("esnBiomeBoss")||z.getScoreboardTags().contains("esnSwampBoss")){z.addPotionEffect(new org.bukkit.potion.PotionEffect(org.bukkit.potion.PotionEffectType.STRENGTH,18000,1));z.addPotionEffect(new org.bukkit.potion.PotionEffect(org.bukkit.potion.PotionEffectType.RESISTANCE,18000,0));}nextInvasion=n+3600000;}if(n>=nextBlood){bloodUntil=n+15*60_000L;Bukkit.broadcastMessage(ChatColor.RED+"BLOOD MOON: hostile kills award bonus XP for 15 minutes!");nextBlood=n+5400000;}if(n>=nextMeteor){for(World w:Bukkit.getWorlds())if(w.getEnvironment()==World.Environment.NORMAL&&!w.getPlayers().isEmpty()){Player x=w.getPlayers().get(0);Location q=x.getLocation().clone().add(ThreadLocalRandom.current().nextInt(-150,151),0,ThreadLocalRandom.current().nextInt(-150,151));q.setY(w.getHighestBlockYAt(q.getBlockX(),q.getBlockZ())+1);w.dropItemNaturally(q,new ItemStack(Material.AMETHYST_SHARD,8));Bukkit.broadcastMessage(ChatColor.AQUA+"METEOR EVENT: a crystal meteor landed near "+String.valueOf(q.getBlockX())+", "+q.getBlockZ()+"!");break;}nextMeteor=n+7200000;}}
 private void diagnostics(){int declared=p.getDescription().getCommands().size(),available=0;for(String n:p.getDescription().getCommands().keySet())if(p.getCommand(n)!=null)available++;p.getLogger().info("[ESN Diagnostics] Commands available="+available+"/"+declared+".");p.getLogger().info("[ESN Diagnostics] Adventure systems online; Realm crates="+MegaCrates.COUNT+", rewards="+(MegaCrates.COUNT*MegaCrates.ITEMS)+".");for(int t=0;t<MegaCrates.COUNT;t++)if(MegaCrates.key(t).getMaxStackSize()<64)p.getLogger().warning("[ESN Diagnostics] Realm key "+(t+1)+" is not 64-stackable.");}
}