package com.esn.smp.gameplay;
import org.bukkit.*;import org.bukkit.block.Biome;import org.bukkit.entity.*;import org.bukkit.event.*;import org.bukkit.event.entity.EntityDeathEvent;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.ItemMeta;import org.bukkit.persistence.*;import org.bukkit.plugin.java.JavaPlugin;import java.util.*;import java.util.concurrent.ThreadLocalRandom;
public final class BiomeBosses implements Listener{
 private final JavaPlugin p;private final Map<String,Set<UUID>> active=new HashMap<>();private final NamespacedKey matKey;
 private record Theme(String name,EntityType type,Material drop,ChatColor color){}
 public BiomeBosses(JavaPlugin p){this.p=p;matKey=new NamespacedKey(p,"biome_relic");Bukkit.getScheduler().runTaskTimer(p,this::scan,300L,1200L);}
 private String family(Biome b){String n=b.name();if(n.contains("DESERT")||n.contains("BADLANDS"))return"DESERT";if(n.contains("SNOW")||n.contains("FROZEN")||n.contains("ICE")||n.contains("GROVE"))return"FROST";if(n.contains("JUNGLE")||n.contains("BAMBOO"))return"JUNGLE";if(n.contains("OCEAN")||n.contains("BEACH")||n.contains("RIVER"))return"OCEAN";if(n.contains("NETHER")||n.contains("CRIMSON")||n.contains("WARPED")||n.contains("SOUL")||n.contains("BASALT"))return"NETHER";if(n.contains("END"))return"END";if(n.contains("SWAMP"))return"SWAMP";if(n.contains("TAIGA"))return"TAIGA";if(n.contains("SAVANNA"))return"SAVANNA";if(n.contains("MUSHROOM"))return"MUSHROOM";if(n.contains("CHERRY"))return"CHERRY";if(n.contains("DARK_FOREST"))return"DARK";if(n.contains("FOREST"))return"FOREST";if(n.contains("MOUNTAIN")||n.contains("PEAK")||n.contains("HILLS")||n.contains("SLOPE"))return"MOUNTAIN";if(n.contains("CAVE")||n.contains("DEEP_DARK"))return"CAVE";return"PLAINS";}
 private Theme[] themes(String f){return switch(f){case"DESERT"->new Theme[]{t("Sand Golem",EntityType.IRON_GOLEM,Material.SAND),t("Dune King",EntityType.HUSK,Material.SANDSTONE),t("Scarab Lord",EntityType.RAVAGER,Material.GOLD_INGOT),t("Sun Warden",EntityType.VINDICATOR,Material.SUNFLOWER)};case"FROST"->a("Frost Titan","Ice Wraith","Blizzard Golem","Frozen King",Material.PACKED_ICE);case"JUNGLE"->a("Vine Colossus","Jungle Stalker","Ancient Guardian","Venom King",Material.VINE);case"OCEAN"->new Theme[]{t("Abyss Leviathan",EntityType.ELDER_GUARDIAN,Material.PRISMARINE_SHARD),t("Tide Guardian",EntityType.GUARDIAN,Material.PRISMARINE_CRYSTALS),t("Drowned Emperor",EntityType.DROWNED,Material.NAUTILUS_SHELL),t("Reef Colossus",EntityType.IRON_GOLEM,Material.HEART_OF_THE_SEA)};case"NETHER"->a("Infernal Titan","Magma Lord","Soul Reaper","Crimson Warlord",Material.MAGMA_CREAM);case"END"->a("Void Colossus","Ender Sovereign","Rift Warden","Dragon Disciple",Material.ECHO_SHARD);case"TAIGA"->a("Pine Reaper","Winter Ravager","Wolf King","Ancient Trapper",Material.SPRUCE_LOG);case"SAVANNA"->a("Sunfang","Savanna Titan","Acacia Warden","Dust Reaver",Material.ACACIA_LOG);case"MUSHROOM"->a("Mycelium Ancient","Spore Titan","Mushroom King","Fungal Horror",Material.MYCELIUM);case"CHERRY"->a("Petal Warden","Sakura Knight","Bloom Titan","Cherry Sovereign",Material.CHERRY_LOG);case"DARK"->a("Night Stalker","Darkwood Reaper","Shadow Ravager","Forest Hexer",Material.DARK_OAK_LOG);case"FOREST"->a("Grove Guardian","Woodland Titan","Wild Reaper","Ancient Hunter",Material.OAK_LOG);case"MOUNTAIN"->a("Stone Colossus","Peak Warden","Cliff Reaper","Mountain King",Material.STONE);case"CAVE"->a("Deep Horror","Sculk Warden","Cavern Titan","Echo Reaper",Material.SCULK);default->a("Grassland Titan","Plains Warden","Wild King","Storm Reaper",Material.GRASS_BLOCK);};}
 private Theme t(String n,EntityType e,Material d){return new Theme(n,e,d,ChatColor.GOLD);}private Theme[] a(String a,String b,String c,String d,Material m){return new Theme[]{t(a,EntityType.RAVAGER,m),t(b,EntityType.WITHER_SKELETON,m),t(c,EntityType.IRON_GOLEM,m),t(d,EntityType.VINDICATOR,m)};}
 private void scan(){for(Player x:Bukkit.getOnlinePlayers()){String f=family(x.getLocation().getBlock().getBiome());if(f.equals("SWAMP"))continue;String id=x.getWorld().getUID()+":"+f+":"+Math.floorDiv(x.getLocation().getBlockX(),512)+":"+Math.floorDiv(x.getLocation().getBlockZ(),512);Set<UUID>s=active.computeIfAbsent(id,k->new HashSet<>());s.removeIf(u->{Entity e=Bukkit.getEntity(u);return e==null||!e.isValid();});if(s.size()>=4)continue;spawn(x.getLocation(),id,f,s.size(),s);}}
 private void spawn(Location near,String id,String f,int slot,Set<UUID>s){Theme[] ts=themes(f);Theme th=ts[Math.floorMod(id.hashCode()+slot,ts.length)];Location q=near.clone().add(12+(slot%2)*10,0,12+(slot/2)*10);q.setY(q.getWorld().getHighestBlockYAt(q.getBlockX(),q.getBlockZ())+1);try{LivingEntity z=(LivingEntity)q.getWorld().spawnEntity(q,th.type());var max=z.getAttribute(org.bukkit.attribute.Attribute.MAX_HEALTH);if(max==null){z.remove();return;}double hp=Math.min(1024,300+slot*125);max.setBaseValue(hp);z.setHealth(hp);z.setCustomName(th.color()+"ESN "+th.name());z.setCustomNameVisible(true);z.setGlowing(true);z.setPersistent(true);if(z instanceof Mob m)m.setRemoveWhenFarAway(false);z.addScoreboardTag("esnBiomeBoss");z.addScoreboardTag("esnBiome_"+f);s.add(z.getUniqueId());}catch(Exception ex){p.getLogger().warning("Biome boss spawn skipped safely: "+ex.getMessage());}}
 @EventHandler public void death(EntityDeathEvent e){if(!e.getEntity().getScoreboardTags().contains("esnBiomeBoss"))return;String f=e.getEntity().getScoreboardTags().stream().filter(x->x.startsWith("esnBiome_")).findFirst().orElse("esnBiome_PLAINS").substring(9);Theme th=themes(f)[0];ItemStack r=new ItemStack(th.drop(),1+ThreadLocalRandom.current().nextInt(3));ItemMeta m=r.getItemMeta();m.setDisplayName(ChatColor.GOLD+f+" Boss Relic");m.setLore(List.of(ChatColor.GRAY+"Regional boss crafting material",ChatColor.LIGHT_PURPLE+"Use it for ESN progression and collections."));m.getPersistentDataContainer().set(matKey,PersistentDataType.STRING,f);r.setItemMeta(m);e.getDrops().add(r);if(ThreadLocalRandom.current().nextDouble()<.25)e.getDrops().add(MegaCrates.key(ThreadLocalRandom.current().nextInt(MegaCrates.COUNT)));}
}