package com.esn.smp.gameplay;
import org.bukkit.*;import org.bukkit.boss.*;import org.bukkit.entity.*;import org.bukkit.event.*;import org.bukkit.event.entity.*;import org.bukkit.plugin.java.JavaPlugin;import java.util.*;
public final class BossHealthBars implements Listener{
 private final JavaPlugin p;private final Map<UUID,BossBar> bars=new HashMap<>();
 public BossHealthBars(JavaPlugin p){this.p=p;Bukkit.getScheduler().runTaskTimer(p,this::discover,20L,100L);Bukkit.getScheduler().runTaskTimer(p,this::tick,20L,20L);}
 private boolean boss(LivingEntity e){Set<String>t=e.getScoreboardTags();return t.contains("esnSwampBoss")||t.contains("esnBiomeBoss")||t.contains("esnWorldBoss");}
 private void discover(){for(World w:Bukkit.getWorlds())for(LivingEntity e:w.getLivingEntities())if(boss(e)&&e.isValid()&&!e.isDead())bars.computeIfAbsent(e.getUniqueId(),u->Bukkit.createBossBar(e.getCustomName()==null?"ESN BOSS":e.getCustomName(),e.getScoreboardTags().contains("esnWorldBoss")?BarColor.PURPLE:BarColor.RED,BarStyle.SEGMENTED_10));}
 private void tick(){Iterator<Map.Entry<UUID,BossBar>>it=bars.entrySet().iterator();while(it.hasNext()){Map.Entry<UUID,BossBar>en=it.next();Entity raw=Bukkit.getEntity(en.getKey());if(!(raw instanceof LivingEntity e)||!e.isValid()||e.isDead()||!boss(e)){en.getValue().removeAll();it.remove();continue;}BossBar b=en.getValue();double max=EndgameSystems.virtualMax(p,e),hp=EndgameSystems.virtualHealth(p,e);int stages=e.getScoreboardTags().contains("esnWorldBoss")?40:5;int stage=1;for(String t:e.getScoreboardTags())if(t.startsWith("esnStage_"))try{stage=Math.max(stage,Integer.parseInt(t.substring(9)));}catch(Exception ignored){}b.setTitle((e.getCustomName()==null?"ESN BOSS":e.getCustomName())+ChatColor.GOLD+" • Stage "+stage+"/"+stages);b.setProgress(Math.max(0,Math.min(1,hp/Math.max(1,max))));World w=e.getWorld();for(Player x:new ArrayList<>(b.getPlayers()))if(x.getWorld()!=w||x.getLocation().distanceSquared(e.getLocation())>22500)b.removePlayer(x);for(Player x:w.getPlayers())if(x.getLocation().distanceSquared(e.getLocation())<=22500&&!b.getPlayers().contains(x))b.addPlayer(x);}}
 @EventHandler public void death(EntityDeathEvent e){BossBar b=bars.remove(e.getEntity().getUniqueId());if(b!=null)b.removeAll();}
}
