package com.esn.smp.gameplay;
import org.bukkit.*;import org.bukkit.entity.Player;import org.bukkit.event.*;import org.bukkit.event.player.PlayerInteractEvent;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.ItemMeta;import org.bukkit.plugin.java.JavaPlugin;import java.util.*;
public final class CastleServices implements Listener{
 private final JavaPlugin p;private static final String TITLE=ChatColor.DARK_BLUE+"ESN Castle Services";
 public CastleServices(JavaPlugin p){this.p=p;}
 private ItemStack it(Material m,String n,String...l){ItemStack i=new ItemStack(m);ItemMeta x=i.getItemMeta();x.setDisplayName(n);x.setLore(Arrays.asList(l));i.setItemMeta(x);return i;}
 private Location origin(){String w=p.getConfig().getString("castle.world");if(w==null)return null;World world=Bukkit.getWorld(w);if(world==null)return null;return new Location(world,p.getConfig().getDouble("castle.x"),p.getConfig().getDouble("castle.y"),p.getConfig().getDouble("castle.z"));}
 private boolean inside(Location l){Location o=origin();return o!=null&&l.getWorld()==o.getWorld()&&Math.abs(l.getX()-o.getX())<=116&&Math.abs(l.getZ()-o.getZ())<=116&&l.getY()>=o.getY()-8&&l.getY()<=o.getY()+76;}
 private void open(Player x){Inventory v=Bukkit.createInventory(null,27,TITLE);v.setItem(10,it(Material.ANVIL,ChatColor.GOLD+"Castle Forge",ChatColor.GRAY+"Open blacksmith/forge services"));v.setItem(11,it(Material.IRON_BARS,ChatColor.RED+"Prison Control",ChatColor.GRAY+"Staff: manage castle prison"));v.setItem(12,it(Material.ENDER_PEARL,ChatColor.AQUA+"Castle Travel",ChatColor.GRAY+"Return to the castle gate"));v.setItem(13,it(Material.GOLD_BLOCK,ChatColor.YELLOW+"Royal Vault",ChatColor.GRAY+"View rewards and progression"));v.setItem(14,it(Material.WRITABLE_BOOK,ChatColor.GREEN+"Castle Quests",ChatColor.GRAY+"Open quests"));v.setItem(15,it(Material.BELL,ChatColor.LIGHT_PURPLE+"Castle Events",ChatColor.GRAY+"Open current events"));v.setItem(16,it(Material.SHIELD,ChatColor.BLUE+"Throne & Records",ChatColor.GRAY+"Open your ESN profile"));x.openInventory(v);}
 @EventHandler public void use(PlayerInteractEvent e){if(e.getClickedBlock()==null||!inside(e.getClickedBlock().getLocation()))return;Material m=e.getClickedBlock().getType();if(m==Material.SMITHING_TABLE||m==Material.ANVIL||m==Material.BEACON||m==Material.LECTERN||m==Material.BELL){e.setCancelled(true);open(e.getPlayer());}}
 @EventHandler public void click(org.bukkit.event.inventory.InventoryClickEvent e){if(!e.getView().getTitle().equals(TITLE))return;e.setCancelled(true);if(!(e.getWhoClicked() instanceof Player x))return;String cmd=switch(e.getRawSlot()){case 10->"forge";case 11->x.hasPermission("esnsmp.staff")?"jail":null;case 13->"rewards";case 14->"quests";case 15->"event";case 16->"profile";default->null;};if(e.getRawSlot()==12){Location o=origin();if(o!=null)x.teleport(o.clone().add(0,2,-100));x.closeInventory();return;}if(cmd!=null){x.closeInventory();x.performCommand(cmd);}}
}