package com.esn.smp.gameplay;
import org.bukkit.*;import org.bukkit.block.Block;import org.bukkit.command.*;import org.bukkit.entity.Player;import org.bukkit.event.*;import org.bukkit.event.block.*;import org.bukkit.event.inventory.InventoryOpenEvent;import org.bukkit.event.player.PlayerInteractEvent;import java.util.*;
public final class Claims implements Listener,CommandExecutor{
 private final Map<String,Claim> claims=new HashMap<>(); private final Map<UUID,Location> pos1=new HashMap<>(),pos2=new HashMap<>();
 record Claim(UUID owner,String world,int minX,int maxX,int minZ,int maxZ){boolean in(Location l){return l.getWorld()!=null&&l.getWorld().getName().equals(world)&&l.getBlockX()>=minX&&l.getBlockX()<=maxX&&l.getBlockZ()>=minZ&&l.getBlockZ()<=maxZ;}}
 public boolean onCommand(CommandSender s,Command c,String l,String[] a){if(!(s instanceof Player p))return true;if(a.length==0){p.sendMessage(ChatColor.GOLD+"/claim <pos1|pos2|create|remove>");return true;}switch(a[0].toLowerCase()){case"pos1"-> {pos1.put(p.getUniqueId(),p.getLocation());p.sendMessage(ChatColor.GREEN+"Claim corner 1 set.");}case"pos2"->{pos2.put(p.getUniqueId(),p.getLocation());p.sendMessage(ChatColor.GREEN+"Claim corner 2 set.");}case"create"->{Location x=pos1.get(p.getUniqueId()),z=pos2.get(p.getUniqueId());if(x==null||z==null||x.getWorld()!=z.getWorld()){p.sendMessage(ChatColor.RED+"Set both corners in the same world.");break;}int minX=Math.min(x.getBlockX(),z.getBlockX()),maxX=Math.max(x.getBlockX(),z.getBlockX()),minZ=Math.min(x.getBlockZ(),z.getBlockZ()),maxZ=Math.max(x.getBlockZ(),z.getBlockZ());if((maxX-minX+1L)*(maxZ-minZ+1L)>10000){p.sendMessage(ChatColor.RED+"Claim is too large (max 10,000 blocks).");break;}for(Claim q:claims.values())if(q.world.equals(x.getWorld().getName())&&minX<=q.maxX&&maxX>=q.minX&&minZ<=q.maxZ&&maxZ>=q.minZ){p.sendMessage(ChatColor.RED+"That overlaps another claim.");return true;}claims.put(p.getUniqueId().toString(),new Claim(p.getUniqueId(),x.getWorld().getName(),minX,maxX,minZ,maxZ));p.sendMessage(ChatColor.GREEN+"Base protected.");}case"remove"->{claims.remove(p.getUniqueId().toString());p.sendMessage(ChatColor.YELLOW+"Your claim was removed.");}}return true;}
 private boolean deny(Player p,Location l){for(Claim q:claims.values())if(q.in(l)&&!q.owner.equals(p.getUniqueId())&&!p.hasPermission("esnsmp.claim.bypass")){p.sendMessage(ChatColor.RED+"This base is protected.");return true;}return false;}
 @EventHandler public void br(BlockBreakEvent e){if(deny(e.getPlayer(),e.getBlock().getLocation()))e.setCancelled(true);}@EventHandler public void pl(BlockPlaceEvent e){if(deny(e.getPlayer(),e.getBlock().getLocation()))e.setCancelled(true);}
 @EventHandler public void in(PlayerInteractEvent e){Block b=e.getClickedBlock();if(b!=null&&deny(e.getPlayer(),b.getLocation()))e.setCancelled(true);}
 @EventHandler public void ex(BlockExplodeEvent e){e.blockList().removeIf(b->claims.values().stream().anyMatch(q->q.in(b.getLocation())));}
}
