package com.esn.smp.gameplay;
import org.bukkit.*;import org.bukkit.block.Block;import org.bukkit.command.*;import org.bukkit.configuration.file.YamlConfiguration;import org.bukkit.entity.Player;import org.bukkit.event.*;import org.bukkit.event.block.*;import org.bukkit.event.entity.EntityExplodeEvent;import org.bukkit.event.player.PlayerInteractEvent;import org.bukkit.plugin.java.JavaPlugin;import java.io.*;import java.util.*;
public final class Claims implements Listener,CommandExecutor{
 private final JavaPlugin plugin; private final File file; private final Map<UUID,Claim> claims=new HashMap<>(); private final Map<UUID,Location> pos1=new HashMap<>(),pos2=new HashMap<>();
 static final class Claim{final UUID owner;final String world;final int minX,maxX,minZ,maxZ;final Set<UUID> trusted=new HashSet<>();Claim(UUID o,String w,int a,int b,int c,int d){owner=o;world=w;minX=a;maxX=b;minZ=c;maxZ=d;}boolean in(Location l){return l.getWorld()!=null&&l.getWorld().getName().equals(world)&&l.getBlockX()>=minX&&l.getBlockX()<=maxX&&l.getBlockZ()>=minZ&&l.getBlockZ()<=maxZ;}}
 public Claims(JavaPlugin p){plugin=p;file=new File(p.getDataFolder(),"claims.yml");load();}
 private void load(){YamlConfiguration y=YamlConfiguration.loadConfiguration(file);for(String k:y.getKeys(false))try{UUID u=UUID.fromString(k);String w=y.getString(k+".world");Claim q=new Claim(u,w,y.getInt(k+".minX"),y.getInt(k+".maxX"),y.getInt(k+".minZ"),y.getInt(k+".maxZ"));for(String x:y.getStringList(k+".trusted"))q.trusted.add(UUID.fromString(x));claims.put(u,q);}catch(Exception e){plugin.getLogger().warning("Skipped invalid claim "+k);}}
 private void save(){YamlConfiguration y=new YamlConfiguration();for(var e:claims.entrySet()){String k=e.getKey().toString();Claim q=e.getValue();y.set(k+".world",q.world);y.set(k+".minX",q.minX);y.set(k+".maxX",q.maxX);y.set(k+".minZ",q.minZ);y.set(k+".maxZ",q.maxZ);y.set(k+".trusted",q.trusted.stream().map(UUID::toString).toList());}try{y.save(file);}catch(IOException e){plugin.getLogger().severe("Could not save claims: "+e.getMessage());}}
 public boolean onCommand(CommandSender s,Command c,String l,String[] a){if(!(s instanceof Player p))return true;if(a.length==0){p.sendMessage(ChatColor.GOLD+"/claim <pos1|pos2|create|remove|trust|untrust|info>");return true;}switch(a[0].toLowerCase()){case"pos1"->{pos1.put(p.getUniqueId(),p.getLocation());p.sendMessage(ChatColor.GREEN+"Claim corner 1 set.");}case"pos2"->{pos2.put(p.getUniqueId(),p.getLocation());p.sendMessage(ChatColor.GREEN+"Claim corner 2 set.");}case"create"->{Location x=pos1.get(p.getUniqueId()),z=pos2.get(p.getUniqueId());if(x==null||z==null||x.getWorld()!=z.getWorld()){p.sendMessage(ChatColor.RED+"Set both corners in the same world.");break;}int a1=Math.min(x.getBlockX(),z.getBlockX()),a2=Math.max(x.getBlockX(),z.getBlockX()),b1=Math.min(x.getBlockZ(),z.getBlockZ()),b2=Math.max(x.getBlockZ(),z.getBlockZ());if((a2-a1+1L)*(b2-b1+1L)>10000){p.sendMessage(ChatColor.RED+"Claim is too large (max 10,000 blocks).");break;}for(Claim q:claims.values())if(q.world.equals(x.getWorld().getName())&&a1<=q.maxX&&a2>=q.minX&&b1<=q.maxZ&&b2>=q.minZ){p.sendMessage(ChatColor.RED+"That overlaps another claim.");return true;}claims.put(p.getUniqueId(),new Claim(p.getUniqueId(),x.getWorld().getName(),a1,a2,b1,b2));save();p.sendMessage(ChatColor.GREEN+"Base protected and saved.");}case"remove"->{if(claims.remove(p.getUniqueId())!=null){save();p.sendMessage(ChatColor.YELLOW+"Your claim was removed.");}else p.sendMessage(ChatColor.RED+"You do not have a claim.");}case"trust","untrust"->{Claim q=claims.get(p.getUniqueId());if(q==null||a.length<2){p.sendMessage(ChatColor.RED+"Use /claim "+a[0]+" <player>");break;}Player t=Bukkit.getPlayerExact(a[1]);if(t==null){p.sendMessage(ChatColor.RED+"Player must be online.");break;}if(a[0].equalsIgnoreCase("trust"))q.trusted.add(t.getUniqueId());else q.trusted.remove(t.getUniqueId());save();p.sendMessage(ChatColor.GREEN+"Claim access updated for "+t.getName()+".");}case"info"->{Claim q=claims.values().stream().filter(v->v.in(p.getLocation())).findFirst().orElse(null);if(q==null)p.sendMessage(ChatColor.RED+"You are not inside a claim.");else p.sendMessage(ChatColor.GOLD+"Claim owner: "+Bukkit.getOfflinePlayer(q.owner).getName()+ChatColor.GRAY+" | Size: "+(q.maxX-q.minX+1)+"x"+(q.maxZ-q.minZ+1)+" | Trusted: "+q.trusted.size());}default->p.sendMessage(ChatColor.RED+"Unknown claim command.");}return true;}
 private boolean deny(Player p,Location l){for(Claim q:claims.values())if(q.in(l)&&!q.owner.equals(p.getUniqueId())&&!q.trusted.contains(p.getUniqueId())&&!p.hasPermission("esnsmp.claim.bypass")){p.sendMessage(ChatColor.RED+"This base is protected.");return true;}return false;}
 private boolean protectedAt(Location l){return claims.values().stream().anyMatch(q->q.in(l));}
 @EventHandler public void br(BlockBreakEvent e){if(deny(e.getPlayer(),e.getBlock().getLocation()))e.setCancelled(true);}@EventHandler public void pl(BlockPlaceEvent e){if(deny(e.getPlayer(),e.getBlock().getLocation()))e.setCancelled(true);}@EventHandler public void in(PlayerInteractEvent e){Block b=e.getClickedBlock();if(b!=null&&deny(e.getPlayer(),b.getLocation()))e.setCancelled(true);}@EventHandler public void bx(BlockExplodeEvent e){e.blockList().removeIf(b->protectedAt(b.getLocation()));}@EventHandler public void ex(EntityExplodeEvent e){e.blockList().removeIf(b->protectedAt(b.getLocation()));}
}