package com.esn.smp.gameplay;
import com.esn.smp.ESNSMPPlugin;
import com.esn.smp.data.ESNDataStore;
import org.bukkit.*;import org.bukkit.block.Block;import org.bukkit.command.*;import org.bukkit.configuration.file.YamlConfiguration;import org.bukkit.entity.Player;import org.bukkit.entity.Zombie;import org.bukkit.event.*;import org.bukkit.event.inventory.*;import org.bukkit.event.player.*;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.ItemMeta;import org.bukkit.persistence.*;import org.bukkit.plugin.java.JavaPlugin;
import java.io.*;import java.util.*;import java.util.concurrent.ThreadLocalRandom;

public final class CommunitySystems implements Listener,CommandExecutor{
 private final JavaPlugin p;private final ESNDataStore eco;private final File file;private final YamlConfiguration db;private final NamespacedKey stallOwnerKey,bunkerGuardKey;
 private final Map<UUID,String> openBackpacks=new HashMap<>();private final Map<UUID,Integer> openBackpackPages=new HashMap<>();private final Map<UUID,Long> draftPrice=new HashMap<>();private final Set<UUID> switchingPages=new HashSet<>();
 private static final int BACKPACK_SLOTS=248,BACKPACK_PAGE_DATA=45,BACKPACK_PAGES=6,STALL_COUNT=16;private static final String MANAGER=ChatColor.DARK_GREEN+"ESN Stall Manager",COLORS=ChatColor.DARK_GREEN+"Stall Colors",MARKET=ChatColor.GOLD+"ESN Marketplace";
 private static final String[] COLOR_NAMES={"WHITE","RED","BLUE","LIME","YELLOW","ORANGE","PURPLE","CYAN","PINK","BLACK"};
 private static final long[] COLOR_PRICES={0,2500,2500,3000,3000,3500,5000,5000,7500,10000};
 public CommunitySystems(JavaPlugin p,ESNDataStore eco){this.p=p;this.eco=eco;file=new File(p.getDataFolder(),"community-systems.yml");db=YamlConfiguration.loadConfiguration(file);stallOwnerKey=new NamespacedKey(p,"stall_owner");bunkerGuardKey=new NamespacedKey(p,"bunker_guard");Bukkit.getScheduler().runTaskTimer(p,this::rotateBlackMarket,20L,20L*60L);}
 private boolean save(){try{db.save(file);return true;}catch(Exception e){p.getLogger().severe("Community systems save failed: "+e.getMessage());return false;}}
 public boolean onCommand(CommandSender s,Command c,String l,String[] a){if(!(s instanceof Player x)){s.sendMessage("Players only.");return true;}return switch(c.getName()){case"blackmarket"->{blackMarket(x);yield true;}case"backpack"->{backpack(x);yield true;}case"stall"->{if(a.length>0&&a[0].equalsIgnoreCase("browse"))browse(x);else if(a.length>1&&a[0].equalsIgnoreCase("setprice"))legacyList(x,a[1]);else stallMenu(x);yield true;}case"bunker"->{bunker(x);yield true;}default->true;};}
 private String base(UUID id){return"stalls."+id;} private int stallOf(UUID id){return db.getInt(base(id)+".number",-1);} private UUID ownerOf(int n){String s=db.getString("stallSlots."+n);try{return s==null?null:UUID.fromString(s);}catch(Exception e){return null;}}
 private void rent(Player x){if(stallOf(x.getUniqueId())>=0){x.sendMessage(ChatColor.YELLOW+"You already rent stall #"+(stallOf(x.getUniqueId())+1)+".");return;}int free=-1;for(int i=0;i<STALL_COUNT;i++)if(ownerOf(i)==null){free=i;break;}if(free<0){x.sendMessage(ChatColor.RED+"All 16 physical stalls are currently rented.");return;}try{if(!eco.withdraw(x,500)){x.sendMessage(ChatColor.RED+"Renting a stall costs 500 ESN Coins.");return;}}catch(Exception e){x.sendMessage(ChatColor.RED+"Economy unavailable.");return;}String b=base(x.getUniqueId());db.set(b+".active",true);db.set(b+".number",free);db.set(b+".name",x.getName());db.set(b+".color","WHITE");db.set("stallSlots."+free,x.getUniqueId().toString());db.set(b+".colors.WHITE",true);save();paintStall(free,"WHITE");x.sendMessage(ChatColor.GREEN+"You rented physical stall #"+(free+1)+".");stallMenu(x);}
 private void closeStall(Player x){String b=base(x.getUniqueId());int n=stallOf(x.getUniqueId());if(n<0){x.sendMessage(ChatColor.RED+"You do not rent a stall.");return;}ItemStack old=db.getItemStack(b+".item");if(old!=null)x.getInventory().addItem(old).values().forEach(z->x.getWorld().dropItemNaturally(x.getLocation(),z));db.set("stallSlots."+n,null);db.set(b,null);save();paintStall(n,"WHITE");x.closeInventory();x.sendMessage(ChatColor.YELLOW+"Stall closed. Unsold stock was returned.");}
 private void stallMenu(Player x){Inventory v=Bukkit.createInventory(null,45,MANAGER);int n=stallOf(x.getUniqueId());if(n<0)v.setItem(13,item(Material.EMERALD_BLOCK,ChatColor.GREEN+"Rent a Physical Stall",ChatColor.GRAY+"Cost: 500 ESN Coins",ChatColor.GRAY+"Assigns the next available spawn stall"));else{String b=base(x.getUniqueId());long price=draftPrice.getOrDefault(x.getUniqueId(),Math.max(100,db.getLong(b+".price",100)));v.setItem(4,item(Material.OAK_SIGN,ChatColor.GOLD+"Your Stall #"+(n+1),ChatColor.GRAY+"Color: "+db.getString(b+".color","WHITE")));v.setItem(11,item(Material.CHEST,ChatColor.GREEN+"List Held Stack",ChatColor.GRAY+"Selected price: "+price+" coins",ChatColor.GRAY+"Hold the stack, then click here"));v.setItem(13,item(Material.GOLD_INGOT,ChatColor.YELLOW+"100 Coins"));v.setItem(14,item(Material.GOLD_INGOT,ChatColor.YELLOW+"500 Coins"));v.setItem(15,item(Material.GOLD_INGOT,ChatColor.YELLOW+"1,000 Coins"));v.setItem(16,item(Material.GOLD_INGOT,ChatColor.YELLOW+"5,000 Coins"));v.setItem(17,item(Material.GOLD_BLOCK,ChatColor.YELLOW+"10,000 Coins"));v.setItem(20,item(Material.WHITE_WOOL,ChatColor.AQUA+"Stall Colors",ChatColor.GRAY+"Unlock permanent canopy colors"));v.setItem(24,item(Material.BARRIER,ChatColor.RED+"Close Stall",ChatColor.GRAY+"Returns unsold stock"));ItemStack listed=db.getItemStack(b+".item");if(listed!=null){ItemStack show=listed.clone();ItemMeta m=show.getItemMeta();List<String> lore=m.hasLore()?new ArrayList<>(m.getLore()):new ArrayList<>();lore.add(ChatColor.YELLOW+"Currently listed: "+db.getLong(b+".price")+" coins");m.setLore(lore);show.setItemMeta(m);v.setItem(31,show);}}v.setItem(40,item(Material.BOOK,ChatColor.GOLD+"Browse Marketplace"));x.openInventory(v);}
 private void listHeld(Player x,long price){String b=base(x.getUniqueId());if(stallOf(x.getUniqueId())<0){x.sendMessage(ChatColor.RED+"Rent a stall first.");return;}if(db.getItemStack(b+".item")!=null){x.sendMessage(ChatColor.RED+"Your stall already has an item listed. Close the stall to return it first.");return;}ItemStack hand=x.getInventory().getItemInMainHand();if(hand.getType().isAir()){x.sendMessage(ChatColor.RED+"Hold the item stack you want to sell.");return;}if(price<1||price>1000000000L){x.sendMessage(ChatColor.RED+"Invalid price.");return;}db.set(b+".item",hand.clone());db.set(b+".price",price);x.getInventory().setItemInMainHand(null);save();x.sendMessage(ChatColor.GREEN+"Listed "+hand.getAmount()+"x "+hand.getType()+" for "+price+" coins.");stallMenu(x);}
 private void legacyList(Player x,String raw){try{listHeld(x,Long.parseLong(raw));}catch(Exception e){x.sendMessage(ChatColor.RED+"Invalid price.");}}
 private void colorMenu(Player x){Inventory v=Bukkit.createInventory(null,27,COLORS);String b=base(x.getUniqueId());for(int i=0;i<COLOR_NAMES.length;i++){String n=COLOR_NAMES[i];boolean unlocked=db.getBoolean(b+".colors."+n,n.equals("WHITE"));Material m=Material.valueOf(n+"_WOOL");v.setItem(i,item(m,(unlocked?ChatColor.GREEN:ChatColor.YELLOW)+n,unlocked?ChatColor.GRAY+"Unlocked - click to use":ChatColor.GRAY+"Unlock: "+COLOR_PRICES[i]+" coins"));}x.openInventory(v);}
 private void chooseColor(Player x,int slot){if(slot<0||slot>=COLOR_NAMES.length)return;String b=base(x.getUniqueId());if(stallOf(x.getUniqueId())<0)return;String n=COLOR_NAMES[slot];boolean unlocked=db.getBoolean(b+".colors."+n,n.equals("WHITE"));if(!unlocked){try{if(!eco.withdraw(x,COLOR_PRICES[slot])){x.sendMessage(ChatColor.RED+"You need "+COLOR_PRICES[slot]+" ESN Coins.");return;}}catch(Exception e){x.sendMessage(ChatColor.RED+"Economy unavailable.");return;}db.set(b+".colors."+n,true);x.sendMessage(ChatColor.GREEN+"Unlocked "+n+" stall color.");}db.set(b+".color",n);save();paintStall(stallOf(x.getUniqueId()),n);colorMenu(x);}
 private Location stallCenter(int n){Location s=((ESNSMPPlugin)p).getSpawnManager().getSpawn();if(s==null)return null;int row=n/4,col=n%4;return new Location(s.getWorld(),s.getBlockX()-178+col*32,s.getBlockY(),s.getBlockZ()+82+row*20);}
 private void paintStall(int n,String color){Location c=stallCenter(n);if(c==null||c.getWorld()==null)return;Material wool;try{wool=Material.valueOf(color+"_WOOL");}catch(Exception e){wool=Material.WHITE_WOOL;}for(int dx=-6;dx<=6;dx++)for(int dz=-5;dz<=5;dz++)c.getWorld().getBlockAt(c.getBlockX()+dx,c.getBlockY()+6,c.getBlockZ()+dz).setType(wool,false);}
 private int physicalStall(Block b){for(int i=0;i<STALL_COUNT;i++){Location c=stallCenter(i);if(c!=null&&c.getWorld()==b.getWorld()&&Math.abs(b.getX()-c.getBlockX())<=6&&Math.abs(b.getZ()-c.getBlockZ())<=5&&Math.abs(b.getY()-c.getBlockY())<=7)return i;}return-1;}
 private void browse(Player x){Inventory v=Bukkit.createInventory(null,54,MARKET);int slot=0;var sec=db.getConfigurationSection("stalls");if(sec!=null)for(String id:sec.getKeys(false)){ItemStack listed=db.getItemStack("stalls."+id+".item");if(listed==null)continue;ItemStack show=listed.clone();ItemMeta sm=show.getItemMeta();List<String> lore=sm.hasLore()?new ArrayList<>(sm.getLore()):new ArrayList<>();lore.add(ChatColor.YELLOW+"Price: "+db.getLong("stalls."+id+".price")+" coins");lore.add(ChatColor.GRAY+"Seller: "+db.getString("stalls."+id+".name","Unknown"));lore.add(ChatColor.GRAY+"Click to buy");sm.setLore(lore);sm.getPersistentDataContainer().set(stallOwnerKey,PersistentDataType.STRING,id);show.setItemMeta(sm);v.setItem(slot++,show);if(slot>=54)break;}x.openInventory(v);}
 private void buy(Player buyer,ItemStack clicked){ItemMeta meta=clicked.getItemMeta();String owner=meta==null?null:meta.getPersistentDataContainer().get(stallOwnerKey,PersistentDataType.STRING);if(owner==null)return;String b="stalls."+owner;ItemStack stock=db.getItemStack(b+".item");long price=db.getLong(b+".price");if(stock==null){buyer.sendMessage(ChatColor.RED+"That listing is no longer available.");browse(buyer);return;}if(owner.equals(buyer.getUniqueId().toString())){buyer.sendMessage(ChatColor.RED+"You cannot buy your own listing.");return;}try{if(!eco.withdraw(buyer,price)){buyer.sendMessage(ChatColor.RED+"Not enough coins.");return;}}catch(Exception e){buyer.sendMessage(ChatColor.RED+"Economy unavailable.");return;}db.set("pendingCoins."+owner,db.getLong("pendingCoins."+owner)+price);db.set(b+".item",null);if(!save()){try{eco.deposit(buyer,price);}catch(Exception ignored){}buyer.sendMessage(ChatColor.RED+"Purchase cancelled because marketplace storage could not save.");return;}buyer.getInventory().addItem(stock).values().forEach(z->buyer.getWorld().dropItemNaturally(buyer.getLocation(),z));buyer.sendMessage(ChatColor.GREEN+"Marketplace purchase complete.");browse(buyer);}
 private void settle(Player x){String k="pendingCoins."+x.getUniqueId();long amount=db.getLong(k);if(amount<=0)return;try{eco.deposit(x,amount);db.set(k,null);save();x.sendMessage(ChatColor.GREEN+"Your stalls earned "+amount+" ESN Coins while you were away.");}catch(Exception e){p.getLogger().warning("Could not settle stall earnings for "+x.getName());}}
 private void rotateBlackMarket(){long period=6L*60L*60L*1000L;if(System.currentTimeMillis()>=db.getLong("blackmarket.nextRotation",0)){db.set("blackmarket.rotation",ThreadLocalRandom.current().nextInt(3));db.set("blackmarket.nextRotation",System.currentTimeMillis()+period);save();}}
 private void blackMarket(Player x){rotateBlackMarket();Inventory v=Bukkit.createInventory(null,27,ChatColor.DARK_PURPLE+"ESN Black Market");v.setItem(11,item(Material.ENDER_PEARL,ChatColor.LIGHT_PURPLE+"Void Bundle",ChatColor.GRAY+"2,500 coins"));v.setItem(13,item(Material.TRIAL_KEY,ChatColor.GOLD+"Contraband Key",ChatColor.GRAY+"7,500 coins"));v.setItem(15,item(Material.NETHERITE_UPGRADE_SMITHING_TEMPLATE,ChatColor.RED+"Forbidden Template",ChatColor.GRAY+"25,000 coins"));x.openInventory(v);}
 private void backpack(Player x){openBackpackPage(x,"player-"+x.getUniqueId(),0);}
 private void openBackpackPage(Player x,String id,int page){page=Math.max(0,Math.min(BACKPACK_PAGES-1,page));Inventory v=Bukkit.createInventory(null,54,ChatColor.DARK_AQUA+"ESN Backpack "+(page+1)+"/"+BACKPACK_PAGES);List<?> list=db.getList("backpacks."+id);int base=page*BACKPACK_PAGE_DATA;for(int i=0;i<BACKPACK_PAGE_DATA;i++){int pos=base+i;if(pos<BACKPACK_SLOTS){if(list!=null&&pos<list.size()&&list.get(pos) instanceof ItemStack it)v.setItem(i,it);}else v.setItem(i,item(Material.BLACK_STAINED_GLASS_PANE,ChatColor.DARK_GRAY+"Locked",ChatColor.GRAY+"248-slot capacity"));}for(int i=45;i<54;i++)v.setItem(i,item(Material.GRAY_STAINED_GLASS_PANE," ",ChatColor.GRAY+"Backpack controls"));if(page>0)v.setItem(45,item(Material.ARROW,ChatColor.YELLOW+"Previous Page"));if(page<BACKPACK_PAGES-1)v.setItem(53,item(Material.ARROW,ChatColor.YELLOW+"Next Page"));v.setItem(49,item(Material.BUNDLE,ChatColor.GOLD+"Persistent Backpack",ChatColor.GRAY+"248 storage slots",ChatColor.GRAY+"Saved automatically"));openBackpacks.put(x.getUniqueId(),id);openBackpackPages.put(x.getUniqueId(),page);switchingPages.add(x.getUniqueId());x.openInventory(v);Bukkit.getScheduler().runTask(p,()->switchingPages.remove(x.getUniqueId()));}
 private void saveBackpackPage(Player x,Inventory inv){String id=openBackpacks.get(x.getUniqueId());Integer page=openBackpackPages.get(x.getUniqueId());if(id==null||page==null)return;List<ItemStack> all=new ArrayList<>(Collections.nCopies(BACKPACK_SLOTS,null));List<?> old=db.getList("backpacks."+id);if(old!=null)for(int i=0;i<Math.min(BACKPACK_SLOTS,old.size());i++)if(old.get(i) instanceof ItemStack it)all.set(i,it);int base=page*BACKPACK_PAGE_DATA;for(int i=0;i<BACKPACK_PAGE_DATA&&base+i<BACKPACK_SLOTS;i++)all.set(base+i,inv.getItem(i));db.set("backpacks."+id,all);save();}
 private boolean invalidBackpackSlot(Player x,int raw){int page=openBackpackPages.getOrDefault(x.getUniqueId(),0);return raw>=45||(raw>=0&&page*BACKPACK_PAGE_DATA+raw>=BACKPACK_SLOTS);}
 private void bunker(Player x){if(!x.hasPermission("esnsmp.admin")){x.sendMessage(ChatColor.RED+"Admin only.");return;}Location c=x.getLocation().getBlock().getLocation().add(0,-8,0);World w=c.getWorld();for(int dx=-7;dx<=7;dx++)for(int dy=0;dy<=6;dy++)for(int dz=-10;dz<=10;dz++){boolean shell=Math.abs(dx)==7||dy==0||dy==6||Math.abs(dz)==10;w.getBlockAt(c.clone().add(dx,dy,dz)).setType(shell?Material.DEEPSLATE_BRICKS:Material.AIR,false);}for(int z=-8;z<=8;z+=4){w.getBlockAt(c.clone().add(-5,1,z)).setType(Material.REDSTONE_LAMP,false);w.getBlockAt(c.clone().add(5,1,z)).setType(Material.REDSTONE_LAMP,false);}w.getBlockAt(c.clone().add(0,1,9)).setType(Material.IRON_DOOR,false);w.getBlockAt(c.clone().add(-4,1,-7)).setType(Material.BARREL,false);w.getBlockAt(c.clone().add(4,1,-7)).setType(Material.BARREL,false);for(int gx:new int[]{-4,0,4}){Zombie g=w.spawn(c.clone().add(gx,1,-4),Zombie.class);g.setCustomName(ChatColor.DARK_RED+"Bunker Guard");g.setCustomNameVisible(true);g.getPersistentDataContainer().set(bunkerGuardKey,PersistentDataType.BYTE,(byte)1);g.getEquipment().setHelmet(new ItemStack(Material.IRON_HELMET));g.getEquipment().setItemInMainHand(new ItemStack(Material.IRON_SWORD));}x.sendMessage(ChatColor.GREEN+"Secret bunker generated beneath you at Y "+c.getBlockY()+".");}
 private ItemStack item(Material mat,String name,String... lore){ItemStack i=new ItemStack(mat);ItemMeta m=i.getItemMeta();m.setDisplayName(name);m.setLore(List.of(lore));i.setItemMeta(m);return i;}
 @EventHandler public void interact(PlayerInteractEvent e){if(e.getClickedBlock()==null)return;int n=physicalStall(e.getClickedBlock());if(n<0)return;e.setCancelled(true);UUID owner=ownerOf(n);if(owner==null){stallMenu(e.getPlayer());return;}if(owner.equals(e.getPlayer().getUniqueId()))stallMenu(e.getPlayer());else browse(e.getPlayer());}
 @EventHandler public void join(PlayerJoinEvent e){settle(e.getPlayer());}
 @EventHandler public void click(InventoryClickEvent e){if(!(e.getWhoClicked() instanceof Player x))return;String t=e.getView().getTitle();
  if(t.startsWith(ChatColor.DARK_AQUA+"ESN Backpack ")){if(e.getRawSlot()<54&&invalidBackpackSlot(x,e.getRawSlot())){e.setCancelled(true);if(e.getRawSlot()==45&&openBackpackPages.getOrDefault(x.getUniqueId(),0)>0){saveBackpackPage(x,e.getInventory());openBackpackPage(x,openBackpacks.get(x.getUniqueId()),openBackpackPages.get(x.getUniqueId())-1);}else if(e.getRawSlot()==53&&openBackpackPages.getOrDefault(x.getUniqueId(),0)<BACKPACK_PAGES-1){saveBackpackPage(x,e.getInventory());openBackpackPage(x,openBackpacks.get(x.getUniqueId()),openBackpackPages.get(x.getUniqueId())+1);}}else if(e.isShiftClick()&&e.getRawSlot()>=54){e.setCancelled(true);x.sendMessage(ChatColor.GRAY+"Place items into backpack slots normally.");}return;}
  if(t.equals(MANAGER)){e.setCancelled(true);int s=e.getRawSlot();if(s==13&&stallOf(x.getUniqueId())<0)rent(x);else if(s==11&&stallOf(x.getUniqueId())>=0)listHeld(x,draftPrice.getOrDefault(x.getUniqueId(),100L));else if(s>=13&&s<=17&&stallOf(x.getUniqueId())>=0){long[] ps={100,500,1000,5000,10000};draftPrice.put(x.getUniqueId(),ps[s-13]);stallMenu(x);}else if(s==20)colorMenu(x);else if(s==24)closeStall(x);else if(s==40)browse(x);return;}
  if(t.equals(COLORS)){e.setCancelled(true);chooseColor(x,e.getRawSlot());return;}
  if(t.equals(MARKET)){e.setCancelled(true);if(e.getCurrentItem()!=null)buy(x,e.getCurrentItem());return;}
  if(t.equals(ChatColor.DARK_PURPLE+"ESN Black Market")){e.setCancelled(true);if(e.getCurrentItem()==null)return;int s=e.getRawSlot();long price=s==11?2500:s==13?7500:s==15?25000:0;if(price==0)return;try{if(!eco.withdraw(x,price)){x.sendMessage(ChatColor.RED+"Not enough coins.");return;}}catch(Exception ex){x.sendMessage(ChatColor.RED+"Economy unavailable.");return;}ItemStack reward=s==11?new ItemStack(Material.ENDER_PEARL,8):s==13?new ItemStack(Material.TRIAL_KEY):new ItemStack(Material.NETHERITE_UPGRADE_SMITHING_TEMPLATE);x.getInventory().addItem(reward).values().forEach(z->x.getWorld().dropItemNaturally(x.getLocation(),z));x.sendMessage(ChatColor.GREEN+"Black Market purchase complete.");}}
 @EventHandler public void drag(InventoryDragEvent e){if(!e.getView().getTitle().startsWith(ChatColor.DARK_AQUA+"ESN Backpack ")||!(e.getWhoClicked() instanceof Player x))return;for(int raw:e.getRawSlots())if(raw<54&&invalidBackpackSlot(x,raw)){e.setCancelled(true);return;}}
 @EventHandler public void quit(PlayerQuitEvent e){Player x=e.getPlayer();if(openBackpacks.containsKey(x.getUniqueId()))saveBackpackPage(x,x.getOpenInventory().getTopInventory());openBackpacks.remove(x.getUniqueId());openBackpackPages.remove(x.getUniqueId());switchingPages.remove(x.getUniqueId());}
 @EventHandler public void close(InventoryCloseEvent e){if(!e.getView().getTitle().startsWith(ChatColor.DARK_AQUA+"ESN Backpack "))return;Player x=(Player)e.getPlayer();saveBackpackPage(x,e.getInventory());if(!switchingPages.contains(x.getUniqueId())){openBackpacks.remove(x.getUniqueId());openBackpackPages.remove(x.getUniqueId());}}
}