package com.esn.smp.gameplay;
import org.bukkit.*;import org.bukkit.attribute.Attribute;import org.bukkit.entity.*;import org.bukkit.event.*;import org.bukkit.event.entity.*;import org.bukkit.event.player.*;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.ItemMeta;import org.bukkit.persistence.*;import org.bukkit.plugin.java.JavaPlugin;import java.util.*;import java.util.concurrent.*;
public final class EndgameSystems implements Listener{
 private final JavaPlugin p;private final NamespacedKey artifact,pet;private final Map<UUID,Integer> bossKills=new HashMap<>(),pity=new HashMap<>();private final Set<UUID> participants=ConcurrentHashMap.newKeySet();
 public EndgameSystems(JavaPlugin p){this.p=p;artifact=new NamespacedKey(p,"artifact");pet=new NamespacedKey(p,"boss_pet");Bukkit.getScheduler().runTaskTimer(p,this::worldPulse,1200L,72000L);Bukkit.getScheduler().runTaskTimer(p,this::diagnostics,100L,12000L);}
 private void diagnostics(){if(MegaCrates.COUNT!=100||MegaCrates.ITEMS<10)p.getLogger().severe("DIAGNOSTIC: Realm crate definition mismatch.");else p.getLogger().info("ESN diagnostics OK: 100 Realm crates, biome/endgame systems active.");}
 @EventHandler public void hit(EntityDamageByEntityEvent e){if(!(e.getEntity() instanceof LivingEntity z)||(!z.getScoreboardTags().contains("esnBiomeBoss")&&!z.getScoreboardTags().contains("esnWorldBoss")&&!z.getScoreboardTags().contains("esnSwampBoss")))return;Player x=e.getDamager() instanceof Player q?q:e.getDamager() instanceof Projectile pr&&pr.getShooter() instanceof Player q?q:null;if(x!=null){participants.add(x.getUniqueId());int nearby=(int)z.getWorld().getPlayers().stream().filter(a->a.getLocation().distanceSquared(z.getLocation())<2500).count();var max=z.getAttribute(Attribute.MAX_HEALTH);if(max!=null&&!z.getScoreboardTags().contains("esnScaled")){double hp=Math.min(1024,max.getBaseValue()*(1+Math.max(0,nearby-1)*.18));max.setBaseValue(hp);z.setHealth(hp);z.addScoreboardTag("esnScaled");}}}
 @EventHandler public void bossDeath(EntityDeathEvent e){LivingEntity z=e.getEntity();if(!z.getScoreboardTags().contains("esnBiomeBoss")&&!z.getScoreboardTags().contains("esnWorldBoss")&&!z.getScoreboardTags().contains("esnSwampBoss"))return;Player k=z.getKiller();if(k==null)return;int n=bossKills.merge(k.getUniqueId(),1,Integer::sum),miss=pity.merge(k.getUniqueId(),1,Integer::sum);if(n%10==0)k.sendMessage(ChatColor.GOLD+"Boss Mastery "+n+" — new milestone reached!");double rare=Math.min(.30,.03+miss*.005);if(ThreadLocalRandom.current().nextDouble()<rare){ItemStack a=artifact();e.getDrops().add(a);pity.put(k.getUniqueId(),0);Bukkit.broadcastMessage(ChatColor.LIGHT_PURPLE+k.getName()+" discovered a MYTHIC BOSS ARTIFACT!");}if(ThreadLocalRandom.current().nextDouble()<.01)e.getDrops().add(pet());for(UUID id:new HashSet<>(participants)){Player x=Bukkit.getPlayer(id);if(x!=null&&x.getWorld()==z.getWorld()&&x.getLocation().distanceSquared(z.getLocation())<6400){x.giveExp(75);x.sendActionBar(ChatColor.GOLD+"Boss participation: +75 XP");}}participants.clear();}
 private ItemStack artifact(){ItemStack i=new ItemStack(Material.NETHER_STAR);ItemMeta m=i.getItemMeta();m.setDisplayName(ChatColor.LIGHT_PURPLE+"Mythic Boss Artifact");m.setLore(List.of(ChatColor.GRAY+"Rare ability relic",ChatColor.GOLD+"Right-click: temporary Strength + Resistance"));m.getPersistentDataContainer().set(artifact,PersistentDataType.BYTE,(byte)1);i.setItemMeta(m);return i;}
 private ItemStack pet(){ItemStack i=new ItemStack(Material.ALLAY_SPAWN_EGG);ItemMeta m=i.getItemMeta();m.setDisplayName(ChatColor.AQUA+"Boss Spirit Pet");m.setLore(List.of(ChatColor.GRAY+"Ultra-rare boss collectible"));m.getPersistentDataContainer().set(pet,PersistentDataType.BYTE,(byte)1);i.setItemMeta(m);return i;}
 @EventHandler public void use(PlayerInteractEvent e){ItemStack i=e.getItem();if(i==null||!i.hasItemMeta()||!i.getItemMeta().getPersistentDataContainer().has(artifact,PersistentDataType.BYTE))return;Player x=e.getPlayer();x.addPotionEffect(new org.bukkit.potion.PotionEffect(org.bukkit.potion.PotionEffectType.STRENGTH,200,2));x.addPotionEffect(new org.bukkit.potion.PotionEffect(org.bukkit.potion.PotionEffectType.RESISTANCE,200,1));x.sendActionBar(ChatColor.LIGHT_PURPLE+"Artifact power awakened");}
 private void worldPulse(){if(Bukkit.getOnlinePlayers().isEmpty())return;int r=ThreadLocalRandom.current().nextInt(4);String[] msg={"A Blood Moon surge empowers hostile creatures!","A meteor signal has appeared somewhere in the overworld!","Realm instability is strengthening regional bosses!","Treasure hunters report ancient caches awakening!"};Bukkit.broadcastMessage(ChatColor.DARK_RED+"[WORLD EVENT] "+ChatColor.GOLD+msg[r]);for(World w:Bukkit.getWorlds())if(w.getEnvironment()==World.Environment.NORMAL&&r==0)for(LivingEntity e:w.getLivingEntities())if(e instanceof Monster){e.addPotionEffect(new org.bukkit.potion.PotionEffect(org.bukkit.potion.PotionEffectType.STRENGTH,2400,1));e.addPotionEffect(new org.bukkit.potion.PotionEffect(org.bukkit.potion.PotionEffectType.SPEED,2400,0));}}
}