package com.esn.smp.gameplay;
import com.esn.smp.data.ESNDataStore;import org.bukkit.*;import org.bukkit.attribute.Attribute;import org.bukkit.command.*;import org.bukkit.entity.*;import org.bukkit.event.*;import org.bukkit.event.entity.*;import org.bukkit.event.player.*;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.ItemMeta;import org.bukkit.persistence.*;import org.bukkit.plugin.java.JavaPlugin;import java.io.*;import java.sql.*;import java.util.*;import java.util.concurrent.ThreadLocalRandom;
public final class ESN20Core implements Listener,CommandExecutor,AutoCloseable{
 private final JavaPlugin p;private final ESNDataStore eco;private final NamespacedKey relic;private Connection db;private final Map<UUID,Map<UUID,Double>> damage=new HashMap<>();
 public ESN20Core(JavaPlugin p,ESNDataStore eco)throws Exception{this.p=p;this.eco=eco;relic=new NamespacedKey(p,"boss_relic");db=DriverManager.getConnection("jdbc:sqlite:"+new File(p.getDataFolder(),"esn20.db"));try(Statement s=db.createStatement()){s.execute("CREATE TABLE IF NOT EXISTS boss_progress(uuid TEXT PRIMARY KEY,kills INTEGER DEFAULT 0,tokens INTEGER DEFAULT 0,crafts INTEGER DEFAULT 0)");}Bukkit.getScheduler().runTaskTimer(p,this::pulse,100L,100L);Bukkit.getScheduler().runTaskTimer(p,this::cleanupMemory,1200L,1200L);}
 private void ensure(Player x)throws Exception{try(PreparedStatement q=db.prepareStatement("INSERT OR IGNORE INTO boss_progress(uuid) VALUES(?)")){q.setString(1,x.getUniqueId().toString());q.executeUpdate();}}
 private int get(Player x,String c)throws Exception{ensure(x);try(PreparedStatement q=db.prepareStatement("SELECT "+c+" FROM boss_progress WHERE uuid=?")){q.setString(1,x.getUniqueId().toString());try(ResultSet r=q.executeQuery()){return r.next()?r.getInt(1):0;}}}
 private void add(Player x,String c,int n){try{ensure(x);try(PreparedStatement q=db.prepareStatement("UPDATE boss_progress SET "+c+"="+c+"+? WHERE uuid=?")){q.setInt(1,n);q.setString(2,x.getUniqueId().toString());q.executeUpdate();}}catch(Exception ex){p.getLogger().warning("ESN 2.0 progress: "+ex.getMessage());}}
 public boolean onCommand(CommandSender s,Command c,String l,String[] a){if(!(s instanceof Player x))return true;try{switch(c.getName()){case"forge"->forge(x,a);case"bossdrops"->drops(x);case"contracts"->contracts(x);case"relics"->relics(x);case"challenges"->challenges(x);case"rewards"->rewards(x);}}catch(Exception e){x.sendMessage(ChatColor.RED+"ESN 2.0 system temporarily unavailable.");}return true;}
 private void drops(Player x)throws Exception{x.sendMessage(ChatColor.GOLD+"BOSS DROP USES");x.sendMessage(ChatColor.LIGHT_PURPLE+"Void Shards "+ChatColor.GRAY+"+ "+ChatColor.DARK_RED+"Titan Fragments "+ChatColor.GRAY+"forge boss gear.");x.sendMessage(ChatColor.AQUA+"Celestial Crystals "+ChatColor.GRAY+"and "+ChatColor.LIGHT_PURPLE+"Cosmic Cores "+ChatColor.GRAY+"forge endgame relics.");x.sendMessage(ChatColor.YELLOW+"Use /forge list for recipes. Boss kills: "+get(x,"kills")+" | Crafts: "+get(x,"crafts"));}
 private void forge(Player x,String[] a)throws Exception{if(a.length==0||a[0].equalsIgnoreCase("list")){x.sendMessage(ChatColor.GOLD+"ESN RELIC FORGE");x.sendMessage(ChatColor.GRAY+"/forge voidheart "+ChatColor.WHITE+"4 Void Shards + 2 Titan Fragments");x.sendMessage(ChatColor.GRAY+"/forge celestial "+ChatColor.WHITE+"3 Celestial Crystals + 1 Cosmic Core");x.sendMessage(ChatColor.GRAY+"/forge worldbreaker "+ChatColor.WHITE+"6 Titan Fragments + 2 Cosmic Cores");x.sendMessage(ChatColor.GRAY+"/forge cache "+ChatColor.WHITE+"2 Void Shards + 1 Celestial Crystal");return;}String id=a[0].toLowerCase();ItemStack out;Map<String,Integer> need=new LinkedHashMap<>();switch(id){case"voidheart"->{need.put("Void Shard",4);need.put("Titan Fragment",2);out=mark(CustomItems.abyssChest(),"voidheart");}case"celestial"->{need.put("Celestial Crystal",3);need.put("Cosmic Core",1);out=mark(CustomItems.cosmicBlade(),"celestial");}case"worldbreaker"->{need.put("Titan Fragment",6);need.put("Cosmic Core",2);out=mark(CustomItems.dragonBlade(),"worldbreaker");}case"cache"->{need.put("Void Shard",2);need.put("Celestial Crystal",1);out=mark(LootDrops.abyssKey(),"cache");out.setAmount(2);}default->{x.sendMessage(ChatColor.RED+"Unknown recipe. Use /forge list.");return;}}for(var n:need.entrySet())if(count(x,n.getKey())<n.getValue()){x.sendMessage(ChatColor.RED+"Missing "+n.getValue()+"x "+n.getKey()+".");return;}for(var n:need.entrySet())take(x,n.getKey(),n.getValue());give(x,out);add(x,"crafts",1);x.sendMessage(ChatColor.GREEN+"Forged "+out.getItemMeta().getDisplayName()+ChatColor.GREEN+"!");}
 private ItemStack mark(ItemStack i,String id){ItemMeta m=i.getItemMeta();m.getPersistentDataContainer().set(relic,PersistentDataType.STRING,id);List<String> lore=m.hasLore()?new ArrayList<>(m.getLore()):new ArrayList<>();lore.add(ChatColor.GOLD+"Forged Boss Relic");m.setLore(lore);i.setItemMeta(m);return i;}
 private int count(Player x,String n){int z=0;for(ItemStack i:x.getInventory().getContents())if(named(i,n))z+=i.getAmount();return z;}
 private boolean named(ItemStack i,String n){return i!=null&&i.hasItemMeta()&&i.getItemMeta().hasDisplayName()&&ChatColor.stripColor(i.getItemMeta().getDisplayName()).equals(n);}
 private void take(Player x,String n,int amount){for(int s=0;s<x.getInventory().getSize()&&amount>0;s++){ItemStack i=x.getInventory().getItem(s);if(!named(i,n))continue;int q=Math.min(amount,i.getAmount());i.setAmount(i.getAmount()-q);amount-=q;if(i.getAmount()<=0)x.getInventory().setItem(s,null);}}
 private void give(Player x,ItemStack i){Map<Integer,ItemStack> left=x.getInventory().addItem(i);left.values().forEach(z->x.getWorld().dropItemNaturally(x.getLocation(),z));}
 private void contracts(Player x)throws Exception{x.sendMessage(ChatColor.GOLD+"WEEKLY BOSS CONTRACTS");x.sendMessage(ChatColor.GRAY+"Boss Hunter: "+get(x,"kills")+"/5 boss kills");x.sendMessage(ChatColor.GRAY+"Relic Smith: "+get(x,"crafts")+"/3 forged relics");x.sendMessage(ChatColor.YELLOW+"Complete activities to build your permanent ESN boss record.");}
 private void relics(Player x){x.sendMessage(ChatColor.LIGHT_PURPLE+"Relics are endgame items forged from boss drops. "+ChatColor.GRAY+"Use /forge list.");}
 private void challenges(Player x)throws Exception{x.sendMessage(ChatColor.AQUA+"ESN Challenges: "+ChatColor.WHITE+"Boss kills "+get(x,"kills")+" | Relics forged "+get(x,"crafts"));x.sendMessage(ChatColor.GRAY+"World bosses also reward all qualifying participants, not only the final hit.");}
 private void rewards(Player x)throws Exception{x.sendMessage(ChatColor.GOLD+"Reward Road: "+ChatColor.WHITE+get(x,"kills")+" boss kills. Milestones: 5 / 15 / 30 / 50.");}
 @EventHandler public void hit(EntityDamageByEntityEvent e){if(!(e.getEntity() instanceof LivingEntity b)||(!b.getScoreboardTags().contains("esnWorldBoss")&&!b.getScoreboardTags().contains("esnSwampBoss")))return;Player x=null;if(e.getDamager() instanceof Player q)x=q;else if(e.getDamager() instanceof Projectile pr&&pr.getShooter() instanceof Player q)x=q;if(x!=null)damage.computeIfAbsent(b.getUniqueId(),k->new HashMap<>()).merge(x.getUniqueId(),Math.max(0,e.getFinalDamage()),Double::sum);}
 @EventHandler(priority=EventPriority.MONITOR) public void bossDeath(EntityDeathEvent e){if(!e.getEntity().getScoreboardTags().contains("esnWorldBoss")&&!e.getEntity().getScoreboardTags().contains("esnSwampBoss"))return;Map<UUID,Double> d=damage.remove(e.getEntity().getUniqueId());if(d==null||d.isEmpty())return;double total=d.values().stream().mapToDouble(Double::doubleValue).sum();boolean world=e.getEntity().getScoreboardTags().contains("esnWorldBoss");for(var z:d.entrySet()){Player x=Bukkit.getPlayer(z.getKey());if(x==null||z.getValue()<Math.max(10,total*.05))continue;add(x,"kills",1);try{eco.deposit(x,world?5000:2000);}catch(Exception ignored){}ItemStack drop=world?(ThreadLocalRandom.current().nextBoolean()?CustomItems.cosmicCore():CustomItems.celestialCrystal()):(ThreadLocalRandom.current().nextBoolean()?CustomItems.voidShard():CustomItems.titanFragment());give(x,drop);x.sendMessage(ChatColor.GOLD+"Participation reward: "+(world?"5,000":"2,000")+" Coins + boss material!");}}
 @EventHandler public void use(PlayerInteractEvent e){ItemStack i=e.getItem();if(i==null||!i.hasItemMeta())return;String id=i.getItemMeta().getPersistentDataContainer().get(relic,PersistentDataType.STRING);if(id==null)return;Player x=e.getPlayer();if(id.equals("voidheart")){x.addPotionEffect(new org.bukkit.potion.PotionEffect(org.bukkit.potion.PotionEffectType.RESISTANCE,120,1));x.getWorld().spawnParticle(Particle.PORTAL,x.getLocation().add(0,1,0),40,1,1,1,.05);}else if(id.equals("celestial")){x.addPotionEffect(new org.bukkit.potion.PotionEffect(org.bukkit.potion.PotionEffectType.SPEED,120,2));x.addPotionEffect(new org.bukkit.potion.PotionEffect(org.bukkit.potion.PotionEffectType.STRENGTH,80,1));}else if(id.equals("worldbreaker")){for(Entity z:x.getNearbyEntities(5,3,5))if(z instanceof Monster m)m.damage(12,x);x.getWorld().spawnParticle(Particle.EXPLOSION,x.getLocation(),3);}else return;x.sendActionBar(ChatColor.GOLD+"Relic power activated");}
 private void pulse(){for(Player x:Bukkit.getOnlinePlayers()){ItemStack i=x.getInventory().getItemInMainHand();if(i==null||!i.hasItemMeta())continue;String id=i.getItemMeta().getPersistentDataContainer().get(relic,PersistentDataType.STRING);if("voidheart".equals(id))x.addPotionEffect(new org.bukkit.potion.PotionEffect(org.bukkit.potion.PotionEffectType.RESISTANCE,120,0));}}
 private void cleanupMemory(){damage.entrySet().removeIf(e->{Entity z=Bukkit.getEntity(e.getKey());return z==null||!z.isValid()||z.isDead();});for(Map<UUID,Double> m:damage.values())m.keySet().removeIf(id->Bukkit.getPlayer(id)==null);}
 public void close()throws Exception{damage.clear();if(db!=null)db.close();}
}