package com.esn.smp.gameplay;
import com.esn.smp.data.ESNDataStore;import org.bukkit.*;import org.bukkit.scoreboard.Team;import org.bukkit.command.*;import org.bukkit.entity.*;import org.bukkit.event.*;import org.bukkit.event.block.*;import org.bukkit.event.entity.*;import org.bukkit.event.player.*;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.ItemMeta;import org.bukkit.persistence.*;import org.bukkit.plugin.java.JavaPlugin;import java.io.*;import java.sql.*;import java.util.*;import java.util.concurrent.ThreadLocalRandom;
public final class ESN20Expansion implements Listener,CommandExecutor,AutoCloseable{
 private static final String ACH_MENU=ChatColor.DARK_AQUA+"ESN Achievement Book";
 private final JavaPlugin p;private final ESNDataStore eco;private Connection db;private final NamespacedKey id;private final Map<UUID,Long> combat=new HashMap<>();private final Map<UUID,UUID> invites=new HashMap<>(),leaders=new HashMap<>();private String activeEvent="NONE";private long eventEnd=0;
 public ESN20Expansion(JavaPlugin p,ESNDataStore e)throws Exception{this.p=p;eco=e;id=new NamespacedKey(p,"esn_id");db=DriverManager.getConnection("jdbc:sqlite:"+new File(p.getDataFolder(),"esn20-expansion.db"));try(Statement s=db.createStatement()){s.execute("CREATE TABLE IF NOT EXISTS progress(uuid TEXT PRIMARY KEY,seasonxp INTEGER DEFAULT 0,weekly INTEGER DEFAULT 0,streak INTEGER DEFAULT 0,lastjoin INTEGER DEFAULT 0,reward INTEGER DEFAULT 0,title TEXT DEFAULT '',bosskills INTEGER DEFAULT 0,dungeons INTEGER DEFAULT 0,raids INTEGER DEFAULT 0)");s.execute("CREATE TABLE IF NOT EXISTS achievements(uuid TEXT,key TEXT,PRIMARY KEY(uuid,key))");s.execute("CREATE TABLE IF NOT EXISTS achievement_claims(uuid TEXT,key TEXT,PRIMARY KEY(uuid,key))");s.execute("CREATE TABLE IF NOT EXISTS bestiary(uuid TEXT,mob TEXT,kills INTEGER DEFAULT 0,PRIMARY KEY(uuid,mob))");s.execute("CREATE TABLE IF NOT EXISTS graves(uuid TEXT PRIMARY KEY,world TEXT,x INTEGER,y INTEGER,z INTEGER,expires INTEGER)");}Bukkit.getScheduler().runTaskTimer(p,this::eventPulse,72000L,72000L);Bukkit.getScheduler().runTaskTimer(p,()->{for(Player online:Bukkit.getOnlinePlayers())refreshPlayerTag(online);},60L,40L);}
 private void ensure(Player x)throws Exception{try(PreparedStatement q=db.prepareStatement("INSERT OR IGNORE INTO progress(uuid) VALUES(?)")){q.setString(1,x.getUniqueId().toString());q.executeUpdate();}}
 private int get(Player x,String c)throws Exception{ensure(x);try(PreparedStatement q=db.prepareStatement("SELECT "+c+" FROM progress WHERE uuid=?")){q.setString(1,x.getUniqueId().toString());try(ResultSet r=q.executeQuery()){return r.next()?r.getInt(1):0;}}}
 private void add(Player x,String c,int n){try{ensure(x);try(PreparedStatement q=db.prepareStatement("UPDATE progress SET "+c+"="+c+"+? WHERE uuid=?")){q.setInt(1,n);q.setString(2,x.getUniqueId().toString());q.executeUpdate();}}catch(Exception ignored){}}
 public boolean onCommand(CommandSender s,Command c,String l,String[] a){if(!(s instanceof Player x))return true;try{switch(c.getName()){case"season2"->season(x);case"milestones"->milestones(x,a);case"bestiary2"->bestiary(x);case"achievements2"->achievements(x);case"title"->title(x,a);case"party2"->party(x,a);case"events2"->events(x);case"guide"->guide(x);case"leaderboards2"->boards(x);case"claimflags"->x.sendMessage(ChatColor.GOLD+"Claim 2.0: explosion protection, trusted access and overlap protection are active. Use /claim.");}}catch(Exception e){x.sendMessage(ChatColor.RED+"2.0 system unavailable.");}return true;}
 private void season(Player x)throws Exception{x.sendMessage(ChatColor.GOLD+"ESN SEASON 2 "+ChatColor.GRAY+"XP "+get(x,"seasonxp")+" | Tier "+Math.min(50,get(x,"seasonxp")/500+1));x.sendMessage(ChatColor.YELLOW+"Mine, hunt, bosses, dungeons and raids advance the season.");}
 private void milestones(Player x,String[] a)throws Exception{int k=get(x,"bosskills"),r=get(x,"reward");int[] goals={5,15,30,50};if(a.length>0&&a[0].equalsIgnoreCase("claim")){if(r>=4){x.sendMessage(ChatColor.YELLOW+"All current milestones claimed.");return;}if(k<goals[r]){x.sendMessage(ChatColor.RED+"Next milestone requires "+goals[r]+" boss kills.");return;}long coins=(r+1)*5000L;eco.deposit(x,coins);x.getInventory().addItem(r>=2?LootDrops.dragonKey():LootDrops.key());try(PreparedStatement q=db.prepareStatement("UPDATE progress SET reward=reward+1 WHERE uuid=?")){q.setString(1,x.getUniqueId().toString());q.executeUpdate();}x.sendMessage(ChatColor.GREEN+"Milestone claimed: "+coins+" Coins + key!");}else x.sendMessage(ChatColor.GOLD+"Boss Reward Road: "+k+" kills | Next: "+(r<4?goals[r]:"complete")+" | /milestones claim");}
 private record Ach(String key,String name,String desc,Material icon,long coins,ItemStack item){}
 private List<Ach> achList(){return List.of(new Ach("First Boss","Titan's First Scar","Defeat your first ESN boss.",Material.NETHER_STAR,2500,MegaCrates.key(9)),new Ach("Dungeon Delver","Depthwalker","Complete your first dungeon.",Material.ENDER_CHEST,3500,MegaCrates.key(19)),new Ach("Raid Breaker","Siegebreaker","Complete your first raid.",Material.TOTEM_OF_UNDYING,5000,MegaCrates.key(29)),new Ach("Veteran Hunter","Crown Hunter","Defeat 50 bosses.",Material.DRAGON_HEAD,15000,MegaCrates.key(49)));}
 private boolean unlocked(Player x,String k)throws Exception{try(PreparedStatement q=db.prepareStatement("SELECT 1 FROM achievements WHERE uuid=? AND key=?")){q.setString(1,x.getUniqueId().toString());q.setString(2,k);try(ResultSet r=q.executeQuery()){return r.next();}}}
 private boolean achClaimed(Player x,String k)throws Exception{try(PreparedStatement q=db.prepareStatement("SELECT 1 FROM achievement_claims WHERE uuid=? AND key=?")){q.setString(1,x.getUniqueId().toString());q.setString(2,k);try(ResultSet r=q.executeQuery()){return r.next();}}}
 private void achievements(Player x)throws Exception{Inventory v=Bukkit.createInventory(null,54,ACH_MENU);int slot=10;for(Ach a:achList()){boolean u=unlocked(x,a.key()),cl=achClaimed(x,a.key());ItemStack i=new ItemStack(a.icon());ItemMeta m=i.getItemMeta();m.setDisplayName(ChatColor.AQUA+a.name());m.setLore(List.of(ChatColor.GRAY+a.desc(),ChatColor.GOLD+""+a.coins()+" ESN Coins",ChatColor.LIGHT_PURPLE+"Exclusive: "+a.item().getItemMeta().getDisplayName(),cl?ChatColor.GREEN+"CLAIMED":u?ChatColor.YELLOW+"CLICK TO CLAIM":ChatColor.RED+"LOCKED"));i.setItemMeta(m);v.setItem(slot++,i);}v.setItem(49,achNamed(Material.BARRIER,ChatColor.RED+"Close"));x.openInventory(v);}
 private ItemStack achNamed(Material mat,String name){ItemStack i=new ItemStack(mat);ItemMeta m=i.getItemMeta();m.setDisplayName(name);i.setItemMeta(m);return i;}
 private void claimAchievement(Player x,Ach a)throws Exception{if(!unlocked(x,a.key())){x.sendMessage(ChatColor.RED+"That achievement is locked.");return;}if(achClaimed(x,a.key())){x.sendMessage(ChatColor.YELLOW+"That achievement reward is already claimed.");return;}try(PreparedStatement q=db.prepareStatement("INSERT INTO achievement_claims(uuid,key) VALUES(?,?)")){q.setString(1,x.getUniqueId().toString());q.setString(2,a.key());q.executeUpdate();}eco.deposit(x,a.coins());ItemStack item=a.item().clone();ItemMeta m=item.getItemMeta();List<String> lore=m.hasLore()?new ArrayList<>(m.getLore()):new ArrayList<>();lore.add(ChatColor.AQUA+"ACHIEVEMENT EXCLUSIVE");lore.add(ChatColor.GRAY+a.name());m.setLore(lore);item.setItemMeta(m);x.getInventory().addItem(item).values().forEach(z->x.getWorld().dropItemNaturally(x.getLocation(),z));x.sendMessage(ChatColor.GREEN+"Achievement reward claimed: "+a.name());achievements(x);}
 @EventHandler public void titleMenu(org.bukkit.event.inventory.InventoryClickEvent e){if(!e.getView().getTitle().equals(TITLE_MENU))return;e.setCancelled(true);if(!(e.getWhoClicked() instanceof Player x))return;try{int s=e.getRawSlot();if(s==31){setTitle(x,"");x.sendMessage(ChatColor.YELLOW+"Player title unequipped.");openTitles(x);return;}int[] slots={10,12,14,16};for(int i=0;i<slots.length;i++)if(s==slots[i]){if(get(x,"bosskills")<titleNeeds[i]){x.sendMessage(ChatColor.RED+"That title is still locked.");return;}setTitle(x,titleNames[i]);x.sendMessage(ChatColor.GREEN+titleNames[i]+" title equipped.");openTitles(x);return;}}catch(Exception ex){x.sendMessage(ChatColor.RED+"Title menu unavailable.");p.getLogger().warning("Title menu: "+ex.getMessage());}}
 @EventHandler public void achievementMenu(org.bukkit.event.inventory.InventoryClickEvent e){if(!e.getView().getTitle().equals(ACH_MENU))return;e.setCancelled(true);if(!(e.getWhoClicked() instanceof Player x))return;try{if(e.getRawSlot()==49){x.closeInventory();return;}int idx=e.getRawSlot()-10;List<Ach> a=achList();if(idx>=0&&idx<a.size())claimAchievement(x,a.get(idx));}catch(Exception ex){x.sendMessage(ChatColor.RED+"Achievement reward unavailable.");}}
 private void unlock(Player x,String k){try(PreparedStatement q=db.prepareStatement("INSERT OR IGNORE INTO achievements(uuid,key) VALUES(?,?)")){q.setString(1,x.getUniqueId().toString());q.setString(2,k);if(q.executeUpdate()>0)x.sendMessage(ChatColor.GOLD+"Achievement unlocked: "+k);}catch(Exception ignored){}}
 private void bestiary(Player x)throws Exception{x.sendMessage(ChatColor.GREEN+"BESTIARY");try(PreparedStatement q=db.prepareStatement("SELECT mob,kills FROM bestiary WHERE uuid=? ORDER BY kills DESC LIMIT 8")){q.setString(1,x.getUniqueId().toString());try(ResultSet r=q.executeQuery()){while(r.next())x.sendMessage(ChatColor.GRAY+r.getString(1)+": "+r.getInt(2));}}}
 private static final String TITLE_MENU=ChatColor.DARK_PURPLE+"ESN Player Titles"; private final String[] titleNames={"Hunter","Slayer","Mythic","Legend"}; private final int[] titleNeeds={5,15,30,50}; private void title(Player x,String[] a)throws Exception{ensure(x);if(a.length==0){openTitles(x);return;}if(a[0].equalsIgnoreCase("none")||a[0].equalsIgnoreCase("clear")){setTitle(x,"");x.sendMessage(ChatColor.YELLOW+"Player title unequipped.");return;}for(int i=0;i<titleNames.length;i++)if(titleNames[i].equalsIgnoreCase(a[0])){if(get(x,"bosskills")<titleNeeds[i]){x.sendMessage(ChatColor.RED+"Title locked — defeat "+titleNeeds[i]+" bosses.");return;}setTitle(x,titleNames[i]);x.sendMessage(ChatColor.GREEN+titleNames[i]+" title equipped.");return;}x.sendMessage(ChatColor.RED+"Unknown title. Use /title to open your title menu.");} private void setTitle(Player x,String t)throws Exception{ensure(x);try(PreparedStatement q=db.prepareStatement("UPDATE progress SET title=? WHERE uuid=?")){q.setString(1,t);q.setString(2,x.getUniqueId().toString());q.executeUpdate();}refreshPlayerTag(x);} private void openTitles(Player x)throws Exception{ensure(x);Inventory v=Bukkit.createInventory(null,36,TITLE_MENU);int kills=get(x,"bosskills");String equipped=equippedTitle(x);int[] slots={10,12,14,16};Material[] mats={Material.IRON_SWORD,Material.DIAMOND_SWORD,Material.NETHERITE_SWORD,Material.NETHER_STAR};for(int i=0;i<titleNames.length;i++){boolean unlocked=kills>=titleNeeds[i],eq=titleNames[i].equalsIgnoreCase(equipped);v.setItem(slots[i],achNamed(mats[i],(unlocked?ChatColor.LIGHT_PURPLE:ChatColor.DARK_GRAY)+titleNames[i]));ItemMeta m=v.getItem(slots[i]).getItemMeta();m.setLore(List.of(ChatColor.GRAY+"Requirement: "+titleNeeds[i]+" boss kills",eq?ChatColor.GREEN+"EQUIPPED":unlocked?ChatColor.YELLOW+"Click to equip":ChatColor.RED+"LOCKED"));v.getItem(slots[i]).setItemMeta(m);}boolean champ=ServerChampionship.champion(p,x.getUniqueId());v.setItem(22,achNamed(Material.GOLDEN_HELMET,(champ?ChatColor.GOLD:ChatColor.DARK_GRAY)+"CHAMPION"));ItemMeta cm=v.getItem(22).getItemMeta();cm.setLore(List.of(ChatColor.GRAY+"Permanent Championship winner tag",champ?ChatColor.GREEN+"UNLOCKED — automatically displayed":ChatColor.RED+"Win the Server Championship to unlock"));v.getItem(22).setItemMeta(cm);v.setItem(31,achNamed(Material.BARRIER,ChatColor.RED+"Unequip Player Title"));x.openInventory(v);}
 private void party(Player x,String[] a){if(a.length==0){x.sendMessage(ChatColor.GOLD+"/party2 invite <player> | accept | leave");return;}if(a[0].equalsIgnoreCase("invite")&&a.length>1){Player y=PlayerResolver.online(a[1]);if(y==null){x.sendMessage(ChatColor.RED+"Player not found.");return;}invites.put(y.getUniqueId(),x.getUniqueId());y.sendMessage(ChatColor.GREEN+x.getName()+" invited you. /party2 accept");}else if(a[0].equalsIgnoreCase("accept")){UUID lead=invites.remove(x.getUniqueId());if(lead==null){x.sendMessage(ChatColor.RED+"No invite.");return;}leaders.put(x.getUniqueId(),lead);leaders.put(lead,lead);x.sendMessage(ChatColor.GREEN+"Party joined.");}else if(a[0].equalsIgnoreCase("leave")){leaders.remove(x.getUniqueId());x.sendMessage(ChatColor.YELLOW+"Left party.");}}
 private void events(Player x){long left=Math.max(0,(eventEnd-System.currentTimeMillis())/60000);x.sendMessage(ChatColor.LIGHT_PURPLE+"Current ESN Event: "+ChatColor.GOLD+activeEvent+ChatColor.GRAY+(activeEvent.equals("NONE")?" — waiting for next rotation":" — "+left+"m remaining"));x.sendMessage(ChatColor.GRAY+"Blood Hunt=bonus combat XP • Mining Frenzy=bonus mining XP • Key Storm=key drops • Boss Rush=empowered hostile mobs.");}
 private void eventPulse(){if(Bukkit.getOnlinePlayers().isEmpty())return;String[] e={"BLOOD HUNT","MINING FRENZY","KEY STORM","BOSS RUSH"};activeEvent=e[ThreadLocalRandom.current().nextInt(e.length)];eventEnd=System.currentTimeMillis()+15*60_000L;for(Player x:Bukkit.getOnlinePlayers()){x.sendTitle(ChatColor.LIGHT_PURPLE+"✦ ESN EVENT ✦",ChatColor.GOLD+activeEvent,10,70,20);x.playSound(x.getLocation(),Sound.UI_TOAST_CHALLENGE_COMPLETE,1f,1f);}Bukkit.broadcastMessage(ChatColor.LIGHT_PURPLE+"ESN EVENT: "+ChatColor.GOLD+activeEvent+ChatColor.GRAY+" — active for 15 minutes!");if(activeEvent.equals("BOSS RUSH"))for(World w:Bukkit.getWorlds())for(LivingEntity z:w.getLivingEntities())if(z instanceof Monster){z.addPotionEffect(new org.bukkit.potion.PotionEffect(org.bukkit.potion.PotionEffectType.STRENGTH,18000,0));z.addPotionEffect(new org.bukkit.potion.PotionEffect(org.bukkit.potion.PotionEffectType.SPEED,18000,0));}} private boolean eventActive(String n){return System.currentTimeMillis()<eventEnd&&activeEvent.equals(n);}
 private void guide(Player x){x.sendMessage(ChatColor.GOLD+"2.0 PATH: "+ChatColor.WHITE+"Claim land → choose jobs → daily quests → crates → dungeon/raid → swamp boss → world boss → forge relics → prestige.");}
 private void boards(Player x)throws Exception{x.sendMessage(ChatColor.GOLD+"2.0 Career: Season XP "+get(x,"seasonxp")+" | Bosses "+get(x,"bosskills")+" | Dungeons "+get(x,"dungeons")+" | Raids "+get(x,"raids"));}
 @EventHandler public void breakBlock(BlockBreakEvent e){int xp=eventActive("MINING FRENZY")?5:1;add(e.getPlayer(),"seasonxp",xp);add(e.getPlayer(),"weekly",xp);if(eventActive("MINING FRENZY")&&ThreadLocalRandom.current().nextDouble()<.01){e.getPlayer().giveExp(10);e.getPlayer().spawnParticle(Particle.HAPPY_VILLAGER,e.getBlock().getLocation().add(.5,.5,.5),8,.3,.3,.3,.02);}}
 @EventHandler public void hit(EntityDamageByEntityEvent e){Player a=e.getDamager() instanceof Player q?q:e.getDamager() instanceof Projectile pr&&pr.getShooter() instanceof Player q?q:null;if(a!=null&&e.getEntity() instanceof Player v){long u=System.currentTimeMillis()+15000;combat.put(a.getUniqueId(),u);combat.put(v.getUniqueId(),u);}}
 @EventHandler public void quit(PlayerQuitEvent e){if(combat.getOrDefault(e.getPlayer().getUniqueId(),0L)>System.currentTimeMillis()){e.getPlayer().setHealth(0);Bukkit.broadcastMessage(ChatColor.RED+e.getPlayer().getName()+" combat logged.");}}
 @EventHandler public void death(EntityDeathEvent e){Player x=e.getEntity().getKiller();if(x==null)return;String mob=e.getEntity().getType().name();try(PreparedStatement q=db.prepareStatement("INSERT INTO bestiary(uuid,mob,kills) VALUES(?,?,1) ON CONFLICT(uuid,mob) DO UPDATE SET kills=kills+1")){q.setString(1,x.getUniqueId().toString());q.setString(2,mob);q.executeUpdate();}catch(Exception ignored){}add(x,"seasonxp",(e.getEntity() instanceof Player?25:3)*(eventActive("BLOOD HUNT")?3:1));if(eventActive("KEY STORM")&&e.getEntity() instanceof Monster&&ThreadLocalRandom.current().nextDouble()<.15){x.getInventory().addItem(LootDrops.key()).values().forEach(z->x.getWorld().dropItemNaturally(x.getLocation(),z));x.sendActionBar(ChatColor.GOLD+"KEY STORM drop!");}if(e.getEntity().getScoreboardTags().contains("esnWorldBoss")||e.getEntity().getScoreboardTags().contains("esnSwampBoss")){add(x,"bosskills",1);add(x,"seasonxp",250);unlock(x,"First Boss");try{if(get(x,"bosskills")>=50)unlock(x,"Veteran Hunter");}catch(Exception ignored){}}if(e.getEntity().getScoreboardTags().contains("esnDungeonBoss")){add(x,"dungeons",1);add(x,"seasonxp",150);unlock(x,"Dungeon Delver");}if(e.getEntity().getScoreboardTags().contains("esnRaidBoss")){add(x,"raids",1);add(x,"seasonxp",300);unlock(x,"Raid Breaker");}}
 @EventHandler public void join(PlayerJoinEvent e){Player x=e.getPlayer();try{ensure(x);long now=System.currentTimeMillis(),last;try(PreparedStatement q=db.prepareStatement("SELECT lastjoin FROM progress WHERE uuid=?")){q.setString(1,x.getUniqueId().toString());try(ResultSet r=q.executeQuery()){last=r.next()?r.getLong(1):0;}}int st=now-last<172800000L?get(x,"streak")+1:1;if(now-last>72000000L)try(PreparedStatement q=db.prepareStatement("UPDATE progress SET streak=?,lastjoin=? WHERE uuid=?")){q.setInt(1,st);q.setLong(2,now);q.setString(3,x.getUniqueId().toString());q.executeUpdate();}if(st%7==0){eco.deposit(x,1500);x.getInventory().addItem(LootDrops.key());x.sendMessage(ChatColor.GOLD+"7-day streak reward: 1,500 Coins + key!");}}catch(Exception ignored){}}
 public static ItemStack secure(JavaPlugin p,ItemStack i,String value){ItemMeta m=i.getItemMeta();m.getPersistentDataContainer().set(new NamespacedKey(p,"esn_id"),PersistentDataType.STRING,value);i.setItemMeta(m);return i;}
 public void refreshPlayerTag(Player x){String rank=x.hasPermission("esnsmp.owner")?ChatColor.DARK_RED+"[OWNER] ":x.hasPermission("esnsmp.staff.admin")?ChatColor.RED+"[ADMIN] ":x.hasPermission("esnsmp.staff.seniormod")?ChatColor.DARK_PURPLE+"[SR MOD] ":x.hasPermission("esnsmp.staff.moderator")?ChatColor.LIGHT_PURPLE+"[MOD] ":x.hasPermission("esnsmp.staff.trialmod")?ChatColor.BLUE+"[TRIAL MOD] ":x.hasPermission("esnsmp.staff.helper")?ChatColor.GREEN+"[HELPER] ":ChatColor.GRAY+"[MEMBER] ";String champ=ServerChampionship.champion(p,x.getUniqueId())?ChatColor.GOLD+"[CHAMPION] ":"";String title=equippedTitle(x);String titleTag=title==null||title.isBlank()?"":ChatColor.LIGHT_PURPLE+"["+title+"] ";String tags=rank+champ+titleTag;x.setPlayerListName(tags+ChatColor.WHITE+x.getName());for(Player viewer:Bukkit.getOnlinePlayers()){org.bukkit.scoreboard.Scoreboard board=viewer.getScoreboard();String tn="esn_"+x.getUniqueId().toString().substring(0,12);Team team=board.getTeam(tn);if(team==null)team=board.registerNewTeam(tn);for(Team other:board.getTeams())if(other!=team&&other.hasEntry(x.getName()))other.removeEntry(x.getName());team.prefix(net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializer.legacySection().deserialize(tags));team.addEntry(x.getName());team.setOption(Team.Option.NAME_TAG_VISIBILITY,Team.OptionStatus.ALWAYS);}}
 @EventHandler public void refreshTag(org.bukkit.event.player.PlayerJoinEvent e){Bukkit.getScheduler().runTaskLater(p,()->{for(Player online:Bukkit.getOnlinePlayers())refreshPlayerTag(online);},5L);}
 public void close()throws Exception{if(db!=null)db.close();}
 public String equippedTitle(Player p){try{ensure(p);try(PreparedStatement q=db.prepareStatement("SELECT title FROM progress WHERE uuid=?")){q.setString(1,p.getUniqueId().toString());try(ResultSet r=q.executeQuery()){return r.next()?r.getString("title"):"";}}}catch(Exception e){return "";}}
}
