package com.esn.smp.gameplay;
import com.esn.smp.data.ESNDataStore;import org.bukkit.*;import org.bukkit.command.*;import org.bukkit.entity.*;import org.bukkit.event.*;import org.bukkit.event.block.*;import org.bukkit.event.entity.*;import org.bukkit.event.player.*;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.ItemMeta;import org.bukkit.persistence.*;import org.bukkit.plugin.java.JavaPlugin;import java.io.*;import java.sql.*;import java.util.*;import java.util.concurrent.ThreadLocalRandom;
public final class ESN20Expansion implements Listener,CommandExecutor,AutoCloseable{
 private final JavaPlugin p;private final ESNDataStore eco;private Connection db;private final NamespacedKey id;private final Map<UUID,Long> combat=new HashMap<>();private final Map<UUID,UUID> invites=new HashMap<>(),leaders=new HashMap<>();
 public ESN20Expansion(JavaPlugin p,ESNDataStore e)throws Exception{this.p=p;eco=e;id=new NamespacedKey(p,"esn_id");db=DriverManager.getConnection("jdbc:sqlite:"+new File(p.getDataFolder(),"esn20-expansion.db"));try(Statement s=db.createStatement()){s.execute("CREATE TABLE IF NOT EXISTS progress(uuid TEXT PRIMARY KEY,seasonxp INTEGER DEFAULT 0,weekly INTEGER DEFAULT 0,streak INTEGER DEFAULT 0,lastjoin INTEGER DEFAULT 0,reward INTEGER DEFAULT 0,title TEXT DEFAULT '',bosskills INTEGER DEFAULT 0,dungeons INTEGER DEFAULT 0,raids INTEGER DEFAULT 0)");s.execute("CREATE TABLE IF NOT EXISTS achievements(uuid TEXT,key TEXT,PRIMARY KEY(uuid,key))");s.execute("CREATE TABLE IF NOT EXISTS bestiary(uuid TEXT,mob TEXT,kills INTEGER DEFAULT 0,PRIMARY KEY(uuid,mob))");s.execute("CREATE TABLE IF NOT EXISTS graves(uuid TEXT PRIMARY KEY,world TEXT,x INTEGER,y INTEGER,z INTEGER,expires INTEGER)");}Bukkit.getScheduler().runTaskTimer(p,this::eventPulse,72000L,72000L);}
 private void ensure(Player x)throws Exception{try(PreparedStatement q=db.prepareStatement("INSERT OR IGNORE INTO progress(uuid) VALUES(?)")){q.setString(1,x.getUniqueId().toString());q.executeUpdate();}}
 private int get(Player x,String c)throws Exception{ensure(x);try(PreparedStatement q=db.prepareStatement("SELECT "+c+" FROM progress WHERE uuid=?")){q.setString(1,x.getUniqueId().toString());try(ResultSet r=q.executeQuery()){return r.next()?r.getInt(1):0;}}}
 private void add(Player x,String c,int n){try{ensure(x);try(PreparedStatement q=db.prepareStatement("UPDATE progress SET "+c+"="+c+"+? WHERE uuid=?")){q.setInt(1,n);q.setString(2,x.getUniqueId().toString());q.executeUpdate();}}catch(Exception ignored){}}
 public boolean onCommand(CommandSender s,Command c,String l,String[] a){if(!(s instanceof Player x))return true;try{switch(c.getName()){case"season2"->season(x);case"milestones"->milestones(x,a);case"bestiary2"->bestiary(x);case"achievements2"->achievements(x);case"title"->title(x,a);case"party2"->party(x,a);case"events2"->events(x);case"guide"->guide(x);case"leaderboards2"->boards(x);case"claimflags"->x.sendMessage(ChatColor.GOLD+"Claim 2.0: explosion protection, trusted access and overlap protection are active. Use /claim.");}}catch(Exception e){x.sendMessage(ChatColor.RED+"2.0 system unavailable.");}return true;}
 private void season(Player x)throws Exception{x.sendMessage(ChatColor.GOLD+"ESN SEASON 2 "+ChatColor.GRAY+"XP "+get(x,"seasonxp")+" | Tier "+Math.min(50,get(x,"seasonxp")/500+1));x.sendMessage(ChatColor.YELLOW+"Mine, hunt, bosses, dungeons and raids advance the season.");}
 private void milestones(Player x,String[] a)throws Exception{int k=get(x,"bosskills"),r=get(x,"reward");int[] goals={5,15,30,50};if(a.length>0&&a[0].equalsIgnoreCase("claim")){if(r>=4){x.sendMessage(ChatColor.YELLOW+"All current milestones claimed.");return;}if(k<goals[r]){x.sendMessage(ChatColor.RED+"Next milestone requires "+goals[r]+" boss kills.");return;}long coins=(r+1)*5000L;eco.deposit(x,coins);x.getInventory().addItem(r>=2?LootDrops.dragonKey():LootDrops.key());try(PreparedStatement q=db.prepareStatement("UPDATE progress SET reward=reward+1 WHERE uuid=?")){q.setString(1,x.getUniqueId().toString());q.executeUpdate();}x.sendMessage(ChatColor.GREEN+"Milestone claimed: "+coins+" Coins + key!");}else x.sendMessage(ChatColor.GOLD+"Boss Reward Road: "+k+" kills | Next: "+(r<4?goals[r]:"complete")+" | /milestones claim");}
 private void achievements(Player x)throws Exception{int n;try(PreparedStatement q=db.prepareStatement("SELECT COUNT(*) FROM achievements WHERE uuid=?")){q.setString(1,x.getUniqueId().toString());try(ResultSet r=q.executeQuery()){n=r.next()?r.getInt(1):0;}}x.sendMessage(ChatColor.AQUA+"2.0 Achievements unlocked: "+n+" | First Boss, Dungeon Delver, Raid Breaker, Veteran Hunter");}
 private void unlock(Player x,String k){try(PreparedStatement q=db.prepareStatement("INSERT OR IGNORE INTO achievements(uuid,key) VALUES(?,?)")){q.setString(1,x.getUniqueId().toString());q.setString(2,k);if(q.executeUpdate()>0)x.sendMessage(ChatColor.GOLD+"Achievement unlocked: "+k);}catch(Exception ignored){}}
 private void bestiary(Player x)throws Exception{x.sendMessage(ChatColor.GREEN+"BESTIARY");try(PreparedStatement q=db.prepareStatement("SELECT mob,kills FROM bestiary WHERE uuid=? ORDER BY kills DESC LIMIT 8")){q.setString(1,x.getUniqueId().toString());try(ResultSet r=q.executeQuery()){while(r.next())x.sendMessage(ChatColor.GRAY+r.getString(1)+": "+r.getInt(2));}}}
 private void title(Player x,String[] a)throws Exception{if(a.length==0){x.sendMessage(ChatColor.GOLD+"Titles: Hunter(5 bosses), Slayer(15), Mythic(30), Legend(50). /title <name>");return;}String t=a[0];int k=get(x,"bosskills"),need=t.equalsIgnoreCase("Hunter")?5:t.equalsIgnoreCase("Slayer")?15:t.equalsIgnoreCase("Mythic")?30:t.equalsIgnoreCase("Legend")?50:999999;if(k<need){x.sendMessage(ChatColor.RED+"Title locked.");return;}try(PreparedStatement q=db.prepareStatement("UPDATE progress SET title=? WHERE uuid=?")){q.setString(1,t);q.setString(2,x.getUniqueId().toString());q.executeUpdate();}x.setPlayerListName(ChatColor.GOLD+"["+t+"] "+ChatColor.WHITE+x.getName());x.sendMessage(ChatColor.GREEN+"Title equipped.");}
 private void party(Player x,String[] a){if(a.length==0){x.sendMessage(ChatColor.GOLD+"/party2 invite <player> | accept | leave");return;}if(a[0].equalsIgnoreCase("invite")&&a.length>1){Player y=PlayerResolver.online(a[1]);if(y==null){x.sendMessage(ChatColor.RED+"Player not found.");return;}invites.put(y.getUniqueId(),x.getUniqueId());y.sendMessage(ChatColor.GREEN+x.getName()+" invited you. /party2 accept");}else if(a[0].equalsIgnoreCase("accept")){UUID lead=invites.remove(x.getUniqueId());if(lead==null){x.sendMessage(ChatColor.RED+"No invite.");return;}leaders.put(x.getUniqueId(),lead);leaders.put(lead,lead);x.sendMessage(ChatColor.GREEN+"Party joined.");}else if(a[0].equalsIgnoreCase("leave")){leaders.remove(x.getUniqueId());x.sendMessage(ChatColor.YELLOW+"Left party.");}}
 private void events(Player x){x.sendMessage(ChatColor.LIGHT_PURPLE+"Events 2.0: Blood Hunt, Mining Frenzy, Key Storm and Boss Rush rotate as global hourly events.");}
 private void eventPulse(){if(Bukkit.getOnlinePlayers().isEmpty())return;String[] e={"BLOOD HUNT — bonus combat progression!","MINING FRENZY — mine for Season XP!","KEY STORM — hunt mobs for crate keys!","BOSS RUSH — prepare for the next world boss!"};Bukkit.broadcastMessage(ChatColor.LIGHT_PURPLE+"ESN EVENT: "+e[ThreadLocalRandom.current().nextInt(e.length)]);}
 private void guide(Player x){x.sendMessage(ChatColor.GOLD+"2.0 PATH: "+ChatColor.WHITE+"Claim land → choose jobs → daily quests → crates → dungeon/raid → swamp boss → world boss → forge relics → prestige.");}
 private void boards(Player x)throws Exception{x.sendMessage(ChatColor.GOLD+"2.0 Career: Season XP "+get(x,"seasonxp")+" | Bosses "+get(x,"bosskills")+" | Dungeons "+get(x,"dungeons")+" | Raids "+get(x,"raids"));}
 @EventHandler public void breakBlock(BlockBreakEvent e){add(e.getPlayer(),"seasonxp",1);add(e.getPlayer(),"weekly",1);}
 @EventHandler public void hit(EntityDamageByEntityEvent e){Player a=e.getDamager() instanceof Player q?q:e.getDamager() instanceof Projectile pr&&pr.getShooter() instanceof Player q?q:null;if(a!=null&&e.getEntity() instanceof Player v){long u=System.currentTimeMillis()+15000;combat.put(a.getUniqueId(),u);combat.put(v.getUniqueId(),u);}}
 @EventHandler public void quit(PlayerQuitEvent e){if(combat.getOrDefault(e.getPlayer().getUniqueId(),0L)>System.currentTimeMillis()){e.getPlayer().setHealth(0);Bukkit.broadcastMessage(ChatColor.RED+e.getPlayer().getName()+" combat logged.");}}
 @EventHandler public void death(EntityDeathEvent e){Player x=e.getEntity().getKiller();if(x==null)return;String mob=e.getEntity().getType().name();try(PreparedStatement q=db.prepareStatement("INSERT INTO bestiary(uuid,mob,kills) VALUES(?,?,1) ON CONFLICT(uuid,mob) DO UPDATE SET kills=kills+1")){q.setString(1,x.getUniqueId().toString());q.setString(2,mob);q.executeUpdate();}catch(Exception ignored){}add(x,"seasonxp",e.getEntity() instanceof Player?25:3);if(e.getEntity().getScoreboardTags().contains("esnWorldBoss")||e.getEntity().getScoreboardTags().contains("esnSwampBoss")){add(x,"bosskills",1);add(x,"seasonxp",250);unlock(x,"First Boss");}}
 @EventHandler public void join(PlayerJoinEvent e){Player x=e.getPlayer();try{ensure(x);long now=System.currentTimeMillis(),last;try(PreparedStatement q=db.prepareStatement("SELECT lastjoin FROM progress WHERE uuid=?")){q.setString(1,x.getUniqueId().toString());try(ResultSet r=q.executeQuery()){last=r.next()?r.getLong(1):0;}}int st=now-last<172800000L?get(x,"streak")+1:1;if(now-last>72000000L)try(PreparedStatement q=db.prepareStatement("UPDATE progress SET streak=?,lastjoin=? WHERE uuid=?")){q.setInt(1,st);q.setLong(2,now);q.setString(3,x.getUniqueId().toString());q.executeUpdate();}if(st%7==0){eco.deposit(x,1500);x.getInventory().addItem(LootDrops.key());x.sendMessage(ChatColor.GOLD+"7-day streak reward: 1,500 Coins + key!");}}catch(Exception ignored){}}
 public static ItemStack secure(JavaPlugin p,ItemStack i,String value){ItemMeta m=i.getItemMeta();m.getPersistentDataContainer().set(new NamespacedKey(p,"esn_id"),PersistentDataType.STRING,value);i.setItemMeta(m);return i;}
 public void close()throws Exception{if(db!=null)db.close();}
}