package com.esn.smp.gameplay;
import com.esn.smp.data.ESNDataStore;
import org.bukkit.*;import org.bukkit.attribute.Attribute;import org.bukkit.command.*;import org.bukkit.entity.*;import org.bukkit.event.*;import org.bukkit.event.entity.*;import org.bukkit.event.player.*;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.ItemMeta;import org.bukkit.persistence.*;import org.bukkit.plugin.java.JavaPlugin;import org.bukkit.potion.*;import java.io.*;import java.sql.*;import java.util.*;import java.util.concurrent.ThreadLocalRandom;
public final class ESNAdventureEngine implements Listener,CommandExecutor,AutoCloseable{
 private final JavaPlugin p;private final ESNDataStore eco;private Connection db;private final Map<UUID,Integer> ultimate=new HashMap<>(),streak=new HashMap<>();private final Map<UUID,Long> cd=new HashMap<>();private final NamespacedKey rarity,ability;private String event="CALM";private final Map<UUID,Long> downed=new HashMap<>();private final Map<UUID,String> nemesis=new HashMap<>();private final Map<UUID,Integer> bounty=new HashMap<>(),bountyProgress=new HashMap<>();private final Set<UUID> activeRush=new HashSet<>();private long eventEnd=0;
 private static final String[] CLASSES={"BERSERKER","ASSASSIN","PALADIN","MAGE","RANGER","NECROMANCER","TITAN"};
 public ESNAdventureEngine(JavaPlugin p,ESNDataStore e)throws Exception{this.p=p;eco=e;rarity=new NamespacedKey(p,"adv_rarity");ability=new NamespacedKey(p,"adv_ability");db=DriverManager.getConnection("jdbc:sqlite:"+new File(p.getDataFolder(),"adventure-engine.db"));try(Statement s=db.createStatement()){s.execute("CREATE TABLE IF NOT EXISTS profile(uuid TEXT PRIMARY KEY,class TEXT DEFAULT 'BERSERKER',bossstreak INTEGER DEFAULT 0,rifts INTEGER DEFAULT 0,rush INTEGER DEFAULT 0,endless INTEGER DEFAULT 0,reputation INTEGER DEFAULT 0,ultimates INTEGER DEFAULT 0)");s.execute("CREATE TABLE IF NOT EXISTS records(k TEXT PRIMARY KEY,v INTEGER DEFAULT 0,holder TEXT DEFAULT '')");s.execute("CREATE TABLE IF NOT EXISTS guilds(uuid TEXT PRIMARY KEY,guild TEXT DEFAULT '',xp INTEGER DEFAULT 0)");s.execute("CREATE TABLE IF NOT EXISTS trophies(uuid TEXT,k TEXT,n INTEGER DEFAULT 0,PRIMARY KEY(uuid,k))");s.execute("CREATE TABLE IF NOT EXISTS collections(uuid TEXT,k TEXT,n INTEGER DEFAULT 0,PRIMARY KEY(uuid,k))");s.execute("CREATE TABLE IF NOT EXISTS achievements(uuid TEXT,k TEXT,PRIMARY KEY(uuid,k))");}Bukkit.getScheduler().runTaskTimer(p,this::pulse,2400L,24000L);}
 private void ensure(Player x)throws Exception{try(PreparedStatement q=db.prepareStatement("INSERT OR IGNORE INTO profile(uuid) VALUES(?)")){q.setString(1,x.getUniqueId().toString());q.executeUpdate();}}
 private String cls(Player x)throws Exception{ensure(x);try(PreparedStatement q=db.prepareStatement("SELECT class FROM profile WHERE uuid=?")){q.setString(1,x.getUniqueId().toString());try(ResultSet r=q.executeQuery()){return r.next()?r.getString(1):"BERSERKER";}}}
 private void inc(Player x,String col,int n){try{ensure(x);try(PreparedStatement q=db.prepareStatement("UPDATE profile SET "+col+"="+col+"+? WHERE uuid=?")){q.setInt(1,n);q.setString(2,x.getUniqueId().toString());q.executeUpdate();}}catch(Exception z){p.getLogger().warning("Adventure progress: "+z.getMessage());}}
 public boolean onCommand(CommandSender s,Command c,String l,String[] a){if(!(s instanceof Player x))return true;try{switch(c.getName()){
  case"adventure"->x.sendMessage(ChatColor.LIGHT_PURPLE+"ESN Adventure Engine | Event "+event+" | Class "+cls(x)+" | Ultimate "+ultimate.getOrDefault(x.getUniqueId(),0)+"%");
  case"class"->{if(a.length==0){x.sendMessage(ChatColor.GOLD+"Classes: "+String.join(", ",CLASSES)+" | /class <name>");break;}String v=a[0].toUpperCase(Locale.ROOT);if(!Arrays.asList(CLASSES).contains(v)){x.sendMessage(ChatColor.RED+"Unknown class.");break;}try(PreparedStatement q=db.prepareStatement("UPDATE profile SET class=? WHERE uuid=?")){ensure(x);q.setString(1,v);q.setString(2,x.getUniqueId().toString());q.executeUpdate();}x.sendMessage(ChatColor.GREEN+"Class equipped: "+v);}
  case"ultimate"->ultimate(x);
  case"rift"->startRift(x);
  case"bossrush"->startRush(x);
  case"records"->records(x);
  case"guild"->guild(x,a);
  case"trophies"->trophies(x);case"bountyboard"->bountyBoard(x);case"hunt"->hunt(x);case"artifactfusion"->fusion(x);case"adventureachievements"->achievements(x);case"revive"->revive(x);
 }}catch(Exception z){x.sendMessage(ChatColor.RED+"Adventure system unavailable; check console.");p.getLogger().warning("Adventure command: "+z.getMessage());}return true;}
 private void ultimate(Player x)throws Exception{if(ultimate.getOrDefault(x.getUniqueId(),0)<100){x.sendMessage(ChatColor.RED+"Ultimate meter is not full.");return;}ultimate.put(x.getUniqueId(),0);inc(x,"ultimates",1);String c=cls(x);switch(c){case"BERSERKER"->x.addPotionEffect(new PotionEffect(PotionEffectType.STRENGTH,200,4));case"ASSASSIN"->{x.addPotionEffect(new PotionEffect(PotionEffectType.SPEED,240,3));x.addPotionEffect(new PotionEffect(PotionEffectType.INVISIBILITY,100,0));}case"PALADIN"->{x.addPotionEffect(new PotionEffect(PotionEffectType.RESISTANCE,240,2));x.setHealth(Math.min(x.getAttribute(Attribute.MAX_HEALTH).getValue(),x.getHealth()+12));}case"MAGE"->blast(x,18,12);case"RANGER"->blast(x,14,18);case"NECROMANCER"->{for(int i=0;i<4;i++){Wolf w=(Wolf)x.getWorld().spawnEntity(x.getLocation(),EntityType.WOLF);w.setOwner(x);w.setCustomName(ChatColor.DARK_PURPLE+"Soul Hound");}}case"TITAN"->{x.addPotionEffect(new PotionEffect(PotionEffectType.RESISTANCE,300,3));x.addPotionEffect(new PotionEffect(PotionEffectType.STRENGTH,300,2));}}x.getWorld().spawnParticle(Particle.TOTEM_OF_UNDYING,x.getLocation().add(0,1,0),100,2,2,2,.2);Bukkit.broadcastMessage(ChatColor.GOLD+x.getName()+" unleashed "+c+" ULTIMATE!");}
 private void blast(Player x,double dmg,double radius){for(Entity e:x.getNearbyEntities(radius,radius,radius))if(e instanceof Monster m)m.damage(dmg,x);}
 private void startRift(Player x){Location o=x.getLocation().clone().add(8,0,8);Bukkit.broadcastMessage(ChatColor.DARK_PURPLE+"A RIFT opened near "+x.getName()+"! Survive three waves.");for(int w=0;w<3;w++){final int wave=w;Bukkit.getScheduler().runTaskLater(p,()->spawnWave(o,5+wave*3,"esnRift"),wave*240L);}Bukkit.getScheduler().runTaskLater(p,()->{LivingEntity b=spawnBoss(o,EntityType.ENDERMAN,"RIFT GUARDIAN",8000);b.addScoreboardTag("esnRiftBoss");},760L);}
 private void startRush(Player x){if(!activeRush.add(x.getUniqueId())){x.sendMessage(ChatColor.RED+"You already have an active Boss Rush.");return;}Bukkit.broadcastMessage(ChatColor.RED+x.getName()+" started BOSS RUSH: five bosses, one at a time!");spawnRush(x,1);} private void spawnRush(Player x,int stage){if(!x.isOnline()){activeRush.remove(x.getUniqueId());return;}LivingEntity b=spawnBoss(x.getLocation().clone().add(7,0,7),stage%2==1?EntityType.RAVAGER:EntityType.WITHER_SKELETON,"RUSH "+stage,5000+(stage-1)*2500);b.addScoreboardTag("esnRushBoss");b.addScoreboardTag("esnRushOwner_"+x.getUniqueId());b.addScoreboardTag("esnRushStage_"+stage);}
 private void spawnWave(Location o,int n,String tag){for(int i=0;i<n;i++){Location q=o.clone().add(ThreadLocalRandom.current().nextInt(-7,8),1,ThreadLocalRandom.current().nextInt(-7,8));Monster m=(Monster)o.getWorld().spawnEntity(q,ThreadLocalRandom.current().nextBoolean()?EntityType.ZOMBIE:EntityType.SKELETON);m.addScoreboardTag(tag);m.setCustomName(ChatColor.DARK_PURPLE+"Riftborn");}}
 private LivingEntity spawnBoss(Location o,EntityType t,String name,double hp){o.setY(o.getWorld().getHighestBlockYAt(o.getBlockX(),o.getBlockZ())+1);LivingEntity b=(LivingEntity)o.getWorld().spawnEntity(o,t);b.setCustomName(ChatColor.RED+name);b.setCustomNameVisible(true);b.setPersistent(true);b.setGlowing(true);var a=b.getAttribute(Attribute.MAX_HEALTH);if(a!=null){double safeHp=Math.min(1000.0,hp);a.setBaseValue(safeHp);b.setHealth(safeHp);}b.addScoreboardTag("esnAdventureBoss");String[] mods={"BERSERK","VAMPIRIC","TELEPORTER","JUGGERNAUT","SUMMONER","VOID"};b.addScoreboardTag("esnMod_"+mods[ThreadLocalRandom.current().nextInt(mods.length)]);return b;}
 @EventHandler public void eventSpawn(CreatureSpawnEvent e){if(System.currentTimeMillis()>=eventEnd||!(e.getEntity() instanceof Monster m))return;if(event.equals("BLOOD_MOON")){m.addPotionEffect(new PotionEffect(PotionEffectType.STRENGTH,1200,2));m.addPotionEffect(new PotionEffect(PotionEffectType.SPEED,1200,1));}if(event.equals("VOID_INVASION")){m.addPotionEffect(new PotionEffect(PotionEffectType.RESISTANCE,1200,1));if(ThreadLocalRandom.current().nextDouble()<.12)m.addScoreboardTag("esnElite");}}
 @EventHandler public void eventRewards(EntityDeathEvent e){if(System.currentTimeMillis()>=eventEnd)return;Player x=e.getEntity().getKiller();if(x==null)return;if(event.equals("DOUBLE_BOSS_REWARDS")&&(e.getEntity().getScoreboardTags().contains("esnWorldBoss")||e.getEntity().getScoreboardTags().contains("esnBiomeBoss")||e.getEntity().getScoreboardTags().contains("esnSwampBoss"))){try{eco.deposit(x,5000);}catch(Exception ignored){}x.sendMessage(ChatColor.GOLD+"Double Boss Rewards event bonus: +5,000 Coins");}if(event.equals("TREASURE_RUSH")&&e.getEntity() instanceof Monster&&ThreadLocalRandom.current().nextDouble()<.12)e.getDrops().add(LootDrops.key());}
 @EventHandler public void hit(EntityDamageByEntityEvent e){Player x=e.getDamager() instanceof Player q?q:e.getDamager() instanceof Projectile pr&&pr.getShooter() instanceof Player q?q:null;if(x!=null){ultimate.put(x.getUniqueId(),Math.min(100,ultimate.getOrDefault(x.getUniqueId(),0)+(int)Math.max(1,e.getFinalDamage()/3)));try{String c=cls(x);if(c.equals("BERSERKER")&&x.getHealth()<x.getAttribute(Attribute.MAX_HEALTH).getValue()*.35)e.setDamage(e.getDamage()*1.2);if(c.equals("ASSASSIN")&&ThreadLocalRandom.current().nextDouble()<.08)e.setDamage(e.getDamage()*1.75);}catch(Exception ignored){}}if(e.getEntity() instanceof LivingEntity b&&b.getScoreboardTags().contains("esnAdventureBoss"))for(String t:b.getScoreboardTags()){if(t.equals("esnMod_BERSERK")&&b.getHealth()<b.getAttribute(Attribute.MAX_HEALTH).getValue()*.35)e.setDamage(e.getDamage()*1.5);if(t.equals("esnMod_TELEPORTER")&&ThreadLocalRandom.current().nextDouble()<.05&&x!=null)b.teleport(x.getLocation().clone().add(2,0,2));}}
 @EventHandler public void death(EntityDeathEvent e){LivingEntity b=e.getEntity();Player x=b.getKiller();if(x==null)return;if(b instanceof Monster&&!b.getScoreboardTags().contains("esnAdventureBoss")){Integer target=bounty.get(x.getUniqueId());if(target!=null){int n=bountyProgress.merge(x.getUniqueId(),1,Integer::sum);if(n>=target){bounty.remove(x.getUniqueId());bountyProgress.remove(x.getUniqueId());try{eco.deposit(x,2500);}catch(Exception ex){p.getLogger().warning("Bounty deposit: "+ex.getMessage());}inc(x,"reputation",15);achievement(x,"Bounty Hunter");x.sendMessage(ChatColor.GOLD+"Bounty complete! +2,500 Coins +15 reputation.");}else x.sendActionBar(ChatColor.YELLOW+"Bounty "+n+"/"+target);}}if(b.getScoreboardTags().contains("esnAdventureBoss")||b.getScoreboardTags().contains("esnWorldBoss")||b.getScoreboardTags().contains("esnBiomeBoss")||b.getScoreboardTags().contains("esnSwampBoss")){int st=streak.merge(x.getUniqueId(),1,Integer::sum);inc(x,"reputation",5);trophy(x,"boss");if(b.getScoreboardTags().contains("esnRiftBoss")){inc(x,"rifts",1);trophy(x,"rift");achievement(x,"Riftwalker");}if(b.getScoreboardTags().contains("esnRushBoss")){inc(x,"rush",1);int stage=0;UUID owner=null;for(String t:b.getScoreboardTags()){if(t.startsWith("esnRushStage_"))try{stage=Integer.parseInt(t.substring(13));}catch(Exception ignored){}if(t.startsWith("esnRushOwner_"))try{owner=UUID.fromString(t.substring(13));}catch(Exception ignored){}}if(owner!=null){Player o=Bukkit.getPlayer(owner);if(stage<5&&o!=null){final int nextStage=stage+1;Bukkit.getScheduler().runTaskLater(p,()->spawnRush(o,nextStage),80L);}else{activeRush.remove(owner);if(o!=null){try{eco.deposit(o,10000);}catch(Exception ex){p.getLogger().warning("Boss Rush deposit: "+ex.getMessage());}achievement(o,"Boss Rush Champion");o.sendMessage(ChatColor.GOLD+"BOSS RUSH COMPLETE! +10,000 Coins.");}}}}if(st>=10)achievement(x,"Titanbreaker");if(st%5==0)x.sendMessage(ChatColor.GOLD+"Boss streak "+st+"! Bonus reputation earned.");if(ThreadLocalRandom.current().nextDouble()<.12)e.getDrops().add(mythicItem(x));updateRecord("boss_streak",st,x);}}
 @EventHandler public void playerDeath(PlayerDeathEvent e){Player x=e.getEntity();streak.put(x.getUniqueId(),0);bountyProgress.put(x.getUniqueId(),0);Player k=x.getKiller();if(k!=null)nemesis.put(x.getUniqueId(),k.getName());}
 @EventHandler public void lethal(EntityDamageEvent e){if(!(e.getEntity() instanceof Player x)||downed.containsKey(x.getUniqueId())||e.getFinalDamage()<x.getHealth())return;boolean instance=x.getWorld().getLivingEntities().stream().anyMatch(z->z.getScoreboardTags().contains("esnRift")||z.getScoreboardTags().contains("esnRiftBoss")||z.getScoreboardTags().contains("esnRushBoss"));if(!instance)return;e.setCancelled(true);x.setHealth(Math.max(1,Math.min(2,x.getAttribute(Attribute.MAX_HEALTH).getValue())));x.addPotionEffect(new PotionEffect(PotionEffectType.SLOWNESS,200,8));downed.put(x.getUniqueId(),System.currentTimeMillis()+10000);x.sendMessage(ChatColor.RED+"DOWNED! A teammate has 10 seconds to use /revive near you.");Bukkit.getScheduler().runTaskLater(p,()->{Long until=downed.get(x.getUniqueId());if(until!=null&&System.currentTimeMillis()>=until){downed.remove(x.getUniqueId());x.setHealth(0);}},200L);}
 private ItemStack mythicItem(Player x){Material[] ms={Material.NETHERITE_SWORD,Material.NETHERITE_AXE,Material.BOW,Material.NETHERITE_CHESTPLATE};ItemStack i=new ItemStack(ms[ThreadLocalRandom.current().nextInt(ms.length)]);ItemMeta m=i.getItemMeta();String[] rs={"RARE","EPIC","LEGENDARY","MYTHIC","DIVINE","FORBIDDEN"},ab={"METEOR","VOID_DASH","CHAIN_LIGHTNING","GROUND_SLAM","SOUL_STEAL","TITAN_SMASH"};String r=rs[ThreadLocalRandom.current().nextInt(rs.length)];String a=ab[ThreadLocalRandom.current().nextInt(ab.length)];m.setDisplayName(ChatColor.LIGHT_PURPLE+r+" "+a.replace('_',' ')+" "+i.getType().name().replace('_',' '));m.setLore(List.of(ChatColor.GRAY+"Generated for "+x.getName(),ChatColor.GOLD+"Ability: "+a,ChatColor.AQUA+"Randomized ESN mythic drop"));m.getPersistentDataContainer().set(rarity,PersistentDataType.STRING,r);m.getPersistentDataContainer().set(ability,PersistentDataType.STRING,a);i.setItemMeta(m);return i;}
 @EventHandler public void use(PlayerInteractEvent e){if(e.getAction().name().contains("RIGHT")){ItemStack i=e.getItem();if(i==null||!i.hasItemMeta())return;String a=i.getItemMeta().getPersistentDataContainer().get(ability,PersistentDataType.STRING);if(a==null)return;Player x=e.getPlayer();long now=System.currentTimeMillis();if(cd.getOrDefault(x.getUniqueId(),0L)>now){x.sendActionBar(ChatColor.RED+"Ability cooling down");return;}cd.put(x.getUniqueId(),now+20000);switch(a){case"METEOR","GROUND_SLAM","TITAN_SMASH"->blast(x,16,10);case"VOID_DASH"->x.teleport(x.getLocation().add(x.getLocation().getDirection().multiply(8)));case"CHAIN_LIGHTNING"->blast(x,12,14);case"SOUL_STEAL"->{blast(x,10,8);x.setHealth(Math.min(x.getAttribute(Attribute.MAX_HEALTH).getValue(),x.getHealth()+6));}}x.getWorld().spawnParticle(Particle.ENCHANT,x.getLocation(),50,1,1,1,.1);}}
 private void bountyBoard(Player x){int n=bounty.computeIfAbsent(x.getUniqueId(),k->ThreadLocalRandom.current().nextInt(3,9));int done=bountyProgress.getOrDefault(x.getUniqueId(),0);x.sendMessage(ChatColor.GOLD+"BOUNTY BOARD: hostile mobs "+done+"/"+n+". Reward: 2,500 Coins +15 reputation.");}
 private void hunt(Player x){Location q=x.getLocation().clone().add(ThreadLocalRandom.current().nextInt(80,181),0,ThreadLocalRandom.current().nextInt(80,181));LivingEntity b=spawnBoss(q,EntityType.RAVAGER,"MYTHIC HUNT: "+new String[]{"Ashfang","Voidclaw","Dreadhorn","Stormmaw"}[ThreadLocalRandom.current().nextInt(4)],10000);b.addScoreboardTag("esnHunt");x.sendMessage(ChatColor.LIGHT_PURPLE+"HUNT CLUE: the target is roughly "+Math.abs(q.getBlockX()-x.getLocation().getBlockX())+" blocks east/west and "+Math.abs(q.getBlockZ()-x.getLocation().getBlockZ())+" north/south.");}
 private void fusion(Player x){ItemStack a=x.getInventory().getItemInMainHand(),b=x.getInventory().getItemInOffHand();if(a==null||b==null||!a.hasItemMeta()||!b.hasItemMeta()){x.sendMessage(ChatColor.RED+"Hold generated artifacts in both hands.");return;}String ra=a.getItemMeta().getPersistentDataContainer().get(rarity,PersistentDataType.STRING),rb=b.getItemMeta().getPersistentDataContainer().get(rarity,PersistentDataType.STRING);if(ra==null||!Objects.equals(ra,rb)){x.sendMessage(ChatColor.RED+"Both items must have the same ESN rarity.");return;}String[] rs={"RARE","EPIC","LEGENDARY","MYTHIC","DIVINE","FORBIDDEN"};int at=Arrays.asList(rs).indexOf(ra);if(at<0||at==rs.length-1){x.sendMessage(ChatColor.RED+"These cannot be fused further.");return;}ItemMeta m=a.getItemMeta();m.getPersistentDataContainer().set(rarity,PersistentDataType.STRING,rs[at+1]);m.setDisplayName(ChatColor.LIGHT_PURPLE+rs[at+1]+" FUSED "+a.getType().name().replace('_',' '));a.setItemMeta(m);b.setAmount(b.getAmount()-1);x.sendMessage(ChatColor.GREEN+"Fusion succeeded: "+rs[at+1]+".");}
 private void achievements(Player x)throws Exception{try(PreparedStatement q=db.prepareStatement("SELECT k FROM achievements WHERE uuid=? LIMIT 20")){q.setString(1,x.getUniqueId().toString());try(ResultSet r=q.executeQuery()){x.sendMessage(ChatColor.AQUA+"ADVENTURE ACHIEVEMENTS");boolean any=false;while(r.next()){any=true;x.sendMessage(ChatColor.GREEN+"✓ "+r.getString(1));}if(!any)x.sendMessage(ChatColor.GRAY+"No adventure achievements yet.");}}}
 private void achievement(Player x,String k){try(PreparedStatement q=db.prepareStatement("INSERT OR IGNORE INTO achievements(uuid,k) VALUES(?,?)")){q.setString(1,x.getUniqueId().toString());q.setString(2,k);q.executeUpdate();}catch(Exception ignored){}}
 private void revive(Player x){Player best=null;double d=64;for(Player q:x.getWorld().getPlayers()){if(q==x||!downed.containsKey(q.getUniqueId()))continue;double z=q.getLocation().distanceSquared(x.getLocation());if(z<d){d=z;best=q;}}if(best==null){x.sendMessage(ChatColor.RED+"No downed teammate within 8 blocks.");return;}downed.remove(best.getUniqueId());best.setHealth(Math.min(best.getAttribute(Attribute.MAX_HEALTH).getValue(),10));best.addPotionEffect(new PotionEffect(PotionEffectType.RESISTANCE,100,2));inc(x,"reputation",10);x.sendMessage(ChatColor.GREEN+"Teammate revived! +10 reputation.");best.sendMessage(ChatColor.GREEN+x.getName()+" revived you!");}
 private void guild(Player x,String[] a)throws Exception{ensure(x);if(a.length>=2&&a[0].equalsIgnoreCase("join")){String g=a[1].replaceAll("[^A-Za-z0-9_-]","");if(g.isBlank())return;try(PreparedStatement q=db.prepareStatement("INSERT INTO guilds(uuid,guild,xp) VALUES(?,?,0) ON CONFLICT(uuid) DO UPDATE SET guild=excluded.guild")){q.setString(1,x.getUniqueId().toString());q.setString(2,g);q.executeUpdate();}x.sendMessage(ChatColor.GREEN+"Guild set to "+g+".");return;}try(PreparedStatement q=db.prepareStatement("SELECT guild,xp FROM guilds WHERE uuid=?")){q.setString(1,x.getUniqueId().toString());try(ResultSet r=q.executeQuery()){x.sendMessage(r.next()?ChatColor.GOLD+"Guild "+r.getString(1)+" | XP "+r.getInt(2):ChatColor.GRAY+"No guild. /guild join <name>");}}}
 private void trophy(Player x,String k){try{try(PreparedStatement q=db.prepareStatement("INSERT INTO trophies(uuid,k,n) VALUES(?,?,1) ON CONFLICT(uuid,k) DO UPDATE SET n=n+1")){q.setString(1,x.getUniqueId().toString());q.setString(2,k);q.executeUpdate();}}catch(Exception ignored){}}
 private void trophies(Player x)throws Exception{try(PreparedStatement q=db.prepareStatement("SELECT k,n FROM trophies WHERE uuid=? ORDER BY n DESC LIMIT 12")){q.setString(1,x.getUniqueId().toString());try(ResultSet r=q.executeQuery()){x.sendMessage(ChatColor.GOLD+"TROPHY ROOM");while(r.next())x.sendMessage(ChatColor.GRAY+r.getString(1)+": "+r.getInt(2));}}}
 private void updateRecord(String k,int v,Player x){try{try(PreparedStatement q=db.prepareStatement("INSERT INTO records(k,v,holder) VALUES(?,?,?) ON CONFLICT(k) DO UPDATE SET v=excluded.v,holder=excluded.holder WHERE excluded.v>records.v")){q.setString(1,k);q.setInt(2,v);q.setString(3,x.getName());q.executeUpdate();}}catch(Exception ignored){}}
 private void records(Player x)throws Exception{try(Statement s=db.createStatement();ResultSet r=s.executeQuery("SELECT k,v,holder FROM records ORDER BY v DESC LIMIT 15")){x.sendMessage(ChatColor.AQUA+"ESN SERVER RECORDS");while(r.next())x.sendMessage(ChatColor.GRAY+r.getString(1)+": "+r.getInt(2)+" — "+r.getString(3));}}
 private void pulse(){if(Bukkit.getOnlinePlayers().isEmpty())return;String[] es={"BLOOD_MOON","VOID_INVASION","METEOR_SHOWER","BOSS_UPRISING","TREASURE_RUSH","DOUBLE_BOSS_REWARDS","RIFT_STORM"};event=es[ThreadLocalRandom.current().nextInt(es.length)];eventEnd=System.currentTimeMillis()+15*60_000L;Bukkit.broadcastMessage(ChatColor.LIGHT_PURPLE+"ESN WORLD EVENT: "+event.replace('_',' ')+" is active for 15 minutes!");if(event.equals("BLOOD_MOON"))for(World w:Bukkit.getWorlds()){w.setTime(18000);for(LivingEntity z:w.getLivingEntities())if(z instanceof Monster){z.addPotionEffect(new PotionEffect(PotionEffectType.STRENGTH,18000,2));z.addPotionEffect(new PotionEffect(PotionEffectType.SPEED,18000,1));}}if(event.equals("VOID_INVASION"))for(Player x:Bukkit.getOnlinePlayers())spawnWave(x.getLocation(),10,"esnVoidInvasion");if(event.equals("BOSS_UPRISING")||event.equals("RIFT_STORM"))for(Player x:Bukkit.getOnlinePlayers())if(ThreadLocalRandom.current().nextDouble()<.50)startRift(x);if(event.equals("TREASURE_RUSH"))for(Player x:Bukkit.getOnlinePlayers())for(int n=0;n<3;n++){Location q=x.getLocation().clone().add(ThreadLocalRandom.current().nextInt(-70,71),0,ThreadLocalRandom.current().nextInt(-70,71));q.setY(q.getWorld().getHighestBlockYAt(q.getBlockX(),q.getBlockZ())+1);q.getWorld().dropItemNaturally(q,LootDrops.key());}if(event.equals("METEOR_SHOWER"))for(Player x:Bukkit.getOnlinePlayers())for(int n=0;n<3;n++){Location q=x.getLocation().clone().add(ThreadLocalRandom.current().nextInt(-80,81),0,ThreadLocalRandom.current().nextInt(-80,81));q.setY(q.getWorld().getHighestBlockYAt(q.getBlockX(),q.getBlockZ())+1);q.getWorld().strikeLightningEffect(q);q.getWorld().spawnParticle(Particle.EXPLOSION,q,12,3,2,3,.1);q.getWorld().dropItemNaturally(q,new ItemStack(Material.AMETHYST_SHARD,ThreadLocalRandom.current().nextInt(4,13)));}}
 public void close()throws Exception{if(db!=null)db.close();}
}