package com.esn.smp.gameplay;

import org.bukkit.*;
import org.bukkit.command.*;
import org.bukkit.entity.*;
import org.bukkit.event.*;
import org.bukkit.event.entity.EntityDeathEvent;
import org.bukkit.event.player.PlayerMoveEvent;
import org.bukkit.inventory.*;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.plugin.java.JavaPlugin;
import java.io.*;
import java.sql.*;
import java.util.*;

public final class ESNWorldProgression implements Listener,CommandExecutor,AutoCloseable {
 private static final String REALM_MENU=ChatColor.DARK_PURPLE+"Realm Rewards";private final Map<UUID,Integer> realmPage=new HashMap<>();
 private final JavaPlugin p; private final V18Core levels; private final ESN20Expansion titles; private Connection db;
 public ESNWorldProgression(JavaPlugin p,V18Core levels,ESN20Expansion titles)throws Exception{this.p=p;this.levels=levels;this.titles=titles;db=DriverManager.getConnection("jdbc:sqlite:"+new File(p.getDataFolder(),"world-progression.db"));try(Statement s=db.createStatement()){s.execute("CREATE TABLE IF NOT EXISTS player(uuid TEXT PRIMARY KEY,realm INTEGER DEFAULT 1,quest INTEGER DEFAULT 0,guild TEXT DEFAULT '')");s.execute("CREATE TABLE IF NOT EXISTS discoveries(uuid TEXT,k TEXT,PRIMARY KEY(uuid,k))");s.execute("CREATE TABLE IF NOT EXISTS guilds(name TEXT PRIMARY KEY,owner TEXT,xp INTEGER DEFAULT 0,level INTEGER DEFAULT 1,bank INTEGER DEFAULT 0)");s.execute("CREATE TABLE IF NOT EXISTS realm_claims(uuid TEXT,realm INTEGER,PRIMARY KEY(uuid,realm))");}}
 private void ensure(Player x)throws Exception{try(PreparedStatement q=db.prepareStatement("INSERT OR IGNORE INTO player(uuid) VALUES(?)")){q.setString(1,x.getUniqueId().toString());q.executeUpdate();}}
 private int val(Player x,String col)throws Exception{ensure(x);try(PreparedStatement q=db.prepareStatement("SELECT "+col+" FROM player WHERE uuid=?")){q.setString(1,x.getUniqueId().toString());try(ResultSet r=q.executeQuery()){return r.next()?r.getInt(1):0;}}}
 private String text(Player x,String col)throws Exception{ensure(x);try(PreparedStatement q=db.prepareStatement("SELECT "+col+" FROM player WHERE uuid=?")){q.setString(1,x.getUniqueId().toString());try(ResultSet r=q.executeQuery()){return r.next()?r.getString(1):"";}}}
 private void discover(Player x,String k,String label){try(PreparedStatement q=db.prepareStatement("INSERT OR IGNORE INTO discoveries(uuid,k) VALUES(?,?)")){q.setString(1,x.getUniqueId().toString());q.setString(2,k);if(q.executeUpdate()>0){x.sendMessage(ChatColor.AQUA+"✦ Journal Discovery: "+ChatColor.WHITE+label);x.playSound(x.getLocation(),Sound.ENTITY_PLAYER_LEVELUP,.5f,1.5f);guildXp(x,5);}}catch(Exception ignored){}}
 @EventHandler public void move(PlayerMoveEvent e){if(e.getTo()==null||e.getFrom().getBlockX()==e.getTo().getBlockX()&&e.getFrom().getBlockZ()==e.getTo().getBlockZ())return;Player x=e.getPlayer();discover(x,"biome:"+x.getLocation().getBlock().getBiome().name(),"Biome — "+x.getLocation().getBlock().getBiome().name().replace('_',' '));}
 @EventHandler public void death(EntityDeathEvent e){Player x=e.getEntity().getKiller();if(x==null)return;if(e.getEntity().getScoreboardTags().stream().anyMatch(t->t.toLowerCase(Locale.ROOT).contains("boss")))discover(x,"boss:"+e.getEntity().getType().name(),"Boss — "+e.getEntity().getType().name().replace('_',' '));}
 private int discoveries(Player x){try(PreparedStatement q=db.prepareStatement("SELECT COUNT(*) FROM discoveries WHERE uuid=?")){q.setString(1,x.getUniqueId().toString());try(ResultSet r=q.executeQuery()){return r.next()?r.getInt(1):0;}}catch(Exception e){return 0;}}
 private boolean realmClaimed(Player x,int realm)throws Exception{try(PreparedStatement q=db.prepareStatement("SELECT 1 FROM realm_claims WHERE uuid=? AND realm=?")){q.setString(1,x.getUniqueId().toString());q.setInt(2,realm);try(ResultSet rs=q.executeQuery()){return rs.next();}}}
 private ItemStack realmExclusive(int realm){Material[] mats={Material.NETHERITE_SWORD,Material.NETHERITE_PICKAXE,Material.NETHERITE_AXE,Material.NETHERITE_SHOVEL,Material.NETHERITE_HELMET,Material.NETHERITE_CHESTPLATE,Material.NETHERITE_LEGGINGS,Material.NETHERITE_BOOTS,Material.BOW,Material.CROSSBOW,Material.TRIDENT,Material.MACE,Material.SHIELD,Material.ELYTRA,Material.TOTEM_OF_UNDYING,Material.RECOVERY_COMPASS,Material.SPYGLASS,Material.HEART_OF_THE_SEA,Material.NETHER_STAR,Material.ECHO_SHARD};String[] n={"Realmblade","Realm Drill","Realm Cleaver","Realm Spade","Realm Crown","Realm Aegis","Realm Legguards","Realm Walkers","Realm Longbow","Realm Repeater","Realm Trident","Realmbreaker","Realmguard","Realm Wings","Realm Idol","Realm Compass","Realm Lens","Realm Heart","Realm Star","Realm Echo"};int z=(realm-1)%mats.length;ItemStack i=new ItemStack(mats[z]);ItemMeta m=i.getItemMeta();m.setDisplayName(ChatColor.GOLD+"✦ Realm "+realm+" "+n[z]+" ✦");m.setLore(List.of(ChatColor.LIGHT_PURPLE+"REALM "+realm+" EXCLUSIVE",ChatColor.GRAY+"Exclusive Realm unlock reward.",ChatColor.DARK_GRAY+"Only awarded for unlocking Realm "+realm+"."));i.setItemMeta(m);if(i.getType().getMaxDurability()>0)i.addUnsafeEnchantment(org.bukkit.enchantments.Enchantment.UNBREAKING,Math.min(200,25+realm));return i;}
 private void claimRealm(Player x,int realm)throws Exception{int unlocked=val(x,"realm");if(realm>unlocked){x.sendMessage(ChatColor.RED+"Realm "+realm+" is still locked.");return;}if(realmClaimed(x,realm)){x.sendMessage(ChatColor.YELLOW+"Realm "+realm+" exclusive already claimed.");return;}try(PreparedStatement q=db.prepareStatement("INSERT INTO realm_claims(uuid,realm) VALUES(?,?)")){q.setString(1,x.getUniqueId().toString());q.setInt(2,realm);q.executeUpdate();}ItemStack i=realmExclusive(realm);x.getInventory().addItem(i).values().forEach(z->x.getWorld().dropItemNaturally(x.getLocation(),z));x.sendMessage(ChatColor.GOLD+"Claimed Realm "+realm+" exclusive: "+i.getItemMeta().getDisplayName());openRealm(x,realmPage.getOrDefault(x.getUniqueId(),0));}
 private void openRealm(Player x,int page)throws Exception{page=Math.max(0,Math.min(5,page));realmPage.put(x.getUniqueId(),page);int unlocked=val(x,"realm");Inventory v=Bukkit.createInventory(null,54,REALM_MENU);ItemStack h=new ItemStack(Material.NETHER_STAR);ItemMeta hm=h.getItemMeta();hm.setDisplayName(ChatColor.GOLD+"Realm "+unlocked+"/100");hm.setLore(List.of(ChatColor.AQUA+"Every Realm has its own exclusive item.",ChatColor.GRAY+"Click unlocked rewards to claim them."));h.setItemMeta(hm);v.setItem(4,h);for(int j=0;j<18;j++){int realm=page*18+j+1;if(realm>100)break;ItemStack i=realmExclusive(realm);ItemMeta m=i.getItemMeta();List<String> lore=new ArrayList<>(m.getLore());boolean claimed=realmClaimed(x,realm);lore.add(claimed?ChatColor.GREEN+"CLAIMED":realm<=unlocked?ChatColor.YELLOW+"CLICK TO CLAIM":ChatColor.RED+"LOCKED");m.setLore(lore);i.setItemMeta(m);v.setItem(9+j,i);}if(page>0)v.setItem(45,named(Material.ARROW,ChatColor.YELLOW+"Previous Page"));v.setItem(49,named(Material.BARRIER,ChatColor.RED+"Close"));if(page<5)v.setItem(53,named(Material.ARROW,ChatColor.YELLOW+"Next Page"));x.openInventory(v);}
 private ItemStack named(Material mat,String name){ItemStack i=new ItemStack(mat);ItemMeta m=i.getItemMeta();m.setDisplayName(name);i.setItemMeta(m);return i;}
 private void realm(Player x,String[] a)throws Exception{int r=val(x,"realm");if(a.length>0&&a[0].equalsIgnoreCase("advance")){if(r>=100){x.sendMessage(ChatColor.GOLD+"You have mastered all 100 Realms.");return;}int level=levels==null?1:levels.chatLevel(x),need=r+1;if(level<need||discoveries(x)<Math.max(1,need/2)){x.sendMessage(ChatColor.RED+"Realm "+need+" requires ESN Level "+need+" and "+Math.max(1,need/2)+" discoveries.");return;}try(PreparedStatement q=db.prepareStatement("UPDATE player SET realm=? WHERE uuid=?")){q.setInt(1,need);q.setString(2,x.getUniqueId().toString());q.executeUpdate();}x.sendMessage(ChatColor.GOLD+"✦ REALM "+need+" UNLOCKED ✦ "+ChatColor.YELLOW+"Open /realm to claim its exclusive item.");openRealm(x,(need-1)/18);return;}openRealm(x,(Math.max(1,r)-1)/18);}
 @EventHandler public void realmMenuClick(org.bukkit.event.inventory.InventoryClickEvent e){if(!e.getView().getTitle().equals(REALM_MENU))return;e.setCancelled(true);if(!(e.getWhoClicked() instanceof Player x))return;try{int s=e.getRawSlot(),page=realmPage.getOrDefault(x.getUniqueId(),0);if(s>=9&&s<27){int realm=page*18+s-8;if(realm<=100)claimRealm(x,realm);}else if(s==45&&page>0)openRealm(x,page-1);else if(s==53&&page<5)openRealm(x,page+1);else if(s==49)x.closeInventory();}catch(Exception ex){x.sendMessage(ChatColor.RED+"Realm rewards unavailable.");}}
 private void quest(Player x)throws Exception{int q=val(x,"quest");String[] names={"The First Footsteps","Whispers Beyond Spawn","Hunter's Oath","The Broken Seal","Realmwalker"};int stage=Math.min(q,names.length-1);x.sendMessage(ChatColor.LIGHT_PURPLE+"NPC STORY: "+names[stage]);x.sendMessage(ChatColor.GRAY+(stage==0?"Discover 3 biomes.":stage==1?"Reach Realm 5.":stage==2?"Defeat a boss.":stage==3?"Reach 15 discoveries.":"Continue mastering the Realms."));boolean done=stage==0?discoveries(x)>=3:stage==1?val(x,"realm")>=5:stage==2?hasPrefix(x,"boss:"):stage==3?discoveries(x)>=15:false;if(done&&q<4){try(PreparedStatement z=db.prepareStatement("UPDATE player SET quest=quest+1 WHERE uuid=?")){z.setString(1,x.getUniqueId().toString());z.executeUpdate();}x.getInventory().addItem(MegaCrates.key(Math.min(99,(q+1)*20-1))).values().forEach(i->x.getWorld().dropItemNaturally(x.getLocation(),i));x.sendMessage(ChatColor.GREEN+"Story stage complete! A Realm crate key was awarded.");}}
 private boolean hasPrefix(Player x,String pre)throws Exception{try(PreparedStatement q=db.prepareStatement("SELECT 1 FROM discoveries WHERE uuid=? AND k LIKE ? LIMIT 1")){q.setString(1,x.getUniqueId().toString());q.setString(2,pre+"%");try(ResultSet r=q.executeQuery()){return r.next();}}}
 private void guild(Player x,String[] a)throws Exception{String g=text(x,"guild");if(a.length==0){if(g==null||g.isBlank()){x.sendMessage(ChatColor.GOLD+"/guildhq create <name>");return;}try(PreparedStatement q=db.prepareStatement("SELECT xp,level,bank FROM guilds WHERE name=?")){q.setString(1,g);try(ResultSet r=q.executeQuery()){if(r.next())x.sendMessage(ChatColor.BLUE+"Guild HQ "+g+ChatColor.GRAY+" | Level "+r.getInt("level")+" | XP "+r.getInt("xp")+" | Bank "+r.getInt("bank"));}}return;}if(a[0].equalsIgnoreCase("create")&&a.length>1){if(g!=null&&!g.isBlank()){x.sendMessage(ChatColor.RED+"You already belong to a guild.");return;}String n=String.join(" ",Arrays.copyOfRange(a,1,a.length));try(PreparedStatement q=db.prepareStatement("INSERT INTO guilds(name,owner) VALUES(?,?)")){q.setString(1,n);q.setString(2,x.getUniqueId().toString());q.executeUpdate();}try(PreparedStatement q=db.prepareStatement("UPDATE player SET guild=? WHERE uuid=?")){q.setString(1,n);q.setString(2,x.getUniqueId().toString());q.executeUpdate();}x.sendMessage(ChatColor.GREEN+"Guild HQ founded: "+n);}}
 private void guildXp(Player x,int n){try{String g=text(x,"guild");if(g==null||g.isBlank())return;try(PreparedStatement q=db.prepareStatement("UPDATE guilds SET xp=xp+?,level=MIN(25,1+(xp+?)/100) WHERE name=?")){q.setInt(1,n);q.setInt(2,n);q.setString(3,g);q.executeUpdate();}}catch(Exception ignored){}}
 public boolean onCommand(CommandSender s,Command c,String l,String[] a){if(!(s instanceof Player x))return true;try{switch(c.getName()){case"realm"->realm(x,a);case"story"->quest(x);case"discoveries"->x.sendMessage(ChatColor.AQUA+"Journal discoveries: "+discoveries(x));case"guildhq"->guild(x,a);case"titlemenu"->{x.sendMessage(ChatColor.GOLD+"Title Collection");x.sendMessage(ChatColor.GRAY+"Use /title Hunter, Slayer, Mythic or Legend. Equipped titles appear in ESN chat.");}}}catch(Exception e){x.sendMessage(ChatColor.RED+"Progression system unavailable.");p.getLogger().warning("World progression: "+e.getMessage());}return true;}
 public void close()throws Exception{if(db!=null)db.close();}
}