package com.esn.smp.gameplay;

import org.bukkit.*;
import org.bukkit.command.*;
import org.bukkit.entity.*;
import org.bukkit.event.*;
import org.bukkit.event.entity.EntityDeathEvent;
import org.bukkit.event.player.PlayerMoveEvent;
import org.bukkit.inventory.*;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.plugin.java.JavaPlugin;
import java.io.*;
import java.sql.*;
import java.util.*;

public final class ESNWorldProgression implements Listener,CommandExecutor,AutoCloseable {
 private final JavaPlugin p; private final V18Core levels; private final ESN20Expansion titles; private Connection db;
 public ESNWorldProgression(JavaPlugin p,V18Core levels,ESN20Expansion titles)throws Exception{this.p=p;this.levels=levels;this.titles=titles;db=DriverManager.getConnection("jdbc:sqlite:"+new File(p.getDataFolder(),"world-progression.db"));try(Statement s=db.createStatement()){s.execute("CREATE TABLE IF NOT EXISTS player(uuid TEXT PRIMARY KEY,realm INTEGER DEFAULT 1,quest INTEGER DEFAULT 0,guild TEXT DEFAULT '')");s.execute("CREATE TABLE IF NOT EXISTS discoveries(uuid TEXT,k TEXT,PRIMARY KEY(uuid,k))");s.execute("CREATE TABLE IF NOT EXISTS guilds(name TEXT PRIMARY KEY,owner TEXT,xp INTEGER DEFAULT 0,level INTEGER DEFAULT 1,bank INTEGER DEFAULT 0)");}}
 private void ensure(Player x)throws Exception{try(PreparedStatement q=db.prepareStatement("INSERT OR IGNORE INTO player(uuid) VALUES(?)")){q.setString(1,x.getUniqueId().toString());q.executeUpdate();}}
 private int val(Player x,String col)throws Exception{ensure(x);try(PreparedStatement q=db.prepareStatement("SELECT "+col+" FROM player WHERE uuid=?")){q.setString(1,x.getUniqueId().toString());try(ResultSet r=q.executeQuery()){return r.next()?r.getInt(1):0;}}}
 private String text(Player x,String col)throws Exception{ensure(x);try(PreparedStatement q=db.prepareStatement("SELECT "+col+" FROM player WHERE uuid=?")){q.setString(1,x.getUniqueId().toString());try(ResultSet r=q.executeQuery()){return r.next()?r.getString(1):"";}}}
 private void discover(Player x,String k,String label){try(PreparedStatement q=db.prepareStatement("INSERT OR IGNORE INTO discoveries(uuid,k) VALUES(?,?)")){q.setString(1,x.getUniqueId().toString());q.setString(2,k);if(q.executeUpdate()>0){x.sendMessage(ChatColor.AQUA+"✦ Journal Discovery: "+ChatColor.WHITE+label);x.playSound(x.getLocation(),Sound.ENTITY_PLAYER_LEVELUP,.5f,1.5f);guildXp(x,5);}}catch(Exception ignored){}}
 @EventHandler public void move(PlayerMoveEvent e){if(e.getTo()==null||e.getFrom().getBlockX()==e.getTo().getBlockX()&&e.getFrom().getBlockZ()==e.getTo().getBlockZ())return;Player x=e.getPlayer();discover(x,"biome:"+x.getLocation().getBlock().getBiome().name(),"Biome — "+x.getLocation().getBlock().getBiome().name().replace('_',' '));}
 @EventHandler public void death(EntityDeathEvent e){Player x=e.getEntity().getKiller();if(x==null)return;if(e.getEntity().getScoreboardTags().stream().anyMatch(t->t.toLowerCase(Locale.ROOT).contains("boss")))discover(x,"boss:"+e.getEntity().getType().name(),"Boss — "+e.getEntity().getType().name().replace('_',' '));}
 private int discoveries(Player x){try(PreparedStatement q=db.prepareStatement("SELECT COUNT(*) FROM discoveries WHERE uuid=?")){q.setString(1,x.getUniqueId().toString());try(ResultSet r=q.executeQuery()){return r.next()?r.getInt(1):0;}}catch(Exception e){return 0;}}
 private void realm(Player x,String[] a)throws Exception{int r=val(x,"realm");if(a.length>0&&a[0].equalsIgnoreCase("advance")){int level=levels==null?1:levels.chatLevel(x),need=Math.min(100,r+1);if(level<need||discoveries(x)<Math.max(1,need/2)){x.sendMessage(ChatColor.RED+"Realm "+need+" requires ESN Level "+need+" and "+Math.max(1,need/2)+" discoveries.");return;}try(PreparedStatement q=db.prepareStatement("UPDATE player SET realm=? WHERE uuid=?")){q.setInt(1,need);q.setString(2,x.getUniqueId().toString());q.executeUpdate();}x.sendMessage(ChatColor.GOLD+"✦ REALM "+need+" UNLOCKED ✦");return;}x.sendMessage(ChatColor.GOLD+"Realm "+r+"/100"+ChatColor.GRAY+" | Discoveries "+discoveries(x)+ChatColor.GRAY+" | Next unlock requires level/discovery mastery. /realm advance");}
 private void quest(Player x)throws Exception{int q=val(x,"quest");String[] names={"The First Footsteps","Whispers Beyond Spawn","Hunter's Oath","The Broken Seal","Realmwalker"};int stage=Math.min(q,names.length-1);x.sendMessage(ChatColor.LIGHT_PURPLE+"NPC STORY: "+names[stage]);x.sendMessage(ChatColor.GRAY+(stage==0?"Discover 3 biomes.":stage==1?"Reach Realm 5.":stage==2?"Defeat a boss.":stage==3?"Reach 15 discoveries.":"Continue mastering the Realms."));boolean done=stage==0?discoveries(x)>=3:stage==1?val(x,"realm")>=5:stage==2?hasPrefix(x,"boss:"):stage==3?discoveries(x)>=15:false;if(done&&q<4){try(PreparedStatement z=db.prepareStatement("UPDATE player SET quest=quest+1 WHERE uuid=?")){z.setString(1,x.getUniqueId().toString());z.executeUpdate();}x.getInventory().addItem(MegaCrates.key(Math.min(99,(q+1)*20-1))).values().forEach(i->x.getWorld().dropItemNaturally(x.getLocation(),i));x.sendMessage(ChatColor.GREEN+"Story stage complete! A Realm crate key was awarded.");}}
 private boolean hasPrefix(Player x,String pre)throws Exception{try(PreparedStatement q=db.prepareStatement("SELECT 1 FROM discoveries WHERE uuid=? AND k LIKE ? LIMIT 1")){q.setString(1,x.getUniqueId().toString());q.setString(2,pre+"%");try(ResultSet r=q.executeQuery()){return r.next();}}}
 private void guild(Player x,String[] a)throws Exception{String g=text(x,"guild");if(a.length==0){if(g==null||g.isBlank()){x.sendMessage(ChatColor.GOLD+"/guildhq create <name>");return;}try(PreparedStatement q=db.prepareStatement("SELECT xp,level,bank FROM guilds WHERE name=?")){q.setString(1,g);try(ResultSet r=q.executeQuery()){if(r.next())x.sendMessage(ChatColor.BLUE+"Guild HQ "+g+ChatColor.GRAY+" | Level "+r.getInt("level")+" | XP "+r.getInt("xp")+" | Bank "+r.getInt("bank"));}}return;}if(a[0].equalsIgnoreCase("create")&&a.length>1){if(g!=null&&!g.isBlank()){x.sendMessage(ChatColor.RED+"You already belong to a guild.");return;}String n=String.join(" ",Arrays.copyOfRange(a,1,a.length));try(PreparedStatement q=db.prepareStatement("INSERT INTO guilds(name,owner) VALUES(?,?)")){q.setString(1,n);q.setString(2,x.getUniqueId().toString());q.executeUpdate();}try(PreparedStatement q=db.prepareStatement("UPDATE player SET guild=? WHERE uuid=?")){q.setString(1,n);q.setString(2,x.getUniqueId().toString());q.executeUpdate();}x.sendMessage(ChatColor.GREEN+"Guild HQ founded: "+n);}}
 private void guildXp(Player x,int n){try{String g=text(x,"guild");if(g==null||g.isBlank())return;try(PreparedStatement q=db.prepareStatement("UPDATE guilds SET xp=xp+?,level=MIN(25,1+(xp+?)/100) WHERE name=?")){q.setInt(1,n);q.setInt(2,n);q.setString(3,g);q.executeUpdate();}}catch(Exception ignored){}}
 public boolean onCommand(CommandSender s,Command c,String l,String[] a){if(!(s instanceof Player x))return true;try{switch(c.getName()){case"realm"->realm(x,a);case"story"->quest(x);case"discoveries"->x.sendMessage(ChatColor.AQUA+"Journal discoveries: "+discoveries(x));case"guildhq"->guild(x,a);case"titlemenu"->{x.sendMessage(ChatColor.GOLD+"Title Collection");x.sendMessage(ChatColor.GRAY+"Use /title Hunter, Slayer, Mythic or Legend. Equipped titles appear in ESN chat.");}}}catch(Exception e){x.sendMessage(ChatColor.RED+"Progression system unavailable.");p.getLogger().warning("World progression: "+e.getMessage());}return true;}
 public void close()throws Exception{if(db!=null)db.close();}
}