package com.esn.smp.gameplay;
import com.esn.smp.data.ESNDataStore;import org.bukkit.*;import org.bukkit.block.Biome;import org.bukkit.command.*;import org.bukkit.entity.*;import org.bukkit.event.*;import org.bukkit.event.block.BlockBreakEvent;import org.bukkit.event.entity.*;import org.bukkit.event.player.*;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.ItemMeta;import org.bukkit.plugin.java.JavaPlugin;import java.io.*;import java.sql.*;import java.util.*;import java.util.concurrent.ThreadLocalRandom;
public final class ExpansionCore implements Listener,CommandExecutor,AutoCloseable{
 private final JavaPlugin p;private final ESNDataStore eco;private Connection db;private final Map<UUID,Long> joined=new HashMap<>(),lastKill=new HashMap<>();private final Set<UUID> afk=new HashSet<>();private final Map<UUID,UUID> parties=new HashMap<>();private final Map<UUID,Long> eventCd=new HashMap<>();private final Map<String,UUID> swampBosses=new HashMap<>();private UUID worldBoss;private org.bukkit.boss.BossBar worldBossBar;private int worldBossParticleTask=-1;
 public ExpansionCore(JavaPlugin p,ESNDataStore e)throws Exception{this.p=p;eco=e;db=DriverManager.getConnection("jdbc:sqlite:"+new File(p.getDataFolder(),"esnsmp-expansion.db"));try(Statement s=db.createStatement()){s.execute("CREATE TABLE IF NOT EXISTS stats(uuid TEXT PRIMARY KEY,mining INTEGER DEFAULT 0,combat INTEGER DEFAULT 0,farming INTEGER DEFAULT 0,fishing INTEGER DEFAULT 0,wood INTEGER DEFAULT 0,prestige INTEGER DEFAULT 0,playtime INTEGER DEFAULT 0,kills INTEGER DEFAULT 0,deaths INTEGER DEFAULT 0,title TEXT DEFAULT '')");s.execute("CREATE TABLE IF NOT EXISTS notes(id INTEGER PRIMARY KEY AUTOINCREMENT,target TEXT,staff TEXT,note TEXT,created INTEGER)");s.execute("CREATE TABLE IF NOT EXISTS reports(id INTEGER PRIMARY KEY AUTOINCREMENT,reporter TEXT,target TEXT,reason TEXT,created INTEGER)");s.execute("CREATE TABLE IF NOT EXISTS unlocks(uuid TEXT,key TEXT,PRIMARY KEY(uuid,key))");}Bukkit.getScheduler().runTaskTimer(p,()->spawnWorldBoss(),200L,18000L);Bukkit.getScheduler().runTaskLater(p,this::recoverBosses,40L);Bukkit.getScheduler().runTaskTimer(p,this::scanSwamps,200L,600L);}
 private void ensure(Player x)throws SQLException{try(PreparedStatement q=db.prepareStatement("INSERT OR IGNORE INTO stats(uuid) VALUES(?)")){q.setString(1,x.getUniqueId().toString());q.executeUpdate();}}
 private int get(Player x,String c)throws SQLException{ensure(x);try(PreparedStatement q=db.prepareStatement("SELECT "+c+" FROM stats WHERE uuid=?")){q.setString(1,x.getUniqueId().toString());try(ResultSet r=q.executeQuery()){return r.next()?r.getInt(1):0;}}}
 private void add(Player x,String c,int n){try{ensure(x);try(PreparedStatement q=db.prepareStatement("UPDATE stats SET "+c+"="+c+"+? WHERE uuid=?")){q.setInt(1,n);q.setString(2,x.getUniqueId().toString());q.executeUpdate();}}catch(Exception ignored){}}
 public boolean onCommand(CommandSender s,Command c,String l,String[] a){if(!(s instanceof Player x))return true;String n=c.getName();try{switch(n){
 case"jobs"->{x.sendMessage(ChatColor.GOLD+"ESN Jobs "+ChatColor.GRAY+"Miner "+get(x,"mining")+" | Hunter "+get(x,"combat")+" | Farmer "+get(x,"farming")+" | Fisher "+get(x,"fishing")+" | Lumberjack "+get(x,"wood"));}
 case"skills"->{x.sendMessage(ChatColor.AQUA+"Skills "+ChatColor.GRAY+"Mining "+get(x,"mining")+" | Combat "+get(x,"combat")+" | Farming "+get(x,"farming")+" | Fishing "+get(x,"fishing")+" | Woodcutting "+get(x,"wood"));}
 case"prestige"->{int total=get(x,"mining")+get(x,"combat")+get(x,"farming")+get(x,"fishing")+get(x,"wood");if(total<5000)x.sendMessage(ChatColor.RED+"You need 5,000 combined skill XP to prestige.");else{try(PreparedStatement q=db.prepareStatement("UPDATE stats SET mining=0,combat=0,farming=0,fishing=0,wood=0,prestige=prestige+1 WHERE uuid=?")){q.setString(1,x.getUniqueId().toString());q.executeUpdate();}x.sendMessage(ChatColor.LIGHT_PURPLE+"Prestige increased! Permanent prestige retained.");}}
 case"titles"->{x.sendMessage(ChatColor.GOLD+"Titles: [OG] [Titan] [Voidwalker] [Bounty Hunter] [Veteran] — earned through ESN progression.");}
 case"collections","bestiary"->{x.sendMessage(ChatColor.GREEN+"Collection progress is tracked through mining, farming, fishing and combat skills.");}
 case"stats"->{x.sendMessage(ChatColor.GOLD+"Career: "+get(x,"kills")+" kills | "+get(x,"deaths")+" deaths | Prestige "+get(x,"prestige")+" | "+get(x,"playtime")+" minutes");}
 case"afk"->{if(!afk.add(x.getUniqueId()))afk.remove(x.getUniqueId());x.sendMessage(ChatColor.YELLOW+"AFK "+(afk.contains(x.getUniqueId())?"enabled":"disabled")+"; progression while AFK is disabled.");}
 case"calendar"->{x.sendMessage(ChatColor.LIGHT_PURPLE+"ESN Calendar: Day=Mining Rush | Night=Hunt Rush | rotating world events can trigger every hour.");}
 case"blacksmith"->{x.sendMessage(ChatColor.GOLD+"ESN Blacksmith: /upgrade improves gear, /salvage converts gear to XP, /reforge rerolls a gear enchant.");}
 case"salvage"->{ItemStack it=x.getInventory().getItemInMainHand();if(it.getType().isAir()){x.sendMessage(ChatColor.RED+"Hold an item to salvage.");break;}int value=Math.max(1,it.getAmount()*5);x.getInventory().setItemInMainHand(null);x.giveExp(value);x.sendMessage(ChatColor.GREEN+"Salvaged for "+value+" XP.");}
 case"reforge"->{ItemStack it=x.getInventory().getItemInMainHand();if(it.getType().isAir()){x.sendMessage(ChatColor.RED+"Hold gear to reforge.");break;}long cost=750;if(!eco.withdraw(x,cost)){x.sendMessage(ChatColor.RED+"You need 750 ESN Coins.");break;}var ench=List.of(org.bukkit.enchantments.Enchantment.UNBREAKING,org.bukkit.enchantments.Enchantment.EFFICIENCY,org.bukkit.enchantments.Enchantment.SHARPNESS);var en=ench.get(ThreadLocalRandom.current().nextInt(ench.size()));try{it.addUnsafeEnchantment(en,1+ThreadLocalRandom.current().nextInt(3));x.sendMessage(ChatColor.LIGHT_PURPLE+"Reforged with "+en.getKey().getKey()+".");}catch(Exception z){eco.deposit(x,cost);x.sendMessage(ChatColor.RED+"That item cannot be reforged; coins refunded.");}}
 case"party"->{if(a.length==0){x.sendMessage(ChatColor.GOLD+"Party: "+(parties.containsKey(x.getUniqueId())?"active":"none")+" | /party invite <player> | /party leave");break;}if(a[0].equalsIgnoreCase("invite")&&a.length>1){Player y=PlayerResolver.online(a[1]);if(y==null){x.sendMessage(ChatColor.RED+"Player not found.");break;}UUID leader=parties.getOrDefault(x.getUniqueId(),x.getUniqueId());parties.put(x.getUniqueId(),leader);parties.put(y.getUniqueId(),leader);y.sendMessage(ChatColor.GREEN+"Joined "+x.getName()+"'s party.");x.sendMessage(ChatColor.GREEN+"Player added to party.");}else if(a[0].equalsIgnoreCase("leave")){parties.remove(x.getUniqueId());x.sendMessage(ChatColor.YELLOW+"Left party.");}}
 case"boss"->{if(a.length>0&&a[0].equalsIgnoreCase("world")){if(!x.hasPermission("esnsmp.admin")){x.sendMessage(ChatColor.RED+"You need esnsmp.admin to spawn a world boss.");break;}spawnWorldBoss(x);break;}Biome b=x.getLocation().getBlock().getBiome();if(!isSwamp(b)){x.sendMessage(ChatColor.RED+"Regional bosses only exist in swamps.");break;}spawnSwampBoss(x.getLocation());}
 case"dungeon"->{if(!eventReady(x))break;spawnWave(x,8);x.sendMessage(ChatColor.GOLD+"Dungeon wave started. Defeat the empowered mobs.");}
 case"raid"->{if(!eventReady(x))break;spawnWave(x,16);x.sendMessage(ChatColor.RED+"ESN Raid started: 16 empowered enemies incoming!");}
 case"koth"->{Location z=x.getLocation();Bukkit.broadcastMessage(ChatColor.GOLD+"KOTH activated near "+x.getName()+" at "+z.getBlockX()+", "+z.getBlockZ()+". Hold the area for 60 seconds!");Bukkit.getScheduler().runTaskLater(p,()->{if(x.isOnline()&&x.getLocation().distanceSquared(z)<225){try{eco.deposit(x,1000);}catch(Exception ignored){}x.sendMessage(ChatColor.GREEN+"KOTH won: +1,000 Coins!");}},1200L);}
 case"report"->{if(a.length<2){x.sendMessage(ChatColor.RED+"/report <player> <reason>");break;}OfflinePlayer t=PlayerResolver.offline(a[0]);try(PreparedStatement q=db.prepareStatement("INSERT INTO reports(reporter,target,reason,created) VALUES(?,?,?,?)")){q.setString(1,x.getUniqueId().toString());q.setString(2,t.getUniqueId().toString());q.setString(3,String.join(" ",Arrays.copyOfRange(a,1,a.length)));q.setLong(4,System.currentTimeMillis());q.executeUpdate();}x.sendMessage(ChatColor.GREEN+"Report submitted to ESN staff.");}
 case"note"->{if(!x.hasPermission("esnsmp.staff"))break;if(a.length<2){x.sendMessage(ChatColor.RED+"/note <player> <note>");break;}OfflinePlayer t=PlayerResolver.offline(a[0]);try(PreparedStatement q=db.prepareStatement("INSERT INTO notes(target,staff,note,created) VALUES(?,?,?,?)")){q.setString(1,t.getUniqueId().toString());q.setString(2,x.getUniqueId().toString());q.setString(3,String.join(" ",Arrays.copyOfRange(a,1,a.length)));q.setLong(4,System.currentTimeMillis());q.executeUpdate();}x.sendMessage(ChatColor.GREEN+"Staff note saved.");}
 default->x.sendMessage(ChatColor.GOLD+"ESN system ready.");}}catch(Exception z){x.sendMessage(ChatColor.RED+"System temporarily unavailable.");p.getLogger().warning(n+": "+z.getMessage());}return true;}
 @EventHandler public void join(PlayerJoinEvent e){joined.put(e.getPlayer().getUniqueId(),System.currentTimeMillis());try{ensure(e.getPlayer());if(!e.getPlayer().hasPlayedBefore()){e.getPlayer().sendMessage(ChatColor.GOLD+"Welcome to ESN SMP! Use /tutorial to begin.");e.getPlayer().setMetadata("esnNewProtection",new org.bukkit.metadata.FixedMetadataValue(p,System.currentTimeMillis()+1800000L));}}catch(Exception ignored){}}
 @EventHandler public void quit(PlayerQuitEvent e){Long j=joined.remove(e.getPlayer().getUniqueId());if(j!=null)add(e.getPlayer(),"playtime",(int)((System.currentTimeMillis()-j)/60000));}
 @EventHandler public void mine(BlockBreakEvent e){Player x=e.getPlayer();if(afk.contains(x.getUniqueId()))return;Material m=e.getBlock().getType();if(m.name().contains("LOG")||m.name().contains("WOOD"))add(x,"wood",1);else if(m.name().contains("WHEAT")||m.name().contains("CARROT")||m.name().contains("POTATO")||m.name().contains("BEETROOT"))add(x,"farming",1);else add(x,"mining",1);}
 @EventHandler public void fish(PlayerFishEvent e){if(e.getState()==PlayerFishEvent.State.CAUGHT_FISH&&!afk.contains(e.getPlayer().getUniqueId()))add(e.getPlayer(),"fishing",5);}
 @EventHandler public void kill(EntityDeathEvent e){Player x=e.getEntity().getKiller();if(x==null||afk.contains(x.getUniqueId()))return;add(x,"combat",e.getEntity() instanceof Player?20:2);if(e.getEntity() instanceof Player){add(x,"kills",1);long now=System.currentTimeMillis();Long last=lastKill.put(x.getUniqueId(),now);if(last!=null&&now-last<15000)x.sendMessage(ChatColor.RED+"Rapid repeated PvP kills are monitored for farming.");}if(ThreadLocalRandom.current().nextDouble()<.002)Bukkit.broadcastMessage(ChatColor.LIGHT_PURPLE+"A rare ESN world-event signal was discovered by "+x.getName()+"!");}
 @EventHandler public void death(PlayerDeathEvent e){add(e.getEntity(),"deaths",1);}
 private boolean eventReady(Player x){long now=System.currentTimeMillis();if(eventCd.getOrDefault(x.getUniqueId(),0L)>now){x.sendMessage(ChatColor.RED+"That event is on cooldown.");return false;}eventCd.put(x.getUniqueId(),now+300000);return true;}
 private void spawnWave(Player x,int count){for(int i=0;i<count;i++){Location l=x.getLocation().clone().add(ThreadLocalRandom.current().nextInt(-8,9),1,ThreadLocalRandom.current().nextInt(-8,9));Zombie z=(Zombie)x.getWorld().spawnEntity(l,EntityType.ZOMBIE);z.setCustomName(ChatColor.RED+"ESN Raider");z.setCustomNameVisible(true);z.getAttribute(org.bukkit.attribute.Attribute.MAX_HEALTH).setBaseValue(40);z.setHealth(40);z.addScoreboardTag("esnRaid");}}
 @EventHandler public void specialDrop(EntityDeathEvent e){Set<String> tags=e.getEntity().getScoreboardTags();Player k=e.getEntity().getKiller();if(tags.contains("esnWorldBoss")){worldBoss=null;clearWorldBossUI();if(k!=null){try{eco.deposit(k,25000);}catch(Exception ignored){}e.getDrops().add(LootDrops.key());e.getDrops().add(LootDrops.key());e.getDrops().add(LootDrops.abyssKey());e.getDrops().add(LootDrops.dragonKey());e.getDrops().add(CustomItems.cosmicCore());e.getDrops().add(CustomItems.celestialCrystal());Bukkit.broadcastMessage(ChatColor.GOLD+k.getName()+" defeated the WORLD BOSS: +25,000 Coins, 4 keys and rare materials!");}}else if(tags.contains("esnSwampBoss")){swampBosses.values().remove(e.getEntity().getUniqueId());if(k!=null){try{eco.deposit(k,10000);}catch(Exception ignored){}e.getDrops().add(LootDrops.abyssKey());e.getDrops().add(LootDrops.dragonKey());e.getDrops().add(CustomItems.voidShard());e.getDrops().add(CustomItems.titanFragment());k.sendMessage(ChatColor.GOLD+"Swamp boss reward: 10,000 Coins + themed keys + rare materials!");}}else if(tags.contains("esnRaid")&&ThreadLocalRandom.current().nextDouble()<.20)e.getDrops().add(LootDrops.key());}
 private boolean isSwamp(Biome b){return b==Biome.SWAMP||b==Biome.MANGROVE_SWAMP;}
 private String swampId(Location l){return l.getWorld().getUID()+":"+Math.floorDiv(l.getBlockX(),256)+":"+Math.floorDiv(l.getBlockZ(),256);}
 private void scanSwamps(){for(Player x:Bukkit.getOnlinePlayers())if(isSwamp(x.getLocation().getBlock().getBiome()))spawnSwampBoss(x.getLocation());}
 private void spawnSwampBoss(Location l){String base=swampId(l);EntityType[] types={EntityType.WITHER_SKELETON,EntityType.RAVAGER,EntityType.WARDEN,EntityType.ELDER_GUARDIAN,EntityType.HUSK,EntityType.DROWNED,EntityType.PIGLIN_BRUTE,EntityType.VINDICATOR};String[] names={"Bog Reaper","Mire Colossus","Swamp Warden","Drowned Ancient","Rot King","Fen Stalker","Marsh Brute","Mire Executioner"};for(int slot=0;slot<4;slot++){String id=base+"#"+slot;UUID old=swampBosses.get(id);if(old!=null&&Bukkit.getEntity(old)!=null)continue;int n=Math.floorMod(base.hashCode()+slot,types.length);Location q=l.clone().add(6+(slot%2)*8,1,6+(slot/2)*8);int y=l.getWorld().getHighestBlockYAt(q.getBlockX(),q.getBlockZ())+1;q.setY(y);LivingEntity z=(LivingEntity)l.getWorld().spawnEntity(q,types[n]);z.setCustomName(ChatColor.DARK_GREEN+"ESN "+names[n]);z.setCustomNameVisible(true);var max=z.getAttribute(org.bukkit.attribute.Attribute.MAX_HEALTH);if(max==null){z.remove();continue;}double hp=Math.min(1000,max.getDefaultValue()*8);max.setBaseValue(hp);z.setHealth(hp);z.addScoreboardTag("esnSwampBoss");z.addScoreboardTag("esnSwampSlot"+slot);z.addScoreboardTag("esnDesign"+(n%4));designBoss(z,n%4,false);swampBosses.put(id,z.getUniqueId());Bukkit.broadcastMessage(ChatColor.DARK_GREEN+"A "+names[n]+" has claimed part of the swamp! Boss "+(slot+1)+"/4.");}}
 private void recoverBosses(){for(World w:Bukkit.getWorlds())for(LivingEntity e:w.getLivingEntities())if(e.getScoreboardTags().contains("esnWorldBoss")){if(worldBoss==null)worldBoss=e.getUniqueId();else e.remove();}if(worldBoss!=null&&Bukkit.getEntity(worldBoss)!=null)attachWorldBoss((LivingEntity)Bukkit.getEntity(worldBoss));}
 private void spawnWorldBoss(){spawnWorldBoss(null);} private void spawnWorldBoss(Player requester){if(Bukkit.getOnlinePlayers().isEmpty()){if(requester!=null)requester.sendMessage(ChatColor.RED+"World boss could not spawn: no players are online.");return;}if(worldBoss!=null){Entity current=Bukkit.getEntity(worldBoss);if(current!=null&&current.isValid()){if(requester!=null){requester.sendMessage(ChatColor.YELLOW+"A world boss is already active at "+current.getWorld().getName()+" "+current.getLocation().getBlockX()+", "+current.getLocation().getBlockY()+", "+current.getLocation().getBlockZ()+".");requester.setCompassTarget(current.getLocation());}return;}worldBoss=null;}World w=Bukkit.getWorlds().stream().filter(q->q.getEnvironment()==World.Environment.NORMAL).findFirst().orElse(Bukkit.getWorlds().get(0));Location base=w.getSpawnLocation().clone().add(8,0,8);int safeY=w.getHighestBlockYAt(base.getBlockX(),base.getBlockZ())+1;Location l=new Location(w,base.getBlockX()+0.5,safeY,base.getBlockZ()+0.5);for(int radius=0;radius<=32&&(!l.getBlock().isPassable()||!l.clone().add(0,1,0).getBlock().isPassable());radius+=4){int x=base.getBlockX()+radius,zx=base.getBlockZ();int y=w.getHighestBlockYAt(x,zx)+1;l=new Location(w,x+0.5,y,zx+0.5);}EntityType[] types={EntityType.WITHER,EntityType.WARDEN,EntityType.RAVAGER,EntityType.ELDER_GUARDIAN,EntityType.IRON_GOLEM,EntityType.PIGLIN_BRUTE,EntityType.VINDICATOR,EntityType.EVOKER};String[] names={"Void Tyrant","Titan Prime","Dragon Herald","Cosmic Devourer","Astral Juggernaut","Nether Warlord","Eclipse Executioner","Arcane Sovereign"};int n=ThreadLocalRandom.current().nextInt(types.length);LivingEntity z=(LivingEntity)w.spawnEntity(l,types[n]);z.setCustomName(ChatColor.DARK_PURPLE+"WORLD BOSS: "+names[n]);z.setCustomNameVisible(true);double hp=10000.0;var max=z.getAttribute(org.bukkit.attribute.Attribute.MAX_HEALTH);if(max==null){z.remove();p.getLogger().severe("World boss type "+types[n]+" has no MAX_HEALTH attribute.");return;}max.setBaseValue(hp);z.setHealth(hp);z.addScoreboardTag("esnWorldBoss");z.addScoreboardTag("esnDesign"+(4+n%4));designBoss(z,4+n%4,true);worldBoss=z.getUniqueId();attachWorldBoss(z);Bukkit.broadcastMessage(ChatColor.RED+"WORLD BOSS "+names[n]+" spawned at WORLD SPAWN! You have 10 minutes!");if(requester!=null){requester.sendMessage(ChatColor.GREEN+"World boss spawned at "+w.getName()+" "+l.getBlockX()+", "+l.getBlockY()+", "+l.getBlockZ()+". Compass target updated.");requester.setCompassTarget(l);}UUID id=z.getUniqueId();Bukkit.getScheduler().runTaskLater(p,()->{Entity e=Bukkit.getEntity(id);if(e!=null&&e.isValid()){e.remove();if(id.equals(worldBoss)){worldBoss=null;clearWorldBossUI();}Bukkit.broadcastMessage(ChatColor.RED+"The world boss escaped.");}},12000L);}
 private void attachWorldBoss(LivingEntity z){clearWorldBossUI();worldBossBar=Bukkit.createBossBar(z.getCustomName()==null?"ESN WORLD BOSS":z.getCustomName(),org.bukkit.boss.BarColor.PURPLE,org.bukkit.boss.BarStyle.SEGMENTED_10);for(Player q:Bukkit.getOnlinePlayers())worldBossBar.addPlayer(q);worldBossParticleTask=Bukkit.getScheduler().scheduleSyncRepeatingTask(p,()->{if(!z.isValid()||z.isDead()){clearWorldBossUI();return;}if(worldBossBar!=null){worldBossBar.setProgress(Math.max(0,Math.min(1,z.getHealth()/z.getAttribute(org.bukkit.attribute.Attribute.MAX_HEALTH).getValue())));for(Player q:Bukkit.getOnlinePlayers())if(!worldBossBar.getPlayers().contains(q))worldBossBar.addPlayer(q);}},1L,10L);} private void clearWorldBossUI(){if(worldBossBar!=null){worldBossBar.removeAll();worldBossBar=null;}if(worldBossParticleTask!=-1){Bukkit.getScheduler().cancelTask(worldBossParticleTask);worldBossParticleTask=-1;}}
 private void designBoss(LivingEntity z,int d,boolean world){z.setGlowing(true);z.setPersistent(true);if(z instanceof Mob m)m.setRemoveWhenFarAway(false);if(z.getEquipment()!=null){ItemStack head=new ItemStack(new Material[]{Material.MOSS_BLOCK,Material.CARVED_PUMPKIN,Material.SCULK,Material.PRISMARINE,Material.CRYING_OBSIDIAN,Material.NETHERITE_BLOCK,Material.DRAGON_HEAD,Material.AMETHYST_BLOCK}[d]);z.getEquipment().setHelmet(head);if(z instanceof Zombie||z instanceof Skeleton){ItemStack hand=new ItemStack(d%2==0?Material.NETHERITE_AXE:Material.NETHERITE_SWORD);ItemMeta hm=hand.getItemMeta();hm.addEnchant(org.bukkit.enchantments.Enchantment.SHARPNESS,45+d,true);hand.setItemMeta(hm);z.getEquipment().setItemInMainHand(hand);}}Particle particle=new Particle[]{Particle.SPORE_BLOSSOM_AIR,Particle.COMPOSTER,Particle.SCULK_SOUL,Particle.NAUTILUS,Particle.PORTAL,Particle.FLAME,Particle.DRAGON_BREATH,Particle.END_ROD}[d];final int[] task={-1};task[0]=Bukkit.getScheduler().scheduleSyncRepeatingTask(p,()->{if(!z.isValid()||z.isDead()){Bukkit.getScheduler().cancelTask(task[0]);return;}z.getWorld().spawnParticle(particle,z.getLocation().add(0,1,0),world?35:18,0.8,1,0.8,0.02);},1L,10L);}
 @EventHandler public void bossHit(EntityDamageByEntityEvent e){if(!(e.getEntity() instanceof LivingEntity z))return;int d=-1;for(String t:z.getScoreboardTags())if(t.startsWith("esnDesign"))try{d=Integer.parseInt(t.substring(9));}catch(Exception ignored){}if(d<0)return;LivingEntity a=e.getDamager() instanceof LivingEntity q?q:null;if(a==null&&e.getDamager() instanceof Projectile pr&&pr.getShooter() instanceof LivingEntity q)a=q;if(a==null)return;switch(d){case 0->a.addPotionEffect(new org.bukkit.potion.PotionEffect(org.bukkit.potion.PotionEffectType.POISON,80,1));case 1->a.setVelocity(a.getLocation().toVector().subtract(z.getLocation().toVector()).normalize().multiply(1.4));case 2->a.addPotionEffect(new org.bukkit.potion.PotionEffect(org.bukkit.potion.PotionEffectType.DARKNESS,100,0));case 3->a.addPotionEffect(new org.bukkit.potion.PotionEffect(org.bukkit.potion.PotionEffectType.SLOWNESS,80,2));case 4->a.teleport(z.getLocation().clone().add(ThreadLocalRandom.current().nextInt(-4,5),0,ThreadLocalRandom.current().nextInt(-4,5)));case 5->a.setFireTicks(100);case 6->a.getWorld().strikeLightningEffect(a.getLocation());case 7->{a.addPotionEffect(new org.bukkit.potion.PotionEffect(org.bukkit.potion.PotionEffectType.LEVITATION,50,1));a.addPotionEffect(new org.bukkit.potion.PotionEffect(org.bukkit.potion.PotionEffectType.GLOWING,100,0));}}}
 @EventHandler public void pvp(EntityDamageByEntityEvent e){if(e.getEntity() instanceof Player v&&v.hasMetadata("esnNewProtection")){long until=v.getMetadata("esnNewProtection").get(0).asLong();if(System.currentTimeMillis()<until){e.setCancelled(true);if(e.getDamager() instanceof Player a)a.sendMessage(ChatColor.YELLOW+"That new player has temporary PvP protection.");}else v.removeMetadata("esnNewProtection",p);}}
 public void close()throws Exception{clearWorldBossUI();if(db!=null)db.close();}
}