package com.esn.smp.gameplay;
import com.esn.smp.data.ESNDataStore;import org.bukkit.*;import org.bukkit.command.*;import org.bukkit.entity.*;import org.bukkit.event.*;import org.bukkit.event.block.BlockBreakEvent;import org.bukkit.event.entity.*;import org.bukkit.event.player.*;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.ItemMeta;import org.bukkit.plugin.java.JavaPlugin;import java.io.*;import java.sql.*;import java.util.*;import java.util.concurrent.ThreadLocalRandom;
public final class ExpansionCore implements Listener,CommandExecutor,AutoCloseable{
 private final JavaPlugin p;private final ESNDataStore eco;private Connection db;private final Map<UUID,Long> joined=new HashMap<>(),lastKill=new HashMap<>();private final Set<UUID> afk=new HashSet<>();
 public ExpansionCore(JavaPlugin p,ESNDataStore e)throws Exception{this.p=p;eco=e;db=DriverManager.getConnection("jdbc:sqlite:"+new File(p.getDataFolder(),"esnsmp-expansion.db"));try(Statement s=db.createStatement()){s.execute("CREATE TABLE IF NOT EXISTS stats(uuid TEXT PRIMARY KEY,mining INTEGER DEFAULT 0,combat INTEGER DEFAULT 0,farming INTEGER DEFAULT 0,fishing INTEGER DEFAULT 0,wood INTEGER DEFAULT 0,prestige INTEGER DEFAULT 0,playtime INTEGER DEFAULT 0,kills INTEGER DEFAULT 0,deaths INTEGER DEFAULT 0,title TEXT DEFAULT '')");s.execute("CREATE TABLE IF NOT EXISTS notes(id INTEGER PRIMARY KEY AUTOINCREMENT,target TEXT,staff TEXT,note TEXT,created INTEGER)");s.execute("CREATE TABLE IF NOT EXISTS reports(id INTEGER PRIMARY KEY AUTOINCREMENT,reporter TEXT,target TEXT,reason TEXT,created INTEGER)");}}
 private void ensure(Player x)throws SQLException{try(PreparedStatement q=db.prepareStatement("INSERT OR IGNORE INTO stats(uuid) VALUES(?)")){q.setString(1,x.getUniqueId().toString());q.executeUpdate();}}
 private int get(Player x,String c)throws SQLException{ensure(x);try(PreparedStatement q=db.prepareStatement("SELECT "+c+" FROM stats WHERE uuid=?")){q.setString(1,x.getUniqueId().toString());try(ResultSet r=q.executeQuery()){return r.next()?r.getInt(1):0;}}}
 private void add(Player x,String c,int n){try{ensure(x);try(PreparedStatement q=db.prepareStatement("UPDATE stats SET "+c+"="+c+"+? WHERE uuid=?")){q.setInt(1,n);q.setString(2,x.getUniqueId().toString());q.executeUpdate();}}catch(Exception ignored){}}
 public boolean onCommand(CommandSender s,Command c,String l,String[] a){if(!(s instanceof Player x))return true;String n=c.getName();try{switch(n){
 case"jobs"->{x.sendMessage(ChatColor.GOLD+"ESN Jobs "+ChatColor.GRAY+"Miner "+get(x,"mining")+" | Hunter "+get(x,"combat")+" | Farmer "+get(x,"farming")+" | Fisher "+get(x,"fishing")+" | Lumberjack "+get(x,"wood"));}
 case"skills"->{x.sendMessage(ChatColor.AQUA+"Skills "+ChatColor.GRAY+"Mining "+get(x,"mining")+" | Combat "+get(x,"combat")+" | Farming "+get(x,"farming")+" | Fishing "+get(x,"fishing")+" | Woodcutting "+get(x,"wood"));}
 case"prestige"->{int total=get(x,"mining")+get(x,"combat")+get(x,"farming")+get(x,"fishing")+get(x,"wood");if(total<5000)x.sendMessage(ChatColor.RED+"You need 5,000 combined skill XP to prestige.");else{try(PreparedStatement q=db.prepareStatement("UPDATE stats SET mining=0,combat=0,farming=0,fishing=0,wood=0,prestige=prestige+1 WHERE uuid=?")){q.setString(1,x.getUniqueId().toString());q.executeUpdate();}x.sendMessage(ChatColor.LIGHT_PURPLE+"Prestige increased! Permanent prestige retained.");}}
 case"titles"->{x.sendMessage(ChatColor.GOLD+"Titles: [OG] [Titan] [Voidwalker] [Bounty Hunter] [Veteran] — earned through ESN progression.");}
 case"collections","bestiary"->{x.sendMessage(ChatColor.GREEN+"Collection progress is tracked through mining, farming, fishing and combat skills.");}
 case"stats"->{x.sendMessage(ChatColor.GOLD+"Career: "+get(x,"kills")+" kills | "+get(x,"deaths")+" deaths | Prestige "+get(x,"prestige")+" | "+get(x,"playtime")+" minutes");}
 case"afk"->{if(!afk.add(x.getUniqueId()))afk.remove(x.getUniqueId());x.sendMessage(ChatColor.YELLOW+"AFK "+(afk.contains(x.getUniqueId())?"enabled":"disabled")+"; progression while AFK is disabled.");}
 case"calendar"->{x.sendMessage(ChatColor.LIGHT_PURPLE+"ESN Calendar: Day=Mining Rush | Night=Hunt Rush | rotating world events can trigger every hour.");}
 case"blacksmith","salvage","reforge"->{x.sendMessage(ChatColor.GOLD+"Blacksmith: hold custom gear. /upgrade improves it; salvage/reforge materials arrive with the next custom-item batch.");}
 case"boss","dungeon","raid","party","koth"->{x.sendMessage(ChatColor.RED+"ESN "+n.toUpperCase()+" queue registered. Event content/rewards use the upcoming custom-item and crate batch.");}
 case"report"->{if(a.length<2){x.sendMessage(ChatColor.RED+"/report <player> <reason>");break;}OfflinePlayer t=PlayerResolver.offline(a[0]);try(PreparedStatement q=db.prepareStatement("INSERT INTO reports(reporter,target,reason,created) VALUES(?,?,?,?)")){q.setString(1,x.getUniqueId().toString());q.setString(2,t.getUniqueId().toString());q.setString(3,String.join(" ",Arrays.copyOfRange(a,1,a.length)));q.setLong(4,System.currentTimeMillis());q.executeUpdate();}x.sendMessage(ChatColor.GREEN+"Report submitted to ESN staff.");}
 case"note"->{if(!x.hasPermission("esnsmp.staff"))break;if(a.length<2){x.sendMessage(ChatColor.RED+"/note <player> <note>");break;}OfflinePlayer t=PlayerResolver.offline(a[0]);try(PreparedStatement q=db.prepareStatement("INSERT INTO notes(target,staff,note,created) VALUES(?,?,?,?)")){q.setString(1,t.getUniqueId().toString());q.setString(2,x.getUniqueId().toString());q.setString(3,String.join(" ",Arrays.copyOfRange(a,1,a.length)));q.setLong(4,System.currentTimeMillis());q.executeUpdate();}x.sendMessage(ChatColor.GREEN+"Staff note saved.");}
 default->x.sendMessage(ChatColor.GOLD+"ESN system ready.");}}catch(Exception z){x.sendMessage(ChatColor.RED+"System temporarily unavailable.");p.getLogger().warning(n+": "+z.getMessage());}return true;}
 @EventHandler public void join(PlayerJoinEvent e){joined.put(e.getPlayer().getUniqueId(),System.currentTimeMillis());try{ensure(e.getPlayer());if(!e.getPlayer().hasPlayedBefore()){e.getPlayer().sendMessage(ChatColor.GOLD+"Welcome to ESN SMP! Use /tutorial to begin.");e.getPlayer().setMetadata("esnNewProtection",new org.bukkit.metadata.FixedMetadataValue(p,System.currentTimeMillis()+1800000L));}}catch(Exception ignored){}}
 @EventHandler public void quit(PlayerQuitEvent e){Long j=joined.remove(e.getPlayer().getUniqueId());if(j!=null)add(e.getPlayer(),"playtime",(int)((System.currentTimeMillis()-j)/60000));}
 @EventHandler public void mine(BlockBreakEvent e){Player x=e.getPlayer();if(afk.contains(x.getUniqueId()))return;Material m=e.getBlock().getType();if(m.name().contains("LOG")||m.name().contains("WOOD"))add(x,"wood",1);else if(m.name().contains("WHEAT")||m.name().contains("CARROT")||m.name().contains("POTATO")||m.name().contains("BEETROOT"))add(x,"farming",1);else add(x,"mining",1);}
 @EventHandler public void fish(PlayerFishEvent e){if(e.getState()==PlayerFishEvent.State.CAUGHT_FISH&&!afk.contains(e.getPlayer().getUniqueId()))add(e.getPlayer(),"fishing",5);}
 @EventHandler public void kill(EntityDeathEvent e){Player x=e.getEntity().getKiller();if(x==null||afk.contains(x.getUniqueId()))return;add(x,"combat",e.getEntity() instanceof Player?20:2);if(e.getEntity() instanceof Player){add(x,"kills",1);long now=System.currentTimeMillis();Long last=lastKill.put(x.getUniqueId(),now);if(last!=null&&now-last<15000)x.sendMessage(ChatColor.RED+"Rapid repeated PvP kills are monitored for farming.");}if(ThreadLocalRandom.current().nextDouble()<.002)Bukkit.broadcastMessage(ChatColor.LIGHT_PURPLE+"A rare ESN world-event signal was discovered by "+x.getName()+"!");}
 @EventHandler public void death(PlayerDeathEvent e){add(e.getEntity(),"deaths",1);}
 @EventHandler public void pvp(EntityDamageByEntityEvent e){if(e.getEntity() instanceof Player v&&v.hasMetadata("esnNewProtection")){long until=v.getMetadata("esnNewProtection").get(0).asLong();if(System.currentTimeMillis()<until){e.setCancelled(true);if(e.getDamager() instanceof Player a)a.sendMessage(ChatColor.YELLOW+"That new player has temporary PvP protection.");}else v.removeMetadata("esnNewProtection",p);}}
 public void close()throws Exception{if(db!=null)db.close();}
}