package com.esn.smp.gameplay;
import org.bukkit.*;import org.bukkit.attribute.Attribute;import org.bukkit.enchantments.Enchantment;import org.bukkit.entity.*;import org.bukkit.event.*;import org.bukkit.event.entity.*;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.ItemMeta;import org.bukkit.persistence.*;import java.util.*;import java.util.concurrent.ThreadLocalRandom;
public final class ExtendedCrates implements Listener{
 public static final String[] LOW={"Wooden","Stonebound","Rustic","Bronze","Ironbound","Emerald","Obsidian"};
 public static final String[] HIGH={"Nova","Quantum","Celestial Prime","Transcendent","Singularity","Infinity","Eternity","Omniversal","Godforge","Absolute"};
 private static final Material[] LOWICON={Material.OAK_PLANKS,Material.STONE,Material.COPPER_INGOT,Material.BRICK,Material.IRON_INGOT,Material.EMERALD,Material.OBSIDIAN};
 private static final Material[] HIGHICON={Material.FIREWORK_STAR,Material.ENDER_EYE,Material.NETHER_STAR,Material.TOTEM_OF_UNDYING,Material.END_CRYSTAL,Material.DRAGON_EGG,Material.BEACON,Material.RESPAWN_ANCHOR,Material.HEAVY_CORE,Material.NETHERITE_BLOCK};
 private static NamespacedKey k(String s){return new NamespacedKey("esnsmp",s);}
 public static ItemStack key(boolean high,int t){Material mat=(high?HIGHICON:LOWICON)[t];String name=(high?HIGH:LOW)[t];ItemStack i=new ItemStack(mat);ItemMeta m=i.getItemMeta();m.setDisplayName((high?ChatColor.DARK_PURPLE:ChatColor.GREEN)+name+" Crate Key");m.setLore(List.of(ChatColor.GRAY+(high?"Post-Omega":"Starter")+" crate key"));m.getPersistentDataContainer().set(k("extended_key"),PersistentDataType.STRING,high?"H"+t:new String[]{"W","S","L0","L1","L2","L3","L4"}[t]);i.setItemMeta(m);return i;}
 public static boolean isKey(ItemStack i,boolean high,int t){if(i==null||!i.hasItemMeta())return false;String v=i.getItemMeta().getPersistentDataContainer().get(k("extended_key"),PersistentDataType.STRING);if(high)return ("H"+t).equals(v);String stable=new String[]{"W","S","L0","L1","L2","L3","L4"}[t];if(stable.equals(v))return true;return t>=2&&("L"+(t-2)).equals(v);}
 public static ItemStack item(boolean high,int t,int slot){Material[] mats={Material.NETHERITE_SWORD,Material.NETHERITE_AXE,Material.NETHERITE_PICKAXE,Material.NETHERITE_SHOVEL,Material.NETHERITE_HOE,Material.NETHERITE_HELMET,Material.NETHERITE_CHESTPLATE,Material.NETHERITE_LEGGINGS,Material.NETHERITE_BOOTS};String[] suf={"Blade","Cleaver","Drill","Spade","Harvester","Crown","Aegis","Legguards","Walkers"};String name=(high?HIGH:LOW)[t];ItemStack i=new ItemStack(high?mats[slot]:new Material[]{Material.STONE_SWORD,Material.STONE_AXE,Material.STONE_PICKAXE,Material.STONE_SHOVEL,Material.STONE_HOE,Material.CHAINMAIL_HELMET,Material.CHAINMAIL_CHESTPLATE,Material.CHAINMAIL_LEGGINGS,Material.CHAINMAIL_BOOTS}[slot]);ItemMeta m=i.getItemMeta();int base=high?145+t*15:1+t*2;m.setDisplayName((high?ChatColor.LIGHT_PURPLE:ChatColor.GREEN)+name+" "+suf[slot]);m.setLore(List.of(ChatColor.GRAY+(high?"BEYOND OMEGA":"STARTER")+" TIER",ChatColor.GOLD+"Power "+base));m.getPersistentDataContainer().set(k("extended_item"),PersistentDataType.STRING,(high?"H":"L")+t+":"+slot);m.addEnchant(Enchantment.UNBREAKING,Math.max(1,base),true);if(slot<=1){m.addEnchant(Enchantment.SHARPNESS,base+5,true);m.addEnchant(Enchantment.LOOTING,Math.max(1,base),true);}else if(slot<=4){m.addEnchant(Enchantment.EFFICIENCY,base+5,true);m.addEnchant(Enchantment.FORTUNE,Math.max(1,base),true);}else{m.addEnchant(Enchantment.PROTECTION,base+5,true);m.addEnchant(Enchantment.FIRE_PROTECTION,Math.max(1,base),true);if(slot==8)m.addEnchant(Enchantment.FEATHER_FALLING,base+3,true);}i.setItemMeta(m);return i;}
 public static ItemStack[] pool(boolean high,int t){ItemStack[] a=new ItemStack[9];for(int s=0;s<9;s++)a[s]=item(high,t,s);return a;}
 @EventHandler public void death(EntityDeathEvent e){Player p=e.getEntity().getKiller();if(p==null)return;Set<String> tags=e.getEntity().getScoreboardTags();boolean world=tags.contains("esnWorldBoss"),boss=world||tags.contains("esnSwampBoss")||tags.contains("esnBiomeBoss"),apex=tags.contains("esnApex");if(boss)return;if(apex&&ThreadLocalRandom.current().nextDouble()<.65)e.getDrops().add(key(true,ThreadLocalRandom.current().nextInt(HIGH.length)));else if(e.getEntity() instanceof Monster&&ThreadLocalRandom.current().nextDouble()<.08)e.getDrops().add(key(false,ThreadLocalRandom.current().nextInt(LOW.length)));}
 @EventHandler public void spawn(CreatureSpawnEvent e){if(!(e.getEntity() instanceof Monster m)||ThreadLocalRandom.current().nextDouble()>.012)return;m.addScoreboardTag("esnApex");m.setCustomName(ChatColor.DARK_RED+"APEX "+m.getType().name());m.setCustomNameVisible(true);var a=m.getAttribute(Attribute.MAX_HEALTH);if(a!=null){double hp=Math.min(900,Math.max(120,a.getBaseValue()*8));a.setBaseValue(hp);m.setHealth(hp);}m.addPotionEffect(new org.bukkit.potion.PotionEffect(org.bukkit.potion.PotionEffectType.RESISTANCE,Integer.MAX_VALUE,2));m.addPotionEffect(new org.bukkit.potion.PotionEffect(org.bukkit.potion.PotionEffectType.STRENGTH,Integer.MAX_VALUE,2));m.addPotionEffect(new org.bukkit.potion.PotionEffect(org.bukkit.potion.PotionEffectType.SPEED,Integer.MAX_VALUE,1));}
}