package com.esn.smp.gameplay;
import org.bukkit.*;import org.bukkit.command.*;import org.bukkit.configuration.file.YamlConfiguration;import org.bukkit.entity.Player;import org.bukkit.event.*;import org.bukkit.event.block.*;import org.bukkit.event.inventory.InventoryClickEvent;import org.bukkit.event.player.*;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.*;import org.bukkit.plugin.java.JavaPlugin;import java.io.*;import java.util.*;
public final class JailSystem implements Listener,CommandExecutor{
 private final JavaPlugin p;private final File file;private final YamlConfiguration db;private final String title=ChatColor.DARK_RED+"ESN Prison • Select Player";private final Map<UUID,String> selectedSentence=new HashMap<>();
 public JailSystem(JavaPlugin p){this.p=p;file=new File(p.getDataFolder(),"jails.yml");db=YamlConfiguration.loadConfiguration(file);Bukkit.getScheduler().runTaskLater(p,this::finishPrison,60L);Bukkit.getScheduler().runTaskTimer(p,this::expire,20L,20L);}
 private void save(){try{db.save(file);}catch(Exception e){p.getLogger().severe("Jail data save failed: "+e.getMessage());}}
 private boolean staff(Player x){return x.hasPermission("esnsmp.staff")||x.hasPermission("esnsmp.owner");}private boolean jailed(Player x){return db.getBoolean("jailed."+x.getUniqueId(),false);}
 private Location cell(int n){Location s=((com.esn.smp.ESNSMPPlugin)p).getSpawnManager().getSpawn();if(s==null)return Bukkit.getWorlds().get(0).getSpawnLocation();int bx=137+(n%4)*12,bz=125+(n/4)*17;return s.clone().add(bx,2,bz);}
 private long duration(String v){if(v==null)return 30*60000L;try{char u=Character.toLowerCase(v.charAt(v.length()-1));long n=Long.parseLong(Character.isDigit(u)?v:v.substring(0,v.length()-1));if(Character.isDigit(u))return n*60000L;return n*(u=='s'?1000L:u=='m'?60000L:u=='h'?3600000L:u=='d'?86400000L:-1);}catch(Exception e){return -1;}}
 public boolean onCommand(CommandSender s,Command c,String l,String[]a){if(!(s instanceof Player x)){s.sendMessage("Players only.");return true;}if(!staff(x)){x.sendMessage(ChatColor.RED+"Staff only.");return true;}if(a.length==0){open(x);return true;}Player t=Bukkit.getPlayer(a[0]);if(t==null){x.sendMessage(ChatColor.RED+"Player must be online.");return true;}if(a.length>1&&a[1].equalsIgnoreCase("release")){release(t);x.sendMessage(ChatColor.GREEN+"Released "+t.getName());return true;}int n=0;String time="30m";if(a.length>1)try{n=Math.max(0,Math.min(11,Integer.parseInt(a[1])-1));}catch(Exception ignored){time=a[1];}if(a.length>2)time=a[2];long ms=duration(time);if(ms<1000){x.sendMessage(ChatColor.RED+"Invalid time. Examples: 30m, 2h, 1d.");return true;}jail(t,n,ms);x.sendMessage(ChatColor.RED+"Jailed "+t.getName()+" in cell "+(n+1)+" for "+time+".");return true;}
 private ItemStack it(Material m,String n,String... lore){ItemStack i=new ItemStack(m);ItemMeta im=i.getItemMeta();im.setDisplayName(n);im.setLore(Arrays.asList(lore));i.setItemMeta(im);return i;}
 private void open(Player x){Inventory v=Bukkit.createInventory(null,54,title);int slot=0;for(Player t:Bukkit.getOnlinePlayers()){ItemStack h=it(Material.PLAYER_HEAD,ChatColor.RED+t.getName(),ChatColor.GRAY+"Click: cell selection",ChatColor.YELLOW+"GUI sentence: 30 minutes");SkullMeta sm=(SkullMeta)h.getItemMeta();sm.setOwningPlayer(t);h.setItemMeta(sm);v.setItem(slot++,h);if(slot>=45)break;}x.openInventory(v);}
 private void cells(Player x,Player t){Inventory v=Bukkit.createInventory(null,36,ChatColor.DARK_RED+"Cell for "+t.getName());String time=selectedSentence.getOrDefault(x.getUniqueId(),"30m");for(int i=0;i<12;i++)v.setItem(i,it(Material.IRON_BARS,ChatColor.RED+"Cell "+(i+1),ChatColor.GRAY+"Sentence: "+time));v.setItem(18,it(Material.CLOCK,ChatColor.YELLOW+"15 Minutes"));v.setItem(19,it(Material.CLOCK,ChatColor.YELLOW+"30 Minutes"));v.setItem(20,it(Material.CLOCK,ChatColor.GOLD+"1 Hour"));v.setItem(21,it(Material.CLOCK,ChatColor.GOLD+"2 Hours"));v.setItem(22,it(Material.CLOCK,ChatColor.RED+"1 Day"));v.setItem(31,it(Material.LIME_CONCRETE,ChatColor.GREEN+"Release",ChatColor.GRAY+"Release "+t.getName()));x.openInventory(v);}
 private void jail(Player t,int n,long ms){if(!jailed(t)){db.set("inventory."+t.getUniqueId()+".storage",Arrays.asList(t.getInventory().getStorageContents()));db.set("inventory."+t.getUniqueId()+".armor",Arrays.asList(t.getInventory().getArmorContents()));db.set("inventory."+t.getUniqueId()+".offhand",t.getInventory().getItemInOffHand());}t.getInventory().clear();t.getInventory().setArmorContents(new ItemStack[4]);t.getInventory().setItemInOffHand(null);db.set("jailed."+t.getUniqueId(),true);db.set("cell."+t.getUniqueId(),n);db.set("expires."+t.getUniqueId(),System.currentTimeMillis()+ms);save();t.teleport(cell(n));t.sendMessage(ChatColor.DARK_RED+"You have been jailed for "+format(ms)+". Your inventory was secured.");}
 private String format(long ms){long s=Math.max(0,ms/1000),d=s/86400;s%=86400;long h=s/3600;s%=3600;long m=s/60;s%=60;return (d>0?d+"d ":"")+(h>0?h+"h ":"")+(m>0?m+"m ":"")+(s>0?s+"s":"");}
 private void release(Player t){String id=t.getUniqueId().toString(),base="inventory."+id;t.getInventory().clear();List<?> st=db.getList(base+".storage");if(st!=null){ItemStack[] a=new ItemStack[t.getInventory().getStorageContents().length];for(int i=0;i<a.length&&i<st.size();i++)if(st.get(i) instanceof ItemStack z)a[i]=z;t.getInventory().setStorageContents(a);}List<?> ar=db.getList(base+".armor");if(ar!=null){ItemStack[] a=new ItemStack[4];for(int i=0;i<a.length&&i<ar.size();i++)if(ar.get(i) instanceof ItemStack z)a[i]=z;t.getInventory().setArmorContents(a);}ItemStack off=db.getItemStack(base+".offhand");if(off!=null)t.getInventory().setItemInOffHand(off);db.set(base,null);db.set("jailed."+id,false);db.set("expires."+id,null);save();Location s=((com.esn.smp.ESNSMPPlugin)p).getSpawnManager().getSpawn();if(s!=null)t.teleport(s);t.sendMessage(ChatColor.GREEN+"Your jail sentence is complete.");}
 private void expire(){long now=System.currentTimeMillis();for(Player x:Bukkit.getOnlinePlayers())if(jailed(x)){long end=db.getLong("expires."+x.getUniqueId(),0);if(end>0&&now>=end)release(x);}}
 private void finishPrison(){for(int n=0;n<12;n++){Location c=cell(n);World w=c.getWorld();if(w==null)continue;int bx=c.getBlockX(),by=c.getBlockY()-1,bz=c.getBlockZ();for(int dx=-4;dx<=4;dx++)for(int dy=0;dy<=5;dy++)for(int dz=-5;dz<=5;dz++){boolean wall=Math.abs(dx)==4||dy==0||dy==5||Math.abs(dz)==5;Material m=wall?Material.DEEPSLATE_BRICKS:Material.AIR;if(dz==-5&&Math.abs(dx)<=1&&dy>=1&&dy<=3)m=Material.IRON_BARS;w.getBlockAt(bx+dx,by+dy,bz+dz).setType(m,false);}w.getBlockAt(bx-2,by+1,bz+2).setType(Material.RED_BED,false);w.getBlockAt(bx+2,by+4,bz).setType(Material.SEA_LANTERN,false);w.getBlockAt(bx,by+1,bz-5).setType(Material.IRON_DOOR,false);}}
 @EventHandler public void click(InventoryClickEvent e){String tt=e.getView().getTitle();if(!tt.equals(title)&&!tt.startsWith(ChatColor.DARK_RED+"Cell for "))return;e.setCancelled(true);if(!(e.getWhoClicked() instanceof Player x)||e.getCurrentItem()==null)return;if(!staff(x)){x.closeInventory();return;}if(tt.equals(title)){if(e.getCurrentItem().getItemMeta() instanceof SkullMeta sm&&sm.getOwningPlayer()!=null){Player t=Bukkit.getPlayer(sm.getOwningPlayer().getUniqueId());if(t!=null)cells(x,t);}}else{String name=ChatColor.stripColor(tt).substring("Cell for ".length());Player t=Bukkit.getPlayerExact(name);if(t==null)return;if(e.getSlot()==31){release(t);x.closeInventory();}else if(e.getSlot()>=18&&e.getSlot()<=22){String[] times={"15m","30m","1h","2h","1d"};selectedSentence.put(x.getUniqueId(),times[e.getSlot()-18]);cells(x,t);}else if(e.getSlot()<12){String time=selectedSentence.getOrDefault(x.getUniqueId(),"30m");jail(t,e.getSlot(),duration(time));selectedSentence.remove(x.getUniqueId());x.closeInventory();}}}
 @EventHandler public void move(PlayerMoveEvent e){Player x=e.getPlayer();if(!jailed(x))return;Location c=cell(db.getInt("cell."+x.getUniqueId(),0));if(e.getTo()!=null&&(e.getTo().getWorld()!=c.getWorld()||Math.abs(e.getTo().getX()-c.getX())>3||Math.abs(e.getTo().getZ()-c.getZ())>4||Math.abs(e.getTo().getY()-c.getY())>4))x.teleport(c);}
 @EventHandler public void cmd(PlayerCommandPreprocessEvent e){if(jailed(e.getPlayer())&&!e.getPlayer().hasPermission("esnsmp.owner")){e.setCancelled(true);long end=db.getLong("expires."+e.getPlayer().getUniqueId(),0);e.getPlayer().sendMessage(ChatColor.RED+"Commands disabled while jailed. Remaining: "+format(end-System.currentTimeMillis()));}}
 @EventHandler public void breakB(BlockBreakEvent e){if(jailed(e.getPlayer()))e.setCancelled(true);}@EventHandler public void placeB(BlockPlaceEvent e){if(jailed(e.getPlayer()))e.setCancelled(true);}
 @EventHandler public void join(PlayerJoinEvent e){if(!jailed(e.getPlayer()))return;long end=db.getLong("expires."+e.getPlayer().getUniqueId(),0);Bukkit.getScheduler().runTaskLater(p,()->{if(end>0&&System.currentTimeMillis()>=end)release(e.getPlayer());else{e.getPlayer().teleport(cell(db.getInt("cell."+e.getPlayer().getUniqueId(),0)));e.getPlayer().sendMessage(ChatColor.RED+"Jail time remaining: "+format(end-System.currentTimeMillis()));}},2L);}
}