package com.esn.smp.gameplay;
import org.bukkit.*;import org.bukkit.command.*;import org.bukkit.configuration.file.YamlConfiguration;import org.bukkit.entity.Player;import org.bukkit.event.*;import org.bukkit.event.block.*;import org.bukkit.event.entity.*;import org.bukkit.event.inventory.InventoryClickEvent;import org.bukkit.event.player.*;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.*;import org.bukkit.plugin.java.JavaPlugin;import java.io.*;import java.util.*;
public final class JailSystem implements Listener,CommandExecutor{
 private final JavaPlugin p;private final File file;private final YamlConfiguration db;private final String title=ChatColor.DARK_RED+"ESN Prison • Select Player";
 public JailSystem(JavaPlugin p){this.p=p;file=new File(p.getDataFolder(),"jails.yml");db=YamlConfiguration.loadConfiguration(file);}
 private void save(){try{db.save(file);}catch(Exception e){p.getLogger().severe("Jail data save failed: "+e.getMessage());}}
 private boolean staff(Player x){return x.hasPermission("esnsmp.staff")||x.hasPermission("esnsmp.owner");}private boolean jailed(Player x){return db.getBoolean("jailed."+x.getUniqueId(),false);}
 private Location cell(int n){Location s=((com.esn.smp.ESNSMPPlugin)p).getSpawnManager().getSpawn();int bx=137+(n%4)*12,bz=125+(n/4)*17;return s.clone().add(bx,2,bz);}
 public boolean onCommand(CommandSender s,Command c,String l,String[]a){if(!(s instanceof Player x)){s.sendMessage("Players only.");return true;}if(!staff(x)){x.sendMessage(ChatColor.RED+"Staff only.");return true;}if(a.length==0){open(x);return true;}Player t=Bukkit.getPlayer(a[0]);if(t==null){x.sendMessage(ChatColor.RED+"Player must be online.");return true;}if(a.length>1&&a[1].equalsIgnoreCase("release")){release(t);x.sendMessage(ChatColor.GREEN+"Released "+t.getName());return true;}int n=0;if(a.length>1)try{n=Math.max(0,Math.min(11,Integer.parseInt(a[1])-1));}catch(Exception ignored){}jail(t,n);x.sendMessage(ChatColor.RED+"Jailed "+t.getName()+" in cell "+(n+1));return true;}
 private ItemStack it(Material m,String n,String... lore){ItemStack i=new ItemStack(m);ItemMeta im=i.getItemMeta();im.setDisplayName(n);im.setLore(Arrays.asList(lore));i.setItemMeta(im);return i;}
 private void open(Player x){Inventory v=Bukkit.createInventory(null,54,title);int slot=0;for(Player t:Bukkit.getOnlinePlayers()){ItemStack h=it(Material.PLAYER_HEAD,ChatColor.RED+t.getName(),ChatColor.GRAY+"Click to choose cell");SkullMeta sm=(SkullMeta)h.getItemMeta();sm.setOwningPlayer(t);h.setItemMeta(sm);v.setItem(slot++,h);if(slot>=45)break;}x.openInventory(v);}
 private void cells(Player x,Player t){Inventory v=Bukkit.createInventory(null,27,ChatColor.DARK_RED+"Cell for "+t.getName());for(int i=0;i<12;i++)v.setItem(i,it(Material.IRON_BARS,ChatColor.RED+"Cell "+(i+1),ChatColor.GRAY+"Jail "+t.getName()));v.setItem(22,it(Material.LIME_CONCRETE,ChatColor.GREEN+"Release",ChatColor.GRAY+"Release "+t.getName()));x.openInventory(v);}
 private void jail(Player t,int n){if(!jailed(t)){db.set("inventory."+t.getUniqueId()+".storage",Arrays.asList(t.getInventory().getStorageContents()));db.set("inventory."+t.getUniqueId()+".armor",Arrays.asList(t.getInventory().getArmorContents()));db.set("inventory."+t.getUniqueId()+".offhand",t.getInventory().getItemInOffHand());}t.getInventory().clear();t.getInventory().setArmorContents(new ItemStack[4]);t.getInventory().setItemInOffHand(null);db.set("jailed."+t.getUniqueId(),true);db.set("cell."+t.getUniqueId(),n);save();t.teleport(cell(n));t.sendMessage(ChatColor.DARK_RED+"You have been jailed. Your inventory was secured.");}
 private void release(Player t){String base="inventory."+t.getUniqueId();t.getInventory().clear();List<?> st=db.getList(base+".storage");if(st!=null){ItemStack[] a=new ItemStack[t.getInventory().getStorageContents().length];for(int i=0;i<a.length&&i<st.size();i++)if(st.get(i) instanceof ItemStack it)a[i]=it;t.getInventory().setStorageContents(a);}List<?> ar=db.getList(base+".armor");if(ar!=null){ItemStack[] a=new ItemStack[4];for(int i=0;i<a.length&&i<ar.size();i++)if(ar.get(i) instanceof ItemStack it)a[i]=it;t.getInventory().setArmorContents(a);}ItemStack off=db.getItemStack(base+".offhand");if(off!=null)t.getInventory().setItemInOffHand(off);db.set(base,null);db.set("jailed."+t.getUniqueId(),false);save();Location s=((com.esn.smp.ESNSMPPlugin)p).getSpawnManager().getSpawn();if(s!=null)t.teleport(s);}
 @EventHandler public void click(InventoryClickEvent e){String tt=e.getView().getTitle();if(!tt.equals(title)&&!tt.startsWith(ChatColor.DARK_RED+"Cell for "))return;e.setCancelled(true);if(!(e.getWhoClicked() instanceof Player x)||e.getCurrentItem()==null)return;if(!staff(x)){x.closeInventory();x.sendMessage(ChatColor.RED+"Staff only.");return;}if(tt.equals(title)){if(e.getCurrentItem().getItemMeta() instanceof SkullMeta sm&&sm.getOwningPlayer()!=null){Player t=Bukkit.getPlayer(sm.getOwningPlayer().getUniqueId());if(t!=null)cells(x,t);}}else{String name=ChatColor.stripColor(tt).substring("Cell for ".length());Player t=Bukkit.getPlayerExact(name);if(t==null)return;if(e.getSlot()==22){release(t);x.closeInventory();return;}if(e.getSlot()<12){jail(t,e.getSlot());x.closeInventory();}}}
 @EventHandler public void move(PlayerMoveEvent e){Player x=e.getPlayer();if(!jailed(x))return;int n=db.getInt("cell."+x.getUniqueId(),0);Location c=cell(n);if(e.getTo()!=null&&(e.getTo().getWorld()!=c.getWorld()||Math.abs(e.getTo().getX()-c.getX())>3||Math.abs(e.getTo().getZ()-c.getZ())>3||Math.abs(e.getTo().getY()-c.getY())>4))x.teleport(c);}
 @EventHandler public void cmd(PlayerCommandPreprocessEvent e){if(jailed(e.getPlayer())&&!e.getPlayer().hasPermission("esnsmp.owner")){e.setCancelled(true);e.getPlayer().sendMessage(ChatColor.RED+"Commands are disabled while jailed.");}}
 @EventHandler public void breakB(BlockBreakEvent e){if(jailed(e.getPlayer()))e.setCancelled(true);}@EventHandler public void placeB(BlockPlaceEvent e){if(jailed(e.getPlayer()))e.setCancelled(true);}@EventHandler public void quit(PlayerQuitEvent e){if(jailed(e.getPlayer()))db.set("jailed."+e.getPlayer().getUniqueId(),true);save();}@EventHandler public void join(PlayerJoinEvent e){if(jailed(e.getPlayer()))Bukkit.getScheduler().runTaskLater(p,()->e.getPlayer().teleport(cell(db.getInt("cell."+e.getPlayer().getUniqueId(),0))),2L);}
}