package com.esn.smp.gameplay;
import org.bukkit.*;import org.bukkit.enchantments.Enchantment;import org.bukkit.entity.*;import org.bukkit.event.*;import org.bukkit.event.entity.EntityDeathEvent;import org.bukkit.event.entity.EntityDamageByEntityEvent;import org.bukkit.event.block.BlockBreakEvent;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.ItemMeta;import org.bukkit.persistence.*;import java.util.*;import java.util.concurrent.ThreadLocalRandom;
public final class MegaCrates implements Listener{
 public static final int COUNT=100, ITEMS=11;
 private static NamespacedKey k(String s){return new NamespacedKey("esnsmp",s);}
 public static String name(int t){return "Realm "+String.format("%03d",t+1);}
 private static Material keyMaterial(int t){List<Material> a=new ArrayList<>();for(Material m:Material.values())if(m.isItem()&&m.getMaxStackSize()>=64&&!m.isAir()&&!m.name().contains("SPAWN_EGG"))a.add(m);a.sort(Comparator.comparing(Enum::name));return a.get(Math.floorMod(t,a.size()));}
 public static ItemStack key(int t){ItemStack i=new ItemStack(keyMaterial(t));ItemMeta m=i.getItemMeta();m.setDisplayName(ChatColor.GOLD+"✦ "+ChatColor.DARK_PURPLE+name(t)+ChatColor.GOLD+" Crate Key ✦");m.setLore(List.of(ChatColor.DARK_GRAY+"━━━━━━━━━━━━━━━━━━━━",ChatColor.LIGHT_PURPLE+"Realm Progression Key",ChatColor.GRAY+"Unlocks: "+ChatColor.WHITE+name(t)+" Crate",ChatColor.GRAY+"Realm Tier: "+ChatColor.GOLD+(t+1)+ChatColor.GRAY+" / "+ChatColor.GOLD+"100",ChatColor.GRAY+"Reward Pool: "+ChatColor.AQUA+ITEMS+" exclusive items",ChatColor.GRAY+"Enchant Power: "+ChatColor.LIGHT_PURPLE+(255+(int)Math.round((9745.0*t)/(COUNT-1))),ChatColor.DARK_GRAY+"Bound to the ESN Realm crate system",ChatColor.DARK_GRAY+"━━━━━━━━━━━━━━━━━━━━"));m.getPersistentDataContainer().set(k("mega_key"),PersistentDataType.INTEGER,t);i.setItemMeta(m);return i;}
 public static boolean isKey(ItemStack i,int t){return i!=null&&i.hasItemMeta()&&Objects.equals(i.getItemMeta().getPersistentDataContainer().get(k("mega_key"),PersistentDataType.INTEGER),t);}
 public static ItemStack item(int t,int s){Material[] a={Material.NETHERITE_SWORD,Material.NETHERITE_AXE,Material.NETHERITE_PICKAXE,Material.NETHERITE_SHOVEL,Material.NETHERITE_HOE,Material.NETHERITE_HELMET,Material.NETHERITE_CHESTPLATE,Material.NETHERITE_LEGGINGS,Material.NETHERITE_BOOTS,Material.BOW,Material.CROSSBOW};String[] n={"Blade","Cleaver","Drill","Spade","Harvester","Crown","Aegis","Legguards","Walkers","Longbow","Repeater"};int base=255+(int)Math.round((9745.0*t)/(COUNT-1));ItemStack i=new ItemStack(a[s]);ItemMeta m=i.getItemMeta();m.setDisplayName(ChatColor.LIGHT_PURPLE+name(t)+" "+n[s]);m.setLore(List.of(ChatColor.DARK_PURPLE+"MEGA CRATE TIER "+(t+1),ChatColor.GOLD+"Power "+base));m.getPersistentDataContainer().set(k("mega_item"),PersistentDataType.STRING,t+":"+s);applyUnsafe(i,Enchantment.UNBREAKING,base);if(s<=1){applyUnsafe(i,Enchantment.SHARPNESS,base);applyUnsafe(i,Enchantment.LOOTING,base);}else if(s<=4){applyUnsafe(i,Enchantment.EFFICIENCY,base);applyUnsafe(i,Enchantment.FORTUNE,base);}else if(s<=8){applyUnsafe(i,Enchantment.PROTECTION,base);if(s==8)applyUnsafe(i,Enchantment.FEATHER_FALLING,base);}else{applyUnsafe(i,Enchantment.POWER,base);applyUnsafe(i,Enchantment.PUNCH,base);}i.setItemMeta(m);return i;}
 private static void applyUnsafe(ItemStack i,Enchantment e,int level){i.addUnsafeEnchantment(e,Math.max(1,Math.min(10000,level)));}
 private static int tier(ItemStack i){if(i==null||!i.hasItemMeta())return -1;String v=i.getItemMeta().getPersistentDataContainer().get(k("mega_item"),PersistentDataType.STRING);if(v==null)return -1;try{return Integer.parseInt(v.split(":")[0]);}catch(Exception ex){return -1;}}
 private static double scale(int t){return t<0?1.0:1.0+(255.0+(9745.0*t)/(COUNT-1))/255.0;}
 @EventHandler(priority=EventPriority.HIGH,ignoreCancelled=true) public void realmDamage(EntityDamageByEntityEvent e){Player p=e.getDamager() instanceof Player q?q:e.getDamager() instanceof Projectile pr&&pr.getShooter() instanceof Player q?q:null;if(p==null)return;int t=tier(p.getInventory().getItemInMainHand());if(t<0)return;double mult=Math.min(12.0,scale(t));e.setDamage(e.getDamage()*mult);}
 @EventHandler(priority=EventPriority.HIGH,ignoreCancelled=true) public void realmMine(BlockBreakEvent e){ItemStack tool=e.getPlayer().getInventory().getItemInMainHand();int t=tier(tool);if(t<0)return;int level=255+(int)Math.round((9745.0*t)/(COUNT-1));if(ThreadLocalRandom.current().nextDouble()<Math.min(.85,level/12000.0)){Collection<ItemStack> drops=e.getBlock().getDrops(tool,e.getPlayer());for(ItemStack d:drops){ItemStack bonus=d.clone();bonus.setAmount(Math.min(bonus.getMaxStackSize(),Math.max(1,(int)Math.ceil(d.getAmount()*Math.min(8.0,level/1000.0)))));e.getPlayer().getInventory().addItem(bonus).values().forEach(z->e.getPlayer().getWorld().dropItemNaturally(e.getBlock().getLocation(),z));}}
 public static ItemStack[] pool(int t){ItemStack[] a=new ItemStack[ITEMS];for(int s=0;s<ITEMS;s++)a[s]=item(t,s);return a;}
 @EventHandler public void death(EntityDeathEvent e){Player p=e.getEntity().getKiller();if(p==null)return;Set<String> z=e.getEntity().getScoreboardTags();boolean world=z.contains("esnWorldBoss"),boss=world||z.contains("esnSwampBoss")||z.contains("esnBiomeBoss");if(boss)return;if(ThreadLocalRandom.current().nextDouble()<.35)e.getDrops().add(key(ThreadLocalRandom.current().nextInt(COUNT)));}
}