package com.esn.smp.gameplay;
import org.bukkit.*;import org.bukkit.enchantments.Enchantment;import org.bukkit.entity.*;import org.bukkit.event.*;import org.bukkit.event.entity.EntityDeathEvent;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.ItemMeta;import org.bukkit.persistence.*;import java.util.*;import java.util.concurrent.ThreadLocalRandom;
public final class MegaCrates implements Listener{
 public static final int COUNT=100, ITEMS=11;
 private static NamespacedKey k(String s){return new NamespacedKey("esnsmp",s);}
 public static String name(int t){return "Realm "+String.format("%03d",t+1);}
 public static ItemStack key(int t){ItemStack i=new ItemStack(Material.ECHO_SHARD);ItemMeta m=i.getItemMeta();m.setDisplayName(ChatColor.DARK_PURPLE+name(t)+" Crate Key");m.setLore(List.of(ChatColor.GRAY+"Mega progression crate "+(t+1)+"/100"));m.getPersistentDataContainer().set(k("mega_key"),PersistentDataType.INTEGER,t);i.setItemMeta(m);return i;}
 public static boolean isKey(ItemStack i,int t){return i!=null&&i.hasItemMeta()&&Objects.equals(i.getItemMeta().getPersistentDataContainer().get(k("mega_key"),PersistentDataType.INTEGER),t);}
 public static ItemStack item(int t,int s){Material[] a={Material.NETHERITE_SWORD,Material.NETHERITE_AXE,Material.NETHERITE_PICKAXE,Material.NETHERITE_SHOVEL,Material.NETHERITE_HOE,Material.NETHERITE_HELMET,Material.NETHERITE_CHESTPLATE,Material.NETHERITE_LEGGINGS,Material.NETHERITE_BOOTS,Material.BOW,Material.CROSSBOW};String[] n={"Blade","Cleaver","Drill","Spade","Harvester","Crown","Aegis","Legguards","Walkers","Longbow","Repeater"};int base=300+t*5;ItemStack i=new ItemStack(a[s]);ItemMeta m=i.getItemMeta();m.setDisplayName(ChatColor.LIGHT_PURPLE+name(t)+" "+n[s]);m.setLore(List.of(ChatColor.DARK_PURPLE+"MEGA CRATE TIER "+(t+1),ChatColor.GOLD+"Power "+base));m.getPersistentDataContainer().set(k("mega_item"),PersistentDataType.STRING,t+":"+s);m.addEnchant(Enchantment.UNBREAKING,base,true);if(s<=1){m.addEnchant(Enchantment.SHARPNESS,base+5,true);m.addEnchant(Enchantment.LOOTING,base,true);}else if(s<=4){m.addEnchant(Enchantment.EFFICIENCY,base+5,true);m.addEnchant(Enchantment.FORTUNE,base,true);}else if(s<=8){m.addEnchant(Enchantment.PROTECTION,base+5,true);if(s==8)m.addEnchant(Enchantment.FEATHER_FALLING,base,true);}else{m.addEnchant(Enchantment.POWER,base+5,true);m.addEnchant(Enchantment.PUNCH,Math.max(1,base/20),true);}i.setItemMeta(m);return i;}
 public static ItemStack[] pool(int t){ItemStack[] a=new ItemStack[ITEMS];for(int s=0;s<ITEMS;s++)a[s]=item(t,s);return a;}
 @EventHandler public void death(EntityDeathEvent e){Player p=e.getEntity().getKiller();if(p==null)return;Set<String> z=e.getEntity().getScoreboardTags();boolean world=z.contains("esnWorldBoss"),boss=world||z.contains("esnSwampBoss");if(boss){for(int r=0;r<5;r++)e.getDrops().add(key(ThreadLocalRandom.current().nextInt(COUNT)));return;}if(ThreadLocalRandom.current().nextDouble()<.35)e.getDrops().add(key(ThreadLocalRandom.current().nextInt(COUNT)));}
}