package com.esn.smp.gameplay;
import org.bukkit.*;import org.bukkit.enchantments.Enchantment;import org.bukkit.entity.*;import org.bukkit.event.*;import org.bukkit.event.entity.EntityDeathEvent;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.ItemMeta;import org.bukkit.persistence.*;import java.util.*;import java.util.concurrent.ThreadLocalRandom;
public final class MegaCrates implements Listener{
 public static final int COUNT=100, ITEMS=11;
 private static NamespacedKey k(String s){return new NamespacedKey("esnsmp",s);}
 public static String name(int t){return "Realm "+String.format("%03d",t+1);}
 public static ItemStack key(int t){Material[] km={Material.TRIPWIRE_HOOK,Material.ECHO_SHARD,Material.PRISMARINE_SHARD,Material.AMETHYST_SHARD,Material.NETHERITE_INGOT};ItemStack i=new ItemStack(km[Math.min(4,t/20)]);ItemMeta m=i.getItemMeta();m.setDisplayName(ChatColor.GOLD+"✦ "+ChatColor.DARK_PURPLE+name(t)+ChatColor.GOLD+" Crate Key ✦");m.setLore(List.of(ChatColor.DARK_GRAY+"━━━━━━━━━━━━━━━━━━━━",ChatColor.LIGHT_PURPLE+"Realm Progression Key",ChatColor.GRAY+"Unlocks: "+ChatColor.WHITE+name(t)+" Crate",ChatColor.GRAY+"Realm Tier: "+ChatColor.GOLD+(t+1)+ChatColor.GRAY+" / "+ChatColor.GOLD+"100",ChatColor.GRAY+"Reward Pool: "+ChatColor.AQUA+ITEMS+" exclusive items",ChatColor.GRAY+"Enchant Power: "+ChatColor.LIGHT_PURPLE+(500+(int)Math.round((9500.0*t)/(COUNT-1))),ChatColor.DARK_GRAY+"Bound to the ESN Realm crate system",ChatColor.DARK_GRAY+"━━━━━━━━━━━━━━━━━━━━"));m.getPersistentDataContainer().set(k("mega_key"),PersistentDataType.INTEGER,t);i.setItemMeta(m);return i;}
 public static boolean isKey(ItemStack i,int t){return i!=null&&i.hasItemMeta()&&Objects.equals(i.getItemMeta().getPersistentDataContainer().get(k("mega_key"),PersistentDataType.INTEGER),t);}
 public static ItemStack item(int t,int s){Material[] a={Material.NETHERITE_SWORD,Material.NETHERITE_AXE,Material.NETHERITE_PICKAXE,Material.NETHERITE_SHOVEL,Material.NETHERITE_HOE,Material.NETHERITE_HELMET,Material.NETHERITE_CHESTPLATE,Material.NETHERITE_LEGGINGS,Material.NETHERITE_BOOTS,Material.BOW,Material.CROSSBOW};String[] n={"Blade","Cleaver","Drill","Spade","Harvester","Crown","Aegis","Legguards","Walkers","Longbow","Repeater"};int base=500+(int)Math.round((9500.0*t)/(COUNT-1));ItemStack i=new ItemStack(a[s]);ItemMeta m=i.getItemMeta();m.setDisplayName(ChatColor.LIGHT_PURPLE+name(t)+" "+n[s]);m.setLore(List.of(ChatColor.DARK_PURPLE+"MEGA CRATE TIER "+(t+1),ChatColor.GOLD+"Power "+base));m.getPersistentDataContainer().set(k("mega_item"),PersistentDataType.STRING,t+":"+s);m.addEnchant(Enchantment.UNBREAKING,Math.min(10000,base),true);if(s<=1){m.addEnchant(Enchantment.SHARPNESS,Math.min(10000,base+5),true);m.addEnchant(Enchantment.LOOTING,base,true);}else if(s<=4){m.addEnchant(Enchantment.EFFICIENCY,Math.min(10000,base+5),true);m.addEnchant(Enchantment.FORTUNE,base,true);}else if(s<=8){m.addEnchant(Enchantment.PROTECTION,Math.min(10000,base+5),true);if(s==8)m.addEnchant(Enchantment.FEATHER_FALLING,base,true);}else{m.addEnchant(Enchantment.POWER,Math.min(10000,base+5),true);m.addEnchant(Enchantment.PUNCH,Math.max(1,base/20),true);}i.setItemMeta(m);return i;}
 public static ItemStack[] pool(int t){ItemStack[] a=new ItemStack[ITEMS];for(int s=0;s<ITEMS;s++)a[s]=item(t,s);return a;}
 @EventHandler public void death(EntityDeathEvent e){Player p=e.getEntity().getKiller();if(p==null)return;Set<String> z=e.getEntity().getScoreboardTags();boolean world=z.contains("esnWorldBoss"),boss=world||z.contains("esnSwampBoss");if(boss){for(int r=0;r<5;r++)e.getDrops().add(key(ThreadLocalRandom.current().nextInt(COUNT)));return;}if(ThreadLocalRandom.current().nextDouble()<.35)e.getDrops().add(key(ThreadLocalRandom.current().nextInt(COUNT)));}
}