package com.esn.smp.gameplay;
import org.bukkit.*;import org.bukkit.enchantments.Enchantment;import org.bukkit.entity.*;import org.bukkit.event.*;import org.bukkit.event.entity.EntityDeathEvent;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.ItemMeta;import org.bukkit.persistence.*;import org.bukkit.plugin.java.JavaPlugin;import java.util.*;import java.util.concurrent.ThreadLocalRandom;
public final class MythicCrates implements Listener{
 public static final String[] TIERS={"Astral","Oblivion","Seraph","Leviathan","Ragnarok","Eclipse","Genesis","Paradox","Empyrean","Omega"};
 private static final Material[] ICON={Material.NETHER_STAR,Material.CRYING_OBSIDIAN,Material.FEATHER,Material.HEART_OF_THE_SEA,Material.NETHERITE_BLOCK,Material.BLACK_DYE,Material.BEACON,Material.CLOCK,Material.END_CRYSTAL,Material.DRAGON_EGG};
 private final JavaPlugin p;public MythicCrates(JavaPlugin p){this.p=p;}
 private static NamespacedKey key(String s){return new NamespacedKey("esnsmp",s);}
 public static ItemStack crateKey(int tier){ItemStack i=new ItemStack(ICON[tier]);ItemMeta m=i.getItemMeta();m.setDisplayName(ChatColor.LIGHT_PURPLE+TIERS[tier]+" Crate Key");m.setLore(List.of(ChatColor.GRAY+"Tier "+(tier+1)+" Ascendant Key",ChatColor.GOLD+"Opens only the "+TIERS[tier]+" Crate"));m.getPersistentDataContainer().set(key("ascendant_key"),PersistentDataType.INTEGER,tier);i.setItemMeta(m);return i;}
 public static boolean isKey(ItemStack i,int tier){return i!=null&&i.hasItemMeta()&&Objects.equals(i.getItemMeta().getPersistentDataContainer().get(key("ascendant_key"),PersistentDataType.INTEGER),tier);}
 public static ItemStack item(int tier,int slot){Material[] mats={Material.NETHERITE_SWORD,Material.NETHERITE_AXE,Material.NETHERITE_PICKAXE,Material.NETHERITE_SHOVEL,Material.NETHERITE_HOE,Material.NETHERITE_HELMET,Material.NETHERITE_CHESTPLATE,Material.NETHERITE_LEGGINGS,Material.NETHERITE_BOOTS};Material mat=mats[slot];String[] suffix={"Blade","Cleaver","Drill","Spade","Harvester","Crown","Aegis","Legguards","Walkers"};ItemStack i=new ItemStack(mat);ItemMeta m=i.getItemMeta();m.setDisplayName(ChatColor.GOLD+TIERS[tier]+" "+suffix[slot]);m.setLore(List.of(ChatColor.DARK_PURPLE+"ASCENDANT "+(tier+1),ChatColor.GRAY+"Beyond Eternal equipment",ChatColor.GOLD+"Power "+(80+tier*5)));m.getPersistentDataContainer().set(key("ascendant_item"),PersistentDataType.STRING,tier+":"+slot);int base=80+tier*5;m.addEnchant(Enchantment.UNBREAKING,base,true);if(slot<=1){m.addEnchant(Enchantment.SHARPNESS,base+5,true);m.addEnchant(Enchantment.LOOTING,base,true);}else if(slot<=4){m.addEnchant(Enchantment.EFFICIENCY,base+5,true);m.addEnchant(Enchantment.FORTUNE,base,true);}else{m.addEnchant(Enchantment.PROTECTION,base+5,true);m.addEnchant(Enchantment.FIRE_PROTECTION,base,true);m.addEnchant(Enchantment.PROJECTILE_PROTECTION,base,true);if(slot==8)m.addEnchant(Enchantment.FEATHER_FALLING,base,true);}i.setItemMeta(m);return i;}
 public static ItemStack[] pool(int tier){ItemStack[] a=new ItemStack[9];for(int n=0;n<9;n++)a[n]=item(tier,n);return a;}
 @EventHandler public void drop(EntityDeathEvent e){Player k=e.getEntity().getKiller();if(k==null)return;boolean worldBoss=e.getEntity().getScoreboardTags().contains("esnWorldBoss"),swampBoss=e.getEntity().getScoreboardTags().contains("esnSwampBoss");boolean boss=worldBoss||swampBoss;if(boss){for(int t=0;t<10;t++){int amount=worldBoss?4:1;ItemStack key=crateKey(t);key.setAmount(amount);e.getDrops().add(key);}return;}double roll=ThreadLocalRandom.current().nextDouble();int tier=-1;else if(e.getEntity() instanceof Monster&&roll<.06)tier=ThreadLocalRandom.current().nextInt(5);else if((e.getEntity() instanceof Animals||e.getEntity() instanceof WaterMob)&&roll<.025)tier=ThreadLocalRandom.current().nextInt(3);if(tier>=0)e.getDrops().add(crateKey(tier));}
}