package com.esn.smp.gameplay;
import com.esn.smp.data.ESNDataStore;import org.bukkit.*;import org.bukkit.command.*;import org.bukkit.entity.Player;import org.bukkit.event.*;import org.bukkit.event.inventory.InventoryClickEvent;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.*;import java.util.*;
public final class ProfileCommand implements CommandExecutor,Listener{
 private final ESNDataStore data;private static final String TITLE=ChatColor.DARK_AQUA+"ESN Player Profile";
 public ProfileCommand(ESNDataStore d){data=d;}
 private ItemStack it(Material m,String n,String...l){ItemStack i=new ItemStack(m);ItemMeta x=i.getItemMeta();x.setDisplayName(n);x.setLore(Arrays.asList(l));i.setItemMeta(x);return i;}
 public boolean onCommand(CommandSender s,Command c,String l,String[]a){if(!(s instanceof Player p))return true;open(p);return true;}
 public void open(Player p){try{long bal=data.getBalance(p),ticks=p.getStatistic(Statistic.PLAY_ONE_MINUTE),mins=ticks/1200;int pk=p.getStatistic(Statistic.PLAYER_KILLS),deaths=p.getStatistic(Statistic.DEATHS),mobs=p.getStatistic(Statistic.MOB_KILLS);String rank=p.isOp()?"Owner":bal>=100000?"MVP":bal>=25000?"VIP":"Member";Inventory v=Bukkit.createInventory(null,54,TITLE);ItemStack h=it(Material.PLAYER_HEAD,ChatColor.GOLD+p.getName(),ChatColor.YELLOW+"Rank: "+rank,ChatColor.YELLOW+"ESN Coins: "+String.format("%,d",bal),ChatColor.GRAY+"Playtime: "+(mins/60)+"h "+(mins%60)+"m");SkullMeta sm=(SkullMeta)h.getItemMeta();sm.setOwningPlayer(p);h.setItemMeta(sm);v.setItem(4,h);v.setItem(19,it(Material.DIAMOND_SWORD,ChatColor.RED+"Combat",ChatColor.GRAY+"Player kills: "+pk,ChatColor.GRAY+"Mob kills: "+mobs,ChatColor.GRAY+"Deaths: "+deaths));v.setItem(20,it(Material.EXPERIENCE_BOTTLE,ChatColor.GREEN+"Level & Skills",ChatColor.GRAY+"Minecraft level: "+p.getLevel(),ChatColor.YELLOW+"Click: ESN skills"));v.setItem(21,it(Material.WRITABLE_BOOK,ChatColor.YELLOW+"Quests",ChatColor.GRAY+"Open quest progress"));v.setItem(22,it(Material.NETHER_STAR,ChatColor.LIGHT_PURPLE+"Boss & RPG Profile",ChatColor.GRAY+"Boss progression, contracts and gear"));v.setItem(23,it(Material.GOLD_BLOCK,ChatColor.GOLD+"Season Pass",ChatColor.GRAY+"Open Season Pass progression"));v.setItem(24,it(Material.TOTEM_OF_UNDYING,ChatColor.AQUA+"Achievements",ChatColor.GRAY+"Open achievements"));v.setItem(25,it(Material.NAME_TAG,ChatColor.YELLOW+"Titles",ChatColor.GRAY+"View/equip titles"));v.setItem(29,it(Material.IRON_PICKAXE,ChatColor.GRAY+"Jobs",ChatColor.GRAY+"Open jobs"));v.setItem(30,it(Material.ENDER_CHEST,ChatColor.DARK_PURPLE+"Adventure",ChatColor.GRAY+"Adventure records and systems"));v.setItem(31,it(Material.DRAGON_HEAD,ChatColor.RED+"Boss Codex",ChatColor.GRAY+"Persistent boss discoveries"));v.setItem(32,it(Material.BEACON,ChatColor.AQUA+"Progression",ChatColor.GRAY+"Full ESN progression path"));v.setItem(33,it(Material.CHEST,ChatColor.GOLD+"Collections",ChatColor.GRAY+"View collections"));v.setItem(49,it(Material.BARRIER,ChatColor.RED+"Close"));p.openInventory(v);}catch(Exception ex){p.sendMessage(ChatColor.RED+"Profile unavailable.");}}
 @EventHandler public void click(InventoryClickEvent e){if(!e.getView().getTitle().equals(TITLE))return;e.setCancelled(true);if(!(e.getWhoClicked() instanceof Player p))return;String cmd=switch(e.getRawSlot()){case 20->"skills";case 21->"quests";case 22->"rpgprofile";case 23->"seasonpass";case 24->"achievements";case 25->"titles";case 29->"jobs";case 30->"adventure";case 31->"bosscodex";case 32->"progression";case 33->"collections";default->null;};if(e.getRawSlot()==49){p.closeInventory();return;}if(cmd!=null){p.closeInventory();p.performCommand(cmd);}}
}