package com.esn.smp.gameplay;
import com.esn.smp.data.ESNDataStore;
import org.bukkit.*;import org.bukkit.attribute.Attribute;import org.bukkit.command.*;import org.bukkit.entity.*;import org.bukkit.event.*;import org.bukkit.event.entity.*;import org.bukkit.event.player.*;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.ItemMeta;import org.bukkit.persistence.*;import org.bukkit.plugin.java.JavaPlugin;import java.io.*;import java.sql.*;import java.util.*;import java.util.concurrent.ThreadLocalRandom;
public final class RPGOverhaul implements Listener,CommandExecutor,AutoCloseable{
 private final JavaPlugin p;private final ESNDataStore eco;private Connection db;private final NamespacedKey evolve,ability;private final Map<UUID,Map<UUID,Double>> damage=new HashMap<>();private final Map<UUID,Long> cooldown=new HashMap<>();private String rotation="Titan Hunt";
 public RPGOverhaul(JavaPlugin p,ESNDataStore eco)throws Exception{this.p=p;this.eco=eco;evolve=new NamespacedKey(p,"evolution");ability=new NamespacedKey(p,"ability");db=DriverManager.getConnection("jdbc:sqlite:"+new File(p.getDataFolder(),"rpg-overhaul.db"));try(Statement s=db.createStatement()){s.execute("CREATE TABLE IF NOT EXISTS rpg(uuid TEXT PRIMARY KEY,bosses INTEGER DEFAULT 0,dungeons INTEGER DEFAULT 0,raids INTEGER DEFAULT 0,contracts INTEGER DEFAULT 0,skillpoints INTEGER DEFAULT 0,seasonxp INTEGER DEFAULT 0,treasures INTEGER DEFAULT 0,fish INTEGER DEFAULT 0)");s.execute("CREATE TABLE IF NOT EXISTS codex(uuid TEXT,boss TEXT,kills INTEGER DEFAULT 0,PRIMARY KEY(uuid,boss))");s.execute("CREATE TABLE IF NOT EXISTS skills(uuid TEXT,skill TEXT,level INTEGER DEFAULT 0,PRIMARY KEY(uuid,skill))");s.execute("CREATE TABLE IF NOT EXISTS contracts(uuid TEXT PRIMARY KEY,boss INTEGER DEFAULT 0,dungeon INTEGER DEFAULT 0,treasure INTEGER DEFAULT 0,claimed INTEGER DEFAULT 0)");}Bukkit.getScheduler().runTaskTimer(p,this::rotate,1200L,72000L);}
 private void ensure(Player x)throws Exception{try(PreparedStatement q=db.prepareStatement("INSERT OR IGNORE INTO rpg(uuid) VALUES(?)")){q.setString(1,x.getUniqueId().toString());q.executeUpdate();}}
 private int get(Player x,String c)throws Exception{ensure(x);try(PreparedStatement q=db.prepareStatement("SELECT "+c+" FROM rpg WHERE uuid=?")){q.setString(1,x.getUniqueId().toString());try(ResultSet r=q.executeQuery()){return r.next()?r.getInt(1):0;}}}
 private void add(Player x,String c,int n){try{ensure(x);try(PreparedStatement q=db.prepareStatement("UPDATE rpg SET "+c+"="+c+"+? WHERE uuid=?")){q.setInt(1,n);q.setString(2,x.getUniqueId().toString());q.executeUpdate();}}catch(Exception ex){p.getLogger().warning("RPG progress: "+ex.getMessage());}}
 public boolean onCommand(CommandSender s,Command c,String l,String[] a){if(!(s instanceof Player x))return true;try{switch(c.getName()){case"bosscodex"->codex(x);case"skilltree"->{if(a.length>=2&&a[0].equalsIgnoreCase("spend"))spendSkill(x,a[1]);else skills(x);}case"contracts2"->contracts(x);case"gearupgrade"->upgrade(x);case"seasonpass"->x.sendMessage(ChatColor.LIGHT_PURPLE+"Season XP "+get(x,"seasonxp")+" | Bosses "+get(x,"bosses")+" | Dungeons "+get(x,"dungeons")+" | Raids "+get(x,"raids"));case"rpgprofile"->x.sendMessage(ChatColor.AQUA+x.getName()+" | Bosses "+get(x,"bosses")+" | Skill Points "+get(x,"skillpoints")+" | Treasure "+get(x,"treasures")+" | Fishing "+get(x,"fish"));case"rotation"->x.sendMessage(ChatColor.GOLD+"Current weekly focus: "+rotation);case"bossdiag"->diag(x);case"bosssummon"->summon(x);}}catch(Exception ex){x.sendMessage(ChatColor.RED+"RPG system unavailable; check console.");p.getLogger().warning("RPG command: "+ex.getMessage());}return true;}
 private void codex(Player x)throws Exception{x.sendMessage(ChatColor.DARK_PURPLE+"BOSS CODEX");try(PreparedStatement q=db.prepareStatement("SELECT boss,kills FROM codex WHERE uuid=? ORDER BY kills DESC LIMIT 20")){q.setString(1,x.getUniqueId().toString());try(ResultSet r=q.executeQuery()){boolean any=false;while(r.next()){any=true;x.sendMessage(ChatColor.GRAY+r.getString(1)+" — "+r.getInt(2)+" kills");}if(!any)x.sendMessage(ChatColor.GRAY+"Defeat a boss to begin your codex.");}}}
 private int skill(Player x,String sk)throws Exception{try(PreparedStatement q=db.prepareStatement("SELECT level FROM skills WHERE uuid=? AND skill=?")){q.setString(1,x.getUniqueId().toString());q.setString(2,sk);try(ResultSet r=q.executeQuery()){return r.next()?r.getInt(1):0;}}}
 private void skills(Player x)throws Exception{x.sendMessage(ChatColor.AQUA+"SKILL TREE — "+get(x,"skillpoints")+" points");for(String sk:new String[]{"combat","mining","farming","fishing","magic","runes","exploration"})x.sendMessage(ChatColor.GRAY+sk.toUpperCase(Locale.ROOT)+": "+skill(x,sk)+"/25");x.sendMessage(ChatColor.YELLOW+"/skilltree spend <skill>");}
 private void spendSkill(Player x,String sk)throws Exception{sk=sk.toLowerCase(Locale.ROOT);if(!Set.of("combat","mining","farming","fishing","magic","runes","exploration").contains(sk)){x.sendMessage(ChatColor.RED+"Unknown skill.");return;}int pts=get(x,"skillpoints"),lv=skill(x,sk);if(pts<1||lv>=25){x.sendMessage(ChatColor.RED+"No point available or skill is maxed.");return;}try(PreparedStatement q=db.prepareStatement("INSERT INTO skills(uuid,skill,level) VALUES(?,?,1) ON CONFLICT(uuid,skill) DO UPDATE SET level=level+1")){q.setString(1,x.getUniqueId().toString());q.setString(2,sk);q.executeUpdate();}add(x,"skillpoints",-1);x.sendMessage(ChatColor.GREEN+sk+" increased to "+(lv+1)+"/25.");}
 private void contracts(Player x)throws Exception{ensure(x);try(PreparedStatement q=db.prepareStatement("INSERT OR IGNORE INTO contracts(uuid) VALUES(?)")){q.setString(1,x.getUniqueId().toString());q.executeUpdate();}try(PreparedStatement q=db.prepareStatement("SELECT boss,dungeon,treasure,claimed FROM contracts WHERE uuid=?")){q.setString(1,x.getUniqueId().toString());try(ResultSet r=q.executeQuery()){r.next();int b=r.getInt(1),d=r.getInt(2),t=r.getInt(3),claimed=r.getInt(4);if(b>=5&&d>=3&&t>=2&&claimed==0){eco.deposit(x,10000);add(x,"contracts",1);add(x,"seasonxp",1000);try(PreparedStatement u=db.prepareStatement("UPDATE contracts SET claimed=1 WHERE uuid=?")){u.setString(1,x.getUniqueId().toString());u.executeUpdate();}x.sendMessage(ChatColor.GREEN+"Weekly contract completed: +10,000 Coins +1,000 Season XP.");}else x.sendMessage(ChatColor.GOLD+"Weekly Contract — Bosses "+b+"/5 | Dungeons "+d+"/3 | Treasures "+t+"/2"+(claimed==1?" | CLAIMED":""));}}}
 private void upgrade(Player x){ItemStack i=x.getInventory().getItemInMainHand();if(i==null||i.getType().isAir()||!i.hasItemMeta()){x.sendMessage(ChatColor.RED+"Hold equipment to evolve.");return;}ItemMeta m=i.getItemMeta();int lv=m.getPersistentDataContainer().getOrDefault(evolve,PersistentDataType.INTEGER,0);if(lv>=10){x.sendMessage(ChatColor.GOLD+"Maximum Evolution X.");return;}m.getPersistentDataContainer().set(evolve,PersistentDataType.INTEGER,lv+1);List<String> lore=m.hasLore()?new ArrayList<>(m.getLore()):new ArrayList<>();lore.removeIf(z->ChatColor.stripColor(z).startsWith("Evolution:"));lore.add(ChatColor.GOLD+"Evolution: "+(lv+1)+"/10");m.setLore(lore);i.setItemMeta(m);x.sendMessage(ChatColor.GREEN+"Gear evolved to "+(lv+1)+"/10.");}
 private void summon(Player x){ItemStack hand=x.getInventory().getItemInMainHand();if(hand.getType()!=Material.NETHER_STAR){x.sendMessage(ChatColor.RED+"Boss summoning requires a Nether Star.");return;}hand.setAmount(hand.getAmount()-1);Location l=x.getLocation().clone().add(x.getLocation().getDirection().multiply(6));l.setY(x.getWorld().getHighestBlockYAt(l.getBlockX(),l.getBlockZ())+1);LivingEntity z=(LivingEntity)x.getWorld().spawnEntity(l,EntityType.RAVAGER);z.setCustomName(ChatColor.DARK_RED+"SUMMONED TITAN");z.setCustomNameVisible(true);var a=z.getAttribute(Attribute.MAX_HEALTH);if(a!=null){a.setBaseValue(15000);z.setHealth(15000);}z.addScoreboardTag("esnBiomeBoss");z.addScoreboardTag("esnBiome_SUMMONED");z.setPersistent(true);z.setGlowing(true);Bukkit.broadcastMessage(ChatColor.RED+x.getName()+" summoned a Titan at "+l.getBlockX()+", "+l.getBlockY()+", "+l.getBlockZ());}
 private void diag(Player x){long world=Bukkit.getWorlds().stream().flatMap(w->w.getLivingEntities().stream()).filter(e->e.getScoreboardTags().contains("esnWorldBoss")).count(),regional=Bukkit.getWorlds().stream().flatMap(w->w.getLivingEntities().stream()).filter(e->e.getScoreboardTags().contains("esnBiomeBoss")||e.getScoreboardTags().contains("esnSwampBoss")).count();x.sendMessage(ChatColor.GREEN+"Boss diagnostics: world="+world+" regional="+regional+" | Realm crates="+MegaCrates.COUNT+" | DB="+(db!=null));}
 @EventHandler public void hit(EntityDamageByEntityEvent e){if(!(e.getEntity() instanceof LivingEntity b)||!boss(b))return;Player x=e.getDamager() instanceof Player q?q:e.getDamager() instanceof Projectile pr&&pr.getShooter() instanceof Player q?q:null;if(x!=null)damage.computeIfAbsent(b.getUniqueId(),k->new HashMap<>()).merge(x.getUniqueId(),Math.max(0,e.getFinalDamage()),Double::sum);}
 @EventHandler(priority=EventPriority.MONITOR) public void death(EntityDeathEvent e){LivingEntity b=e.getEntity();if(!boss(b))return;Player k=b.getKiller();if(k!=null){add(k,"bosses",1);contract(k,"boss");add(k,"skillpoints",2);add(k,"seasonxp",250);String n=ChatColor.stripColor(b.getCustomName()==null?b.getType().name():b.getCustomName());try(PreparedStatement q=db.prepareStatement("INSERT INTO codex(uuid,boss,kills) VALUES(?,?,1) ON CONFLICT(uuid,boss) DO UPDATE SET kills=kills+1")){q.setString(1,k.getUniqueId().toString());q.setString(2,n);q.executeUpdate();}catch(Exception ignored){}}Map<UUID,Double>d=damage.remove(b.getUniqueId());if(d!=null&&!d.isEmpty()){double total=d.values().stream().mapToDouble(Double::doubleValue).sum();d.entrySet().stream().sorted(Map.Entry.<UUID,Double>comparingByValue().reversed()).limit(3).forEach(z->{Player x=Bukkit.getPlayer(z.getKey());if(x!=null&&z.getValue()>=total*.05){x.giveExp(100);x.sendMessage(ChatColor.GOLD+"Boss participation: "+Math.round(z.getValue())+" damage ("+Math.round(z.getValue()/Math.max(1,total)*100)+"%)");}});}}
 private boolean boss(LivingEntity b){Set<String>t=b.getScoreboardTags();return t.contains("esnWorldBoss")||t.contains("esnSwampBoss")||t.contains("esnBiomeBoss");}
 @EventHandler public void use(PlayerInteractEvent e){ItemStack i=e.getItem();if(i==null||!i.hasItemMeta())return;int lv=i.getItemMeta().getPersistentDataContainer().getOrDefault(evolve,PersistentDataType.INTEGER,0);if(lv<3)return;Player x=e.getPlayer();long now=System.currentTimeMillis();if(cooldown.getOrDefault(x.getUniqueId(),0L)>now)return;cooldown.put(x.getUniqueId(),now+30000);x.addPotionEffect(new org.bukkit.potion.PotionEffect(org.bukkit.potion.PotionEffectType.STRENGTH,100,Math.min(4,lv/2)));x.getWorld().spawnParticle(Particle.ENCHANT,x.getLocation().add(0,1,0),40,1,1,1,.1);x.sendActionBar(ChatColor.GOLD+"Evolution ability activated — 30s cooldown");}
 @EventHandler public void fish(PlayerFishEvent e){if(e.getState()!=PlayerFishEvent.State.CAUGHT_FISH)return;add(e.getPlayer(),"fish",1);if(ThreadLocalRandom.current().nextDouble()<.02){add(e.getPlayer(),"treasures",1);contract(e.getPlayer(),"treasure");e.getPlayer().getInventory().addItem(new ItemStack(Material.HEART_OF_THE_SEA));e.getPlayer().sendMessage(ChatColor.AQUA+"You discovered an ancient fishing treasure!");}}
 @EventHandler public void block(org.bukkit.event.block.BlockBreakEvent e){try{String sk=e.getBlock().getType().name().contains("ORE")?"mining":e.getBlock().getType().name().contains("CROP")?"farming":null;if(sk!=null&&skill(e.getPlayer(),sk)>0&&ThreadLocalRandom.current().nextDouble()<skill(e.getPlayer(),sk)*.01)e.getPlayer().giveExp(2);}catch(Exception ignored){}}
 private void contract(Player x,String type){try{ensure(x);try(PreparedStatement q=db.prepareStatement("INSERT OR IGNORE INTO contracts(uuid) VALUES(?)")){q.setString(1,x.getUniqueId().toString());q.executeUpdate();}String col=type.equals("boss")?"boss":type.equals("treasure")?"treasure":"dungeon";try(PreparedStatement q=db.prepareStatement("UPDATE contracts SET "+col+"="+col+"+1 WHERE uuid=?")){q.setString(1,x.getUniqueId().toString());q.executeUpdate();}}catch(Exception ignored){}}
 private void rotate(){String[]r={"Titan Hunt","Dungeon Delve","Treasure Rush","Fishing Frenzy","Raid Breaker","Relic Forge"};rotation=r[ThreadLocalRandom.current().nextInt(r.length)];Bukkit.broadcastMessage(ChatColor.LIGHT_PURPLE+"ESN ROTATION: "+rotation+" is now active.");}
 public void close()throws Exception{if(db!=null)db.close();}
}