package com.esn.smp.gameplay;
import org.bukkit.*;import org.bukkit.command.*;import org.bukkit.entity.Player;import org.bukkit.event.*;import org.bukkit.event.player.PlayerMoveEvent;import org.bukkit.event.entity.CreatureSpawnEvent;import org.bukkit.plugin.java.JavaPlugin;import java.util.*;
public final class ServerChampionship implements Listener,CommandExecutor{
 private final JavaPlugin p;private boolean registration=false,active=false;private final LinkedHashSet<UUID> entrants=new LinkedHashSet<>();private final Map<UUID,Location> locked=new HashMap<>();
 public ServerChampionship(JavaPlugin p){this.p=p;Bukkit.getScheduler().runTaskLater(p,this::ensureArena,40L);}
 private boolean staff(Player x){return x.hasPermission("esnsmp.staff")||x.hasPermission("esnsmp.owner");}
 public boolean onCommand(CommandSender s,Command c,String l,String[]a){if(!(s instanceof Player x)){s.sendMessage("Players only.");return true;}if(a.length==0){x.sendMessage(ChatColor.GOLD+"/championship <start|forfeit|status|cancel>");return true;}String sub=a[0].toLowerCase(Locale.ROOT);
  if(sub.equals("forfeit")){if(!active||!entrants.remove(x.getUniqueId())){x.sendMessage(ChatColor.RED+"You are not competing in an active Championship.");return true;}locked.remove(x.getUniqueId());Location sp=((com.esn.smp.ESNSMPPlugin)p).getSpawnManager().getSpawn();if(sp!=null)x.teleport(sp);x.sendMessage(ChatColor.YELLOW+"You forfeited the ESN Server Championship.");Bukkit.broadcastMessage(ChatColor.YELLOW+x.getName()+" forfeited the Championship.");return true;}
  if(!staff(x)){x.sendMessage(ChatColor.RED+"Only ESN staff can control Championships.");return true;}
  if(sub.equals("start")){ensureArena();if(active){x.sendMessage(ChatColor.YELLOW+"A Championship is already active.");return true;}registration=false;active=true;entrants.clear();for(Player q:Bukkit.getOnlinePlayers())entrants.add(q.getUniqueId());if(entrants.isEmpty()){active=false;x.sendMessage(ChatColor.RED+"At least 1 online player is required.");return true;}Bukkit.broadcastMessage(ChatColor.GOLD+"🏆 ESN SERVER CHAMPIONSHIP STARTED! "+ChatColor.YELLOW+"All online players are competing. Use /championship forfeit to leave.");if(entrants.size()==1){Player winner=Bukkit.getPlayer(entrants.iterator().next());active=false;if(winner!=null){Bukkit.broadcastMessage(ChatColor.GOLD+"🏆 "+winner.getName()+" wins the ESN Server Championship automatically as the only competitor!");winner.sendTitle(ChatColor.GOLD+"CHAMPION",ChatColor.YELLOW+"Automatic victory!",10,80,20);}entrants.clear();return true;}stage();return true;}
  if(sub.equals("cancel")){registration=false;active=false;for(UUID id:locked.keySet()){Player q=Bukkit.getPlayer(id);if(q!=null)q.setWalkSpeed(.2f);}locked.clear();entrants.clear();Bukkit.broadcastMessage(ChatColor.RED+"The ESN Server Championship was cancelled.");return true;}
  if(sub.equals("status")){x.sendMessage(ChatColor.GOLD+"Championship: "+(active?"ACTIVE":"inactive")+ChatColor.GRAY+" | Remaining competitors: "+entrants.size());return true;}return true;}
 private Location center(){Location s=((com.esn.smp.ESNSMPPlugin)p).getSpawnManager().getSpawn();World w=s!=null?s.getWorld():Bukkit.getWorlds().get(0);Location base=s!=null?s.clone():w.getSpawnLocation();int x=base.getBlockX()+400,z=base.getBlockZ(),y=Math.max(base.getBlockY()+2,w.getHighestBlockYAt(x,z)+2);return new Location(w,x+.5,y,z+.5);}
 private void ensureArena(){Location c=center();World w=c.getWorld();int cx=c.getBlockX(),cy=c.getBlockY()-1,cz=c.getBlockZ();if(w.getBlockAt(cx,cy,cz).getType()==Material.POLISHED_DEEPSLATE&&w.getBlockAt(cx+74,cy,cz+74).getType()==Material.POLISHED_DEEPSLATE)return;final int[] dx={-75},dz={-75};Bukkit.getScheduler().runTaskTimer(p,task->{long end=System.nanoTime()+6_000_000L;while(System.nanoTime()<end&&dx[0]<=74){int x=cx+dx[0],z=cz+dz[0];w.getBlockAt(x,cy,z).setType(Material.POLISHED_DEEPSLATE,false);for(int yy=1;yy<=5;yy++)w.getBlockAt(x,cy+yy,z).setType(Material.AIR,false);if((Math.abs(dx[0])==74||Math.abs(dz[0])==74))w.getBlockAt(x,cy+1,z).setType(Material.IRON_BARS,false);else if(dx[0]%10==0&&dz[0]%10==0)w.getBlockAt(x,cy+1,z).setType(Material.TORCH,false);dz[0]++;if(dz[0]>74){dz[0]=-75;dx[0]++;}}if(dx[0]>74){task.cancel();p.getLogger().info("[Championship] 150x150 arena ready at "+cx+", "+cy+", "+cz);}},1L,1L);}
 @EventHandler public void arenaMob(CreatureSpawnEvent e){Location c=center();if(e.getLocation().getWorld()==c.getWorld()&&Math.abs(e.getLocation().getX()-c.getX())<=80&&Math.abs(e.getLocation().getZ()-c.getZ())<=80)e.setCancelled(true);}
 private void stage(){Location c=center();Iterator<UUID> it=entrants.iterator();Player a=it.hasNext()?Bukkit.getPlayer(it.next()):null,b=it.hasNext()?Bukkit.getPlayer(it.next()):null;if(a==null||b==null){Bukkit.broadcastMessage(ChatColor.RED+"Championship needs two online competitors.");return;}a.teleport(c.clone().add(-25,0,0));b.teleport(c.clone().add(25,0,0));int n=0;while(it.hasNext()){Player q=Bukkit.getPlayer(it.next());if(q==null)continue;Location seat=c.clone().add(-70+(n%15)*10,8,(n/15%2==0?-70:70));q.teleport(seat);locked.put(q.getUniqueId(),seat);n++;}Bukkit.broadcastMessage(ChatColor.GOLD+"🏆 Championship match: "+ChatColor.WHITE+a.getName()+ChatColor.GOLD+" vs "+ChatColor.WHITE+b.getName());}
 @EventHandler public void move(PlayerMoveEvent e){Location l=locked.get(e.getPlayer().getUniqueId());if(l==null||e.getTo()==null)return;if(e.getTo().distanceSquared(l)>.04)e.setTo(l);}
}