package com.esn.smp.gameplay;
import org.bukkit.*;import org.bukkit.command.*;import org.bukkit.entity.Player;import org.bukkit.event.*;import org.bukkit.event.player.PlayerMoveEvent;import org.bukkit.plugin.java.JavaPlugin;import java.util.*;
public final class ServerChampionship implements Listener,CommandExecutor{
 private final JavaPlugin p;private boolean registration=false,active=false;private final LinkedHashSet<UUID> entrants=new LinkedHashSet<>();private final Map<UUID,Location> locked=new HashMap<>();
 public ServerChampionship(JavaPlugin p){this.p=p;}
 private boolean staff(Player x){return x.hasPermission("esnsmp.staff")||x.hasPermission("esnsmp.owner");}
 public boolean onCommand(CommandSender s,Command c,String l,String[]a){if(!(s instanceof Player x)){s.sendMessage("Players only.");return true;}if(a.length==0){x.sendMessage(ChatColor.GOLD+"/championship <start|forfeit|status|cancel>");return true;}String sub=a[0].toLowerCase(Locale.ROOT);
  if(sub.equals("forfeit")){if(!active||!entrants.remove(x.getUniqueId())){x.sendMessage(ChatColor.RED+"You are not competing in an active Championship.");return true;}locked.remove(x.getUniqueId());Location sp=((com.esn.smp.ESNSMPPlugin)p).getSpawnManager().getSpawn();if(sp!=null)x.teleport(sp);x.sendMessage(ChatColor.YELLOW+"You forfeited the ESN Server Championship.");Bukkit.broadcastMessage(ChatColor.YELLOW+x.getName()+" forfeited the Championship.");return true;}
  if(!staff(x)){x.sendMessage(ChatColor.RED+"Only ESN staff can control Championships.");return true;}
  if(sub.equals("start")){if(active){x.sendMessage(ChatColor.YELLOW+"A Championship is already active.");return true;}registration=false;active=true;entrants.clear();for(Player q:Bukkit.getOnlinePlayers())entrants.add(q.getUniqueId());if(entrants.size()<2){active=false;entrants.clear();x.sendMessage(ChatColor.RED+"At least 2 online players are required.");return true;}Bukkit.broadcastMessage(ChatColor.GOLD+"🏆 ESN SERVER CHAMPIONSHIP STARTED! "+ChatColor.YELLOW+"All online players are competing. Use /championship forfeit to leave.");stage();return true;}
  if(sub.equals("cancel")){registration=false;active=false;for(UUID id:locked.keySet()){Player q=Bukkit.getPlayer(id);if(q!=null)q.setWalkSpeed(.2f);}locked.clear();entrants.clear();Bukkit.broadcastMessage(ChatColor.RED+"The ESN Server Championship was cancelled.");return true;}
  if(sub.equals("status")){x.sendMessage(ChatColor.GOLD+"Championship: "+(active?"ACTIVE":"inactive")+ChatColor.GRAY+" | Remaining competitors: "+entrants.size());return true;}return true;}
 private Location center(){Location s=((com.esn.smp.ESNSMPPlugin)p).getSpawnManager().getSpawn();World w=s!=null?s.getWorld():Bukkit.getWorlds().get(0);return (s!=null?s.clone():w.getSpawnLocation()).add(-320,5,320);}
 private void stage(){Location c=center();Iterator<UUID> it=entrants.iterator();Player a=it.hasNext()?Bukkit.getPlayer(it.next()):null,b=it.hasNext()?Bukkit.getPlayer(it.next()):null;if(a==null||b==null){Bukkit.broadcastMessage(ChatColor.RED+"Championship needs two online competitors.");return;}a.teleport(c.clone().add(-25,0,0));b.teleport(c.clone().add(25,0,0));int n=0;while(it.hasNext()){Player q=Bukkit.getPlayer(it.next());if(q==null)continue;Location seat=c.clone().add(-70+(n%15)*10,8,(n/15%2==0?-70:70));q.teleport(seat);locked.put(q.getUniqueId(),seat);n++;}Bukkit.broadcastMessage(ChatColor.GOLD+"🏆 Championship match: "+ChatColor.WHITE+a.getName()+ChatColor.GOLD+" vs "+ChatColor.WHITE+b.getName());}
 @EventHandler public void move(PlayerMoveEvent e){Location l=locked.get(e.getPlayer().getUniqueId());if(l==null||e.getTo()==null)return;if(e.getTo().distanceSquared(l)>.04)e.setTo(l);}
}