package com.esn.smp.gameplay;
import org.bukkit.*;import org.bukkit.command.*;import org.bukkit.configuration.file.YamlConfiguration;import org.bukkit.entity.Player;import org.bukkit.event.*;import org.bukkit.event.entity.EntityDamageEvent;import org.bukkit.event.inventory.InventoryClickEvent;import org.bukkit.event.player.PlayerMoveEvent;
import org.bukkit.event.player.PlayerQuitEvent;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.*;import org.bukkit.plugin.java.JavaPlugin;import org.bukkit.scheduler.BukkitTask;import java.io.*;import java.util.*;
public final class Teleports implements CommandExecutor,Listener{
 private record Request(UUID sender,boolean here,long expires){} private final JavaPlugin plugin;private final Map<UUID,Request> requests=new HashMap<>();private final Map<UUID,Long> cooldown=new HashMap<>();private final Map<UUID,Location> back=new HashMap<>(),warmStart=new HashMap<>();private final Map<UUID,BukkitTask> warmTasks=new HashMap<>();private final File file;private final YamlConfiguration settings;private static final String MENU=ChatColor.DARK_AQUA+"ESN Teleports",PLAYERS=ChatColor.DARK_AQUA+"Choose TPA Player",HERE=ChatColor.DARK_AQUA+"Choose TPAHere Player";
 public Teleports(JavaPlugin p){plugin=p;file=new File(p.getDataFolder(),"teleports.yml");settings=YamlConfiguration.loadConfiguration(file);}
 private boolean disabled(UUID id){return settings.getBoolean("disabled."+id,false);} private void setDisabled(UUID id,boolean v){settings.set("disabled."+id,v);try{settings.save(file);}catch(Exception e){plugin.getLogger().severe("Could not save teleport settings: "+e.getMessage());}}
 public boolean onCommand(CommandSender s,Command c,String l,String[] a){if(!(s instanceof Player p))return true;String n=c.getName().toLowerCase();if(n.equals("tpmenu")){openMenu(p);return true;}if(n.equals("tptoggle")){setDisabled(p.getUniqueId(),!disabled(p.getUniqueId()));p.sendMessage(disabled(p.getUniqueId())?ChatColor.YELLOW+"Teleport requests are now OFF.":ChatColor.GREEN+"Teleport requests are now ON.");return true;}if(n.equals("tpa")||n.equals("tpahere")){if(a.length<1){openPlayers(p,n.equals("tpahere"));return true;}send(p,PlayerResolver.online(a[0]),n.equals("tpahere"));return true;}if(n.equals("tpaccept")){accept(p);return true;}if(n.equals("tpdeny")){Request q=requests.remove(p.getUniqueId());Player r=q==null?null:Bukkit.getPlayer(q.sender());p.sendMessage(q==null?ChatColor.RED+"No active request.":ChatColor.YELLOW+"Request denied.");if(r!=null)r.sendMessage(ChatColor.RED+p.getName()+" denied your teleport request.");return true;}if(n.equals("back")){Location b=back.get(p.getUniqueId());if(b==null)p.sendMessage(ChatColor.RED+"No previous location.");else{Location old=p.getLocation().clone();p.teleport(b);back.put(p.getUniqueId(),old);}return true;}return true;}
 public void openMenu(Player p){Inventory v=Bukkit.createInventory(null,36,MENU);v.setItem(10,item(Material.ENDER_PEARL,ChatColor.GREEN+"Teleport To Player",ChatColor.GRAY+"Choose an online player to send /tpa"));v.setItem(12,item(Material.ENDER_EYE,ChatColor.AQUA+"Bring Player To You",ChatColor.GRAY+"Choose a player for /tpahere"));Request q=requests.get(p.getUniqueId());v.setItem(14,item(q!=null?Material.LIME_DYE:Material.GRAY_DYE,q!=null?ChatColor.GREEN+"Pending Request":ChatColor.GRAY+"No Pending Request",q!=null?ChatColor.YELLOW+"Click to accept":ChatColor.GRAY+"Nobody is requesting a teleport"));v.setItem(16,item(Material.RED_DYE,ChatColor.RED+"Deny Request",ChatColor.GRAY+"Reject your current incoming request"));boolean off=disabled(p.getUniqueId());v.setItem(22,item(off?Material.REDSTONE_BLOCK:Material.EMERALD_BLOCK,(off?ChatColor.RED:ChatColor.GREEN)+"TPA Requests: "+(off?"OFF":"ON"),ChatColor.GRAY+"Click to "+(off?"enable":"disable")+" incoming TPA requests",ChatColor.GRAY+"This setting saves after restart"));v.setItem(31,item(Material.ENDER_CHEST,ChatColor.GOLD+"/back",ChatColor.GRAY+"Return to your previous teleport location"));p.openInventory(v);}
 private void openPlayers(Player p,boolean here){Inventory v=Bukkit.createInventory(null,54,here?HERE:PLAYERS);int slot=0;for(Player t:Bukkit.getOnlinePlayers()){if(t==p)continue;ItemStack head=new ItemStack(Material.PLAYER_HEAD);SkullMeta m=(SkullMeta)head.getItemMeta();m.setOwningPlayer(t);m.setDisplayName((disabled(t.getUniqueId())?ChatColor.RED:ChatColor.GREEN)+t.getName());m.setLore(List.of(disabled(t.getUniqueId())?ChatColor.RED+"TPA disabled":ChatColor.GRAY+"Click to send request"));head.setItemMeta(m);v.setItem(slot++,head);if(slot>=54)break;}p.openInventory(v);}
 private void send(Player p,Player t,boolean here){if(t==null||t==p){p.sendMessage(ChatColor.RED+"Player not found.");return;}if(disabled(t.getUniqueId())){p.sendMessage(ChatColor.RED+"That player has teleport requests disabled.");return;}requests.put(t.getUniqueId(),new Request(p.getUniqueId(),here,System.currentTimeMillis()+60000));t.sendMessage(ChatColor.GOLD+p.getName()+(here?" wants you to teleport to them.":" wants to teleport to you.")+ChatColor.GRAY+" Open /tpa to accept or deny.");p.sendMessage(ChatColor.GREEN+"Teleport request sent. Expires in 60 seconds.");}
 private void accept(Player p){Request q=requests.remove(p.getUniqueId());Player r=q==null?null:Bukkit.getPlayer(q.sender());if(q==null||r==null||q.expires()<System.currentTimeMillis()){p.sendMessage(ChatColor.RED+"No active request.");return;}Player moving=q.here()?p:r,dest=q.here()?r:p;if(cooldown.getOrDefault(moving.getUniqueId(),0L)>System.currentTimeMillis()){moving.sendMessage(ChatColor.RED+"Teleport is on cooldown.");return;}startWarmup(moving,dest);p.sendMessage(ChatColor.GREEN+"Teleport request accepted.");}
 private ItemStack item(Material mat,String name,String...lore){ItemStack i=new ItemStack(mat);ItemMeta m=i.getItemMeta();m.setDisplayName(name);m.setLore(List.of(lore));i.setItemMeta(m);return i;}
 @EventHandler public void menu(InventoryClickEvent e){if(!(e.getWhoClicked() instanceof Player p))return;String t=e.getView().getTitle();if(t.equals(MENU)){e.setCancelled(true);switch(e.getRawSlot()){case 10->openPlayers(p,false);case 12->openPlayers(p,true);case 14->accept(p);case 16->{Request q=requests.remove(p.getUniqueId());p.sendMessage(q==null?ChatColor.RED+"No active request.":ChatColor.YELLOW+"Request denied.");openMenu(p);}case 22->{setDisabled(p.getUniqueId(),!disabled(p.getUniqueId()));openMenu(p);}case 31->Bukkit.dispatchCommand(p,"back");}return;}if(t.equals(PLAYERS)||t.equals(HERE)){e.setCancelled(true);if(e.getCurrentItem()==null||e.getCurrentItem().getType()!=Material.PLAYER_HEAD)return;SkullMeta m=(SkullMeta)e.getCurrentItem().getItemMeta();OfflinePlayer op=m.getOwningPlayer();if(op==null)return;Player target=Bukkit.getPlayer(op.getUniqueId());p.closeInventory();send(p,target,t.equals(HERE));}}
 private void startWarmup(Player p,Player dest){Location start=p.getLocation().clone();warmStart.put(p.getUniqueId(),start);p.sendMessage(ChatColor.YELLOW+"Teleporting in 3 seconds. Moving or taking damage cancels.");BukkitTask task=plugin.getServer().getScheduler().runTaskLater(plugin,()->{warmTasks.remove(p.getUniqueId());warmStart.remove(p.getUniqueId());if(!p.isOnline()||!dest.isOnline())return;back.put(p.getUniqueId(),p.getLocation().clone());p.teleport(dest.getLocation());cooldown.put(p.getUniqueId(),System.currentTimeMillis()+15000);p.sendMessage(ChatColor.GREEN+"Teleported to "+dest.getName()+".");},60L);warmTasks.put(p.getUniqueId(),task);}
 private void cancel(Player p){BukkitTask t=warmTasks.remove(p.getUniqueId());if(t!=null){t.cancel();warmStart.remove(p.getUniqueId());p.sendMessage(ChatColor.RED+"Teleport cancelled.");}}
 @EventHandler public void move(PlayerMoveEvent e){Location s=warmStart.get(e.getPlayer().getUniqueId());if(s!=null&&e.getTo()!=null&&(s.getWorld()!=e.getTo().getWorld()||s.distanceSquared(e.getTo())>0.04))cancel(e.getPlayer());}@EventHandler public void damage(EntityDamageEvent e){if(e.getEntity() instanceof Player p&&warmTasks.containsKey(p.getUniqueId()))cancel(p);}
 @EventHandler public void quit(PlayerQuitEvent e){UUID id=e.getPlayer().getUniqueId();BukkitTask task=warmTasks.remove(id);if(task!=null)task.cancel();warmStart.remove(id);cooldown.remove(id);back.remove(id);requests.remove(id);requests.entrySet().removeIf(x->x.getValue().sender().equals(id));}
}