package com.esn.smp.gameplay;
import org.bukkit.*;import org.bukkit.command.*;import org.bukkit.entity.Player;import org.bukkit.event.*;import org.bukkit.event.entity.EntityDamageEvent;import org.bukkit.event.player.PlayerMoveEvent;import org.bukkit.plugin.java.JavaPlugin;import org.bukkit.scheduler.BukkitTask;import java.util.*;
public final class Teleports implements CommandExecutor,Listener{
 private record Request(UUID sender,boolean here,long expires){} private final JavaPlugin plugin;private final Map<UUID,Request> requests=new HashMap<>();private final Map<UUID,Long> cooldown=new HashMap<>();private final Map<UUID,Location> back=new HashMap<>(),warmStart=new HashMap<>();private final Map<UUID,BukkitTask> warmTasks=new HashMap<>();private final Set<UUID> disabled=new HashSet<>();
 public Teleports(JavaPlugin p){plugin=p;}
 public boolean onCommand(CommandSender s,Command c,String l,String[] a){if(!(s instanceof Player p))return true;String n=c.getName().toLowerCase();if(n.equals("tptoggle")){if(!disabled.add(p.getUniqueId())){disabled.remove(p.getUniqueId());p.sendMessage(ChatColor.GREEN+"Teleport requests enabled.");}else p.sendMessage(ChatColor.YELLOW+"Teleport requests disabled.");return true;}if(n.equals("tpa")||n.equals("tpahere")){if(a.length<1){p.sendMessage(ChatColor.RED+"/"+n+" <player>");return true;}Player t=Bukkit.getPlayerExact(a[0]);if(t==null||t==p){p.sendMessage(ChatColor.RED+"Player not found.");return true;}if(disabled.contains(t.getUniqueId())){p.sendMessage(ChatColor.RED+"That player has teleport requests disabled.");return true;}requests.put(t.getUniqueId(),new Request(p.getUniqueId(),n.equals("tpahere"),System.currentTimeMillis()+60000));t.sendMessage(ChatColor.GOLD+p.getName()+(n.equals("tpahere")?" wants you to teleport to them.":" wants to teleport to you.")+" /tpaccept or /tpdeny");p.sendMessage(ChatColor.GREEN+"Teleport request sent. Expires in 60 seconds.");return true;}if(n.equals("tpaccept")){Request q=requests.remove(p.getUniqueId());Player r=q==null?null:Bukkit.getPlayer(q.sender());if(q==null||r==null||q.expires()<System.currentTimeMillis()){p.sendMessage(ChatColor.RED+"No active request.");return true;}Player moving=q.here()?p:r;Player dest=q.here()?r:p;if(cooldown.getOrDefault(moving.getUniqueId(),0L)>System.currentTimeMillis()){moving.sendMessage(ChatColor.RED+"Teleport is on cooldown.");return true;}startWarmup(moving,dest);return true;}if(n.equals("tpdeny")){requests.remove(p.getUniqueId());p.sendMessage(ChatColor.YELLOW+"Request denied.");return true;}if(n.equals("back")){Location b=back.get(p.getUniqueId());if(b==null)p.sendMessage(ChatColor.RED+"No previous location.");else{Location old=p.getLocation().clone();p.teleport(b);back.put(p.getUniqueId(),old);}return true;}return true;}
 private void startWarmup(Player p,Player dest){Location start=p.getLocation().clone();warmStart.put(p.getUniqueId(),start);p.sendMessage(ChatColor.YELLOW+"Teleporting in 3 seconds. Moving or taking damage cancels.");BukkitTask task=plugin.getServer().getScheduler().runTaskLater(plugin,()->{warmTasks.remove(p.getUniqueId());warmStart.remove(p.getUniqueId());if(!p.isOnline()||!dest.isOnline())return;back.put(p.getUniqueId(),p.getLocation().clone());p.teleport(dest.getLocation());cooldown.put(p.getUniqueId(),System.currentTimeMillis()+15000);p.sendMessage(ChatColor.GREEN+"Teleported to "+dest.getName()+".");},60L);warmTasks.put(p.getUniqueId(),task);}
 private void cancel(Player p){BukkitTask t=warmTasks.remove(p.getUniqueId());if(t!=null){t.cancel();warmStart.remove(p.getUniqueId());p.sendMessage(ChatColor.RED+"Teleport cancelled.");}}
 @EventHandler public void move(PlayerMoveEvent e){Location s=warmStart.get(e.getPlayer().getUniqueId());if(s!=null&&e.getTo()!=null&&(s.getWorld()!=e.getTo().getWorld()||s.distanceSquared(e.getTo())>0.04))cancel(e.getPlayer());}@EventHandler public void damage(EntityDamageEvent e){if(e.getEntity() instanceof Player p&&warmTasks.containsKey(p.getUniqueId()))cancel(p);}
}