package com.esn.smp.gameplay;
import com.esn.smp.data.ESNDataStore;import org.bukkit.*;import org.bukkit.command.*;import org.bukkit.entity.*;import org.bukkit.event.*;import org.bukkit.event.block.BlockBreakEvent;import org.bukkit.event.entity.*;import org.bukkit.event.player.*;import org.bukkit.inventory.ItemStack;import org.bukkit.plugin.java.JavaPlugin;import java.io.File;import java.sql.*;import java.util.*;
public final class V18Core implements CommandExecutor,Listener,AutoCloseable{
 private final JavaPlugin plugin;private final ESNDataStore economy;private Connection db;private final Map<UUID,Long> combat=new HashMap<>(),tradeReq=new HashMap<>();private final Map<UUID,Location> graves=new HashMap<>();
 public V18Core(JavaPlugin p,ESNDataStore e)throws Exception{plugin=p;economy=e;Class.forName("org.sqlite.JDBC");db=DriverManager.getConnection("jdbc:sqlite:"+new File(p.getDataFolder(),"esnsmp-v18.db"));try(Statement s=db.createStatement()){s.execute("CREATE TABLE IF NOT EXISTS progression(uuid TEXT PRIMARY KEY,xp INTEGER NOT NULL DEFAULT 0,level INTEGER NOT NULL DEFAULT 1,quest_mined INTEGER NOT NULL DEFAULT 0,quest_kills INTEGER NOT NULL DEFAULT 0,quest_day INTEGER NOT NULL DEFAULT 0,streak INTEGER NOT NULL DEFAULT 0,last_daily INTEGER NOT NULL DEFAULT 0,achievements TEXT NOT NULL DEFAULT '')");s.execute("CREATE TABLE IF NOT EXISTS teams(name TEXT PRIMARY KEY,owner TEXT NOT NULL,members TEXT NOT NULL DEFAULT '')");s.execute("CREATE TABLE IF NOT EXISTS bounties(target TEXT PRIMARY KEY,amount INTEGER NOT NULL DEFAULT 0)");s.execute("CREATE TABLE IF NOT EXISTS moderation(id INTEGER PRIMARY KEY AUTOINCREMENT,staff TEXT,target TEXT,action TEXT,reason TEXT,created INTEGER)");}}
 private void ensure(Player p)throws SQLException{try(PreparedStatement q=db.prepareStatement("INSERT OR IGNORE INTO progression(uuid) VALUES(?)")){q.setString(1,p.getUniqueId().toString());q.executeUpdate();}}
 private int get(Player p,String col)throws SQLException{ensure(p);try(PreparedStatement q=db.prepareStatement("SELECT "+col+" FROM progression WHERE uuid=?")){q.setString(1,p.getUniqueId().toString());try(ResultSet r=q.executeQuery()){return r.next()?r.getInt(1):0;}}}
 private void add(Player p,String col,int n)throws SQLException{ensure(p);try(PreparedStatement q=db.prepareStatement("UPDATE progression SET "+col+"="+col+"+? WHERE uuid=?")){q.setInt(1,n);q.setString(2,p.getUniqueId().toString());q.executeUpdate();}if(col.equals("xp"))level(p);}
 private void level(Player p)throws SQLException{int xp=get(p,"xp"),lv=Math.max(1,1+(int)Math.sqrt(xp/100.0));try(PreparedStatement q=db.prepareStatement("UPDATE progression SET level=? WHERE uuid=?")){q.setInt(1,lv);q.setString(2,p.getUniqueId().toString());q.executeUpdate();}}
 private String rank(Player p)throws SQLException{int l=get(p,"level");return p.isOp()?"Owner":l>=50?"Legend":l>=30?"MVP":l>=15?"VIP":"Member";}
 public boolean onCommand(CommandSender s,Command c,String label,String[] a){if(!(s instanceof Player p)){s.sendMessage("Players only.");return true;}String n=c.getName().toLowerCase();try{
  if(n.equals("level")){p.sendMessage(ChatColor.GOLD+"ESN Level "+get(p,"level")+ChatColor.GRAY+" | XP: "+get(p,"xp")+ChatColor.GRAY+" | Rank: "+rank(p));return true;}
  if(n.equals("achievements")){p.sendMessage(ChatColor.AQUA+"Achievements: First Blood (1 kill), Miner I (100 blocks), Veteran (Lv10), Rich (25k Coins). Progress is tracked automatically.");return true;}
  if(n.equals("streak")){p.sendMessage(ChatColor.GOLD+"Daily streak: "+get(p,"streak")+" day(s).");return true;}
  if(n.equals("team")){team(p,a);return true;}if(n.equals("bounty")){bounty(p,a);return true;}if(n.equals("trade")){trade(p,a);return true;}
  if(n.equals("grave")){Location g=graves.get(p.getUniqueId());if(g==null)p.sendMessage(ChatColor.RED+"No recent grave/death location.");else{p.sendMessage(ChatColor.YELLOW+"Last death: "+g.getWorld().getName()+" "+g.getBlockX()+" "+g.getBlockY()+" "+g.getBlockZ());}return true;}
  if(n.equals("season")){p.sendMessage(ChatColor.GOLD+"ESN Season 1"+ChatColor.GRAY+" | Level "+get(p,"level")+" | XP "+get(p,"xp")+" | Quests and leaderboards count toward seasonal progress.");return true;}
  if(n.equals("event")){p.sendMessage(ChatColor.LIGHT_PURPLE+"Current event: "+(Bukkit.getWorlds().get(0).getFullTime()%24000<12000?"Day Rush — +XP from mining":"Night Hunt — +XP from kills"));return true;}
  if(Set.of("staff","invsee","ecsee","freeze","warn","mute","history").contains(n)){staff(p,n,a);return true;}
 }catch(Exception e){p.sendMessage(ChatColor.RED+"That ESN system is temporarily unavailable.");plugin.getLogger().warning(n+": "+e.getMessage());}return true;}
 private void team(Player p,String[] a)throws SQLException{if(a.length==0){p.sendMessage(ChatColor.GOLD+"/team <create|join|leave|info>");return;}String sub=a[0].toLowerCase();if(sub.equals("create")&&a.length>1){try(PreparedStatement q=db.prepareStatement("INSERT INTO teams(name,owner,members) VALUES(?,?,?)")){q.setString(1,a[1].toLowerCase());q.setString(2,p.getUniqueId().toString());q.setString(3,p.getUniqueId().toString());q.executeUpdate();}p.sendMessage(ChatColor.GREEN+"Team created.");}else if(sub.equals("join")&&a.length>1){try(PreparedStatement q=db.prepareStatement("UPDATE teams SET members=members||','||? WHERE name=?")){q.setString(1,p.getUniqueId().toString());q.setString(2,a[1].toLowerCase());if(q.executeUpdate()==0)p.sendMessage(ChatColor.RED+"Team not found.");else p.sendMessage(ChatColor.GREEN+"Joined team.");}}else if(sub.equals("leave")){try(PreparedStatement q=db.prepareStatement("UPDATE teams SET members=REPLACE(REPLACE(members,?||',',''),','||?,'')")){q.setString(1,p.getUniqueId().toString());q.setString(2,p.getUniqueId().toString());q.executeUpdate();}p.sendMessage(ChatColor.YELLOW+"Left team memberships.");}else if(sub.equals("info")&&a.length>1){try(PreparedStatement q=db.prepareStatement("SELECT owner,members FROM teams WHERE name=?")){q.setString(1,a[1].toLowerCase());try(ResultSet r=q.executeQuery()){p.sendMessage(r.next()?ChatColor.GOLD+"Team "+a[1]+" | Members: "+r.getString(2).split(",").length:ChatColor.RED+"Team not found.");}}}}
 private void bounty(Player p,String[] a)throws Exception{if(a.length==0){try(Statement q=db.createStatement();ResultSet r=q.executeQuery("SELECT target,amount FROM bounties ORDER BY amount DESC LIMIT 10")){p.sendMessage(ChatColor.RED+"--- Bounties ---");while(r.next())p.sendMessage(Bukkit.getOfflinePlayer(UUID.fromString(r.getString(1))).getName()+": "+r.getLong(2)+" Coins");}return;}if(a.length<2){p.sendMessage(ChatColor.RED+"/bounty <player> <coins>");return;}OfflinePlayer t=PlayerResolver.offline(a[0]);long amt=Long.parseLong(a[1]);if(amt<=0||!economy.withdraw(p,amt)){p.sendMessage(ChatColor.RED+"Invalid amount or insufficient coins.");return;}try(PreparedStatement q=db.prepareStatement("INSERT INTO bounties(target,amount) VALUES(?,?) ON CONFLICT(target) DO UPDATE SET amount=amount+excluded.amount")){q.setString(1,t.getUniqueId().toString());q.setLong(2,amt);q.executeUpdate();}p.sendMessage(ChatColor.GREEN+"Bounty placed.");}
 private void trade(Player p,String[] a){if(a.length<1){p.sendMessage(ChatColor.RED+"/trade <player>");return;}Player t=PlayerResolver.online(a[0]);if(t==null||t==p){p.sendMessage(ChatColor.RED+"Player not found.");return;}if(tradeReq.getOrDefault(p.getUniqueId(),0L)>System.currentTimeMillis()){ItemStack mine=p.getInventory().getItemInMainHand().clone(),theirs=t.getInventory().getItemInMainHand().clone();if(mine.getType().isAir()||theirs.getType().isAir()){p.sendMessage(ChatColor.RED+"Both players must hold the item they want to trade.");return;}p.getInventory().setItemInMainHand(theirs);t.getInventory().setItemInMainHand(mine);tradeReq.remove(p.getUniqueId());p.sendMessage(ChatColor.GREEN+"Trade completed.");t.sendMessage(ChatColor.GREEN+"Trade completed.");}else{tradeReq.put(t.getUniqueId(),System.currentTimeMillis()+30000);t.sendMessage(ChatColor.GOLD+p.getName()+" wants to trade held items. Hold your offer and use /trade "+p.getName());p.sendMessage(ChatColor.GREEN+"Trade request sent.");}}
 private void staff(Player p,String n,String[] a)throws SQLException{if(!p.hasPermission("esnsmp.staff")){p.sendMessage(ChatColor.RED+"No permission.");return;}if(n.equals("staff")){p.sendMessage(ChatColor.GOLD+"Staff: /invsee /ecsee /freeze /warn /mute /history");return;}if(a.length<1){p.sendMessage(ChatColor.RED+"/"+n+" <player> [reason]");return;}Player t=PlayerResolver.online(a[0]);if(t==null){p.sendMessage(ChatColor.RED+"Player must be online.");return;}if(n.equals("invsee"))p.openInventory(t.getInventory());else if(n.equals("ecsee"))p.openInventory(t.getEnderChest());else if(n.equals("freeze")){t.setFreezeTicks(t.getMaxFreezeTicks());t.sendMessage(ChatColor.RED+"You were frozen by staff.");}else if(n.equals("warn"))t.sendMessage(ChatColor.RED+"Staff warning: "+String.join(" ",Arrays.copyOfRange(a,1,a.length)));else if(n.equals("mute")){t.setMetadata("esnMuted",new org.bukkit.metadata.FixedMetadataValue(plugin,true));t.sendMessage(ChatColor.RED+"You were muted until restart.");}else if(n.equals("history")){try(PreparedStatement q=db.prepareStatement("SELECT action,reason FROM moderation WHERE target=? ORDER BY id DESC LIMIT 10")){q.setString(1,t.getUniqueId().toString());try(ResultSet r=q.executeQuery()){while(r.next())p.sendMessage(ChatColor.YELLOW+r.getString(1)+": "+r.getString(2));}}return;}try(PreparedStatement q=db.prepareStatement("INSERT INTO moderation(staff,target,action,reason,created) VALUES(?,?,?,?,?)")){q.setString(1,p.getUniqueId().toString());q.setString(2,t.getUniqueId().toString());q.setString(3,n);q.setString(4,a.length>1?String.join(" ",Arrays.copyOfRange(a,1,a.length)):"");q.setLong(5,System.currentTimeMillis());q.executeUpdate();}}
 public boolean combatTagged(Player p){return combat.getOrDefault(p.getUniqueId(),0L)>System.currentTimeMillis();}
 @EventHandler public void hit(EntityDamageByEntityEvent e){Player a=e.getDamager() instanceof Player x?x:e.getDamager() instanceof Projectile pr&&pr.getShooter() instanceof Player x?x:null;Player v=e.getEntity() instanceof Player x?x:null;if(a!=null&&v!=null){long until=System.currentTimeMillis()+15000;combat.put(a.getUniqueId(),until);combat.put(v.getUniqueId(),until);}}
 @EventHandler public void quit(PlayerQuitEvent e){if(combatTagged(e.getPlayer())){e.getPlayer().setHealth(0);Bukkit.broadcastMessage(ChatColor.RED+e.getPlayer().getName()+" combat logged!");}}
 @EventHandler public void chat(AsyncPlayerChatEvent e){if(e.getPlayer().hasMetadata("esnMuted"))e.setCancelled(true);}
 @EventHandler public void mine(BlockBreakEvent e){try{add(e.getPlayer(),"quest_mined",1);add(e.getPlayer(),"xp",Bukkit.getWorlds().get(0).getFullTime()%24000<12000?2:1);checkQuest(e.getPlayer());}catch(Exception ignored){}}
 @EventHandler public void kill(EntityDeathEvent e){Player p=e.getEntity().getKiller();if(p==null)return;try{add(p,"quest_kills",1);add(p,"xp",Bukkit.getWorlds().get(0).getFullTime()%24000>=12000?10:5);checkQuest(p);if(e.getEntity() instanceof Player dead){try(PreparedStatement q=db.prepareStatement("SELECT amount FROM bounties WHERE target=?")){q.setString(1,dead.getUniqueId().toString());try(ResultSet r=q.executeQuery()){if(r.next()){long amt=r.getLong(1);economy.deposit(p,amt);try(PreparedStatement d=db.prepareStatement("DELETE FROM bounties WHERE target=?")){d.setString(1,dead.getUniqueId().toString());d.executeUpdate();}Bukkit.broadcastMessage(ChatColor.GOLD+p.getName()+" claimed a "+amt+" Coin bounty on "+dead.getName()+"!");}}}}}catch(Exception ignored){}}
 private void checkQuest(Player p)throws Exception{int day=(int)(System.currentTimeMillis()/86400000L);ensure(p);int stored=get(p,"quest_day");if(stored!=day){try(PreparedStatement q=db.prepareStatement("UPDATE progression SET quest_day=?,quest_mined=0,quest_kills=0 WHERE uuid=?")){q.setInt(1,day);q.setString(2,p.getUniqueId().toString());q.executeUpdate();}return;}int m=get(p,"quest_mined"),k=get(p,"quest_kills");if(m==64){economy.deposit(p,300);add(p,"xp",100);p.sendMessage(ChatColor.GREEN+"Mining quest complete: +300 Coins +100 XP");}if(k==10){economy.deposit(p,500);add(p,"xp",150);p.getInventory().addItem(LootDrops.key());p.sendMessage(ChatColor.GREEN+"Hunt quest complete: +500 Coins +150 XP + Crate Key");}}
 @EventHandler public void death(PlayerDeathEvent e){graves.put(e.getEntity().getUniqueId(),e.getEntity().getLocation().clone());e.getEntity().sendMessage(ChatColor.YELLOW+"Death location saved. Use /grave after respawning.");}
 @EventHandler public void join(PlayerJoinEvent e){try{ensure(e.getPlayer());long now=System.currentTimeMillis(),last;try(PreparedStatement q=db.prepareStatement("SELECT last_daily FROM progression WHERE uuid=?")){q.setString(1,e.getPlayer().getUniqueId().toString());try(ResultSet r=q.executeQuery()){last=r.next()?r.getLong(1):0;}}if(now-last>=86400000L){int streak=now-last<=172800000L?get(e.getPlayer(),"streak")+1:1;try(PreparedStatement q=db.prepareStatement("UPDATE progression SET streak=?,last_daily=? WHERE uuid=?")){q.setInt(1,streak);q.setLong(2,now);q.setString(3,e.getPlayer().getUniqueId().toString());q.executeUpdate();}e.getPlayer().sendMessage(ChatColor.GOLD+"Login streak: "+streak+" day(s)!");}}catch(Exception ignored){}}
 public void close()throws Exception{if(db!=null)db.close();}
}