package com.esn.smp.gameplay;
import com.esn.smp.data.ESNDataStore;
import org.bukkit.*;import org.bukkit.block.*;import org.bukkit.command.*;import org.bukkit.entity.*;import org.bukkit.event.*;import org.bukkit.event.entity.PlayerDeathEvent;import org.bukkit.event.inventory.*;import org.bukkit.event.player.*;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.ItemMeta;import org.bukkit.persistence.*;import org.bukkit.plugin.java.JavaPlugin;import java.util.*;
public final class V19Core implements Listener,CommandExecutor{
 private final JavaPlugin p;private final ESNDataStore eco;private final Map<UUID,Grave> graves=new HashMap<>();private final Map<UUID,UUID> tradeReq=new HashMap<>();private final Map<UUID,Trade> trades=new HashMap<>();private final NamespacedKey itemKey;
 record Grave(Location loc,long expires){}
 static final class Trade{final UUID a,b;final Inventory inv;boolean ca,cb,finishing;Trade(UUID a,UUID b,Inventory i){this.a=a;this.b=b;this.inv=i;}}
 public V19Core(JavaPlugin p,ESNDataStore e){this.p=p;eco=e;itemKey=new NamespacedKey(p,"secure_item");Bukkit.getScheduler().runTaskTimer(p,this::cleanupGraves,20L,20L);}
 public boolean onCommand(CommandSender s,Command c,String l,String[] a){if(!(s instanceof Player x)){s.sendMessage("Players only.");return true;}switch(c.getName()){
  case "pass"->pass(x);case "upgrade"->upgrade(x);case "tradegui"->trade(x,a);case "grave"->grave(x);case "tutorial"->tutorial(x);default->{} }return true;}
 private void pass(Player x){Inventory i=Bukkit.createInventory(null,27,"ESN Season Pass");for(int n=0;n<9;n++){ItemStack it=new ItemStack(n%3==0?Material.TRIPWIRE_HOOK:n%3==1?Material.DIAMOND:Material.GOLD_INGOT);ItemMeta m=it.getItemMeta();m.setDisplayName(ChatColor.GOLD+"Tier "+(n+1));m.setLore(List.of(ChatColor.GRAY+"Season reward track",ChatColor.YELLOW+"Complete quests to progress"));it.setItemMeta(m);i.setItem(9+n,it);}x.openInventory(i);}
 private void upgrade(Player x){ItemStack it=x.getInventory().getItemInMainHand();if(it.getType().isAir()){x.sendMessage(ChatColor.RED+"Hold an ESN item to upgrade.");return;}ItemMeta m=it.getItemMeta();if(m==null||!m.hasDisplayName()){x.sendMessage(ChatColor.RED+"That is not an upgradeable ESN item.");return;}int lv=m.getPersistentDataContainer().getOrDefault(new NamespacedKey(p,"upgrade_level"),PersistentDataType.INTEGER,0);if(lv>=5){x.sendMessage(ChatColor.GOLD+"This item is already max level.");return;}long cost=(lv+1)*1000L;try{if(!eco.withdraw(x,cost)){x.sendMessage(ChatColor.RED+"You need "+cost+" ESN Coins.");return;}}catch(Exception ex){x.sendMessage(ChatColor.RED+"Economy unavailable.");return;}m.getPersistentDataContainer().set(new NamespacedKey(p,"upgrade_level"),PersistentDataType.INTEGER,lv+1);List<String> lore=m.hasLore()?new ArrayList<>(m.getLore()):new ArrayList<>();lore.removeIf(z->ChatColor.stripColor(z).startsWith("Upgrade:"));lore.add(ChatColor.LIGHT_PURPLE+"Upgrade: +"+(lv+1));m.setLore(lore);it.setItemMeta(m);x.sendMessage(ChatColor.GREEN+"Item upgraded to +"+(lv+1)+"!");}
 private void trade(Player x,String[] a){if(a.length<1){x.sendMessage(ChatColor.RED+"/tradegui <player>");return;}Player y=PlayerResolver.online(a[0]);if(y==null||y==x){x.sendMessage(ChatColor.RED+"Player not found.");return;}if(x.getLocation().distanceSquared(y.getLocation())>100){x.sendMessage(ChatColor.RED+"You must be within 10 blocks.");return;}if(Objects.equals(tradeReq.get(x.getUniqueId()),y.getUniqueId())){Inventory inv=Bukkit.createInventory(null,27,"ESN Secure Trade");inv.setItem(4,button(Material.RED_CONCRETE,ChatColor.RED+"Both players must confirm"));inv.setItem(22,button(Material.RED_CONCRETE,ChatColor.RED+"Click to confirm trade"));Trade t=new Trade(x.getUniqueId(),y.getUniqueId(),inv);trades.put(x.getUniqueId(),t);trades.put(y.getUniqueId(),t);x.openInventory(inv);y.openInventory(inv);tradeReq.remove(x.getUniqueId());tradeReq.remove(y.getUniqueId());}else{tradeReq.put(y.getUniqueId(),x.getUniqueId());x.sendMessage(ChatColor.GREEN+"Trade request sent.");y.sendMessage(ChatColor.GOLD+x.getName()+" wants to trade. Use /tradegui "+x.getName());}}
 private void grave(Player x){Grave g=graves.get(x.getUniqueId());if(g==null){x.sendMessage(ChatColor.RED+"You have no active grave.");return;}long sec=Math.max(0,(g.expires-System.currentTimeMillis())/1000);x.sendMessage(ChatColor.YELLOW+"Grave: "+g.loc.getBlockX()+" "+g.loc.getBlockY()+" "+g.loc.getBlockZ()+ChatColor.GRAY+" | disappears in "+sec+"s");}
 private void tutorial(Player x){x.sendMessage(ChatColor.GOLD+"ESN SMP QUICK START");x.sendMessage(ChatColor.YELLOW+"/menu "+ChatColor.GRAY+"main hub | "+ChatColor.YELLOW+"/quests "+ChatColor.GRAY+"progress | "+ChatColor.YELLOW+"/pass "+ChatColor.GRAY+"season pass");x.sendMessage(ChatColor.YELLOW+"/claim "+ChatColor.GRAY+"protect land | "+ChatColor.YELLOW+"/team "+ChatColor.GRAY+"teams | "+ChatColor.YELLOW+"/ah "+ChatColor.GRAY+"auction house | "+ChatColor.YELLOW+"/crates "+ChatColor.GRAY+"rewards");}
 @EventHandler public void death(PlayerDeathEvent e){Player x=e.getEntity();if(e.getDrops().isEmpty())return;Location l=x.getLocation().getBlock().getLocation();Block b=l.getBlock();if(!b.getType().isAir())l.add(0,1,0);b=l.getBlock();b.setType(Material.BARREL);if(b.getState() instanceof Barrel box){for(ItemStack it:new ArrayList<>(e.getDrops()))box.getInventory().addItem(it);box.update();e.getDrops().clear();long exp=System.currentTimeMillis()+600000L;graves.put(x.getUniqueId(),new Grave(l.clone(),exp));x.sendMessage(ChatColor.GOLD+"Your protected grave will disappear in 10 minutes. Use /grave.");}}
 @EventHandler public void interact(PlayerInteractEvent e){Block b=e.getClickedBlock();if(b==null)return;for(var z:graves.entrySet())if(z.getValue().loc.getBlock().equals(b)){if(!z.getKey().equals(e.getPlayer().getUniqueId())){e.setCancelled(true);e.getPlayer().sendMessage(ChatColor.RED+"That grave belongs to another player.");}return;}}
 @EventHandler public void breakBlock(org.bukkit.event.block.BlockBreakEvent e){for(var z:graves.entrySet())if(z.getValue().loc.getBlock().equals(e.getBlock())){if(!z.getKey().equals(e.getPlayer().getUniqueId())){e.setCancelled(true);return;}graves.remove(z.getKey());return;}}
 private void cleanupGraves(){long now=System.currentTimeMillis();for(var it=graves.entrySet().iterator();it.hasNext();){var z=it.next();if(z.getValue().expires<=now){Block b=z.getValue().loc.getBlock();if(b.getState() instanceof Barrel box)box.getInventory().clear();b.setType(Material.AIR);it.remove();}}}
 @EventHandler public void click(InventoryClickEvent e){if(!e.getView().getTitle().equals("ESN Secure Trade"))return;if(!(e.getWhoClicked() instanceof Player x))return;Trade t=trades.get(x.getUniqueId());if(t==null){e.setCancelled(true);return;}int slot=e.getRawSlot();if(slot==22){e.setCancelled(true);if(t.a.equals(x.getUniqueId()))t.ca=!t.ca;else t.cb=!t.cb;t.inv.setItem(4,button(t.ca&&t.cb?Material.LIME_CONCRETE:Material.YELLOW_CONCRETE,(t.ca&&t.cb?ChatColor.GREEN+"TRADE CONFIRMED":ChatColor.YELLOW+"Waiting: "+(t.ca?"A✓ ":"A… ")+(t.cb?"B✓":"B…"))));if(t.ca&&t.cb)completeTrade(t);return;}if(slot>=0&&slot<27){boolean left=t.a.equals(x.getUniqueId());boolean allowed=left?slot%9<4:slot%9>4;if(!allowed)e.setCancelled(true);}}
 @EventHandler public void close(InventoryCloseEvent e){if(!e.getView().getTitle().equals("ESN Secure Trade"))return;Trade t=trades.remove(e.getPlayer().getUniqueId());if(t!=null){trades.remove(t.a);trades.remove(t.b);returnTrade(t);}}
 private ItemStack button(Material mat,String name){ItemStack i=new ItemStack(mat);ItemMeta m=i.getItemMeta();m.setDisplayName(name);i.setItemMeta(m);return i;}
 private void completeTrade(Trade t){if(t.finishing)return;t.finishing=true;Player a=Bukkit.getPlayer(t.a),b=Bukkit.getPlayer(t.b);if(a==null||b==null){returnTrade(t);return;}List<ItemStack> ai=new ArrayList<>(),bi=new ArrayList<>();for(int s=0;s<27;s++){ItemStack it=t.inv.getItem(s);if(it==null||s==4||s==22)continue;if(s%9<4)ai.add(it.clone());else if(s%9>4)bi.add(it.clone());}for(int s=0;s<27;s++)if(s!=4&&s!=22)t.inv.setItem(s,null);for(ItemStack it:ai)a.getInventory().addItem(it).values().forEach(z->a.getWorld().dropItemNaturally(a.getLocation(),z));for(ItemStack it:bi)b.getInventory().addItem(it).values().forEach(z->b.getWorld().dropItemNaturally(b.getLocation(),z));trades.remove(t.a);trades.remove(t.b);a.closeInventory();b.closeInventory();a.sendMessage(ChatColor.GREEN+"Secure trade completed.");b.sendMessage(ChatColor.GREEN+"Secure trade completed.");}
 private void returnTrade(Trade t){Player a=Bukkit.getPlayer(t.a),b=Bukkit.getPlayer(t.b);for(int s=0;s<27;s++){ItemStack it=t.inv.getItem(s);if(it==null)continue;Player to=s%9<4?a:b;if(to!=null)to.getInventory().addItem(it);t.inv.setItem(s,null);}}
 public ItemStack secure(ItemStack it,String id){ItemMeta m=it.getItemMeta();m.getPersistentDataContainer().set(itemKey,PersistentDataType.STRING,id);it.setItemMeta(m);return it;}
}